import { DurionSdkConfig } from '@durion-sdk/transport';
import * as GeneratedApis from './apis';
export declare function createWorkorderClient(config: DurionSdkConfig): {
    approvalConfigurationAPIApi: GeneratedApis.ApprovalConfigurationAPIApi;
    changeRequestAPIApi: GeneratedApis.ChangeRequestAPIApi;
    dailyDispatchBoardDashboardApi: GeneratedApis.DailyDispatchBoardDashboardApi;
    estimateAPIApi: GeneratedApis.EstimateAPIApi;
    estimateSearchApi: GeneratedApis.EstimateSearchApi;
    estimatesFromAppointmentsApi: GeneratedApis.EstimatesFromAppointmentsApi;
    operationalContextApi: GeneratedApis.OperationalContextApi;
    substituteLinkControllerApi: GeneratedApis.SubstituteLinkControllerApi;
    technicianAssignmentAPIApi: GeneratedApis.TechnicianAssignmentAPIApi;
    timeEntryAPIApi: GeneratedApis.TimeEntryAPIApi;
    travelSegmentAPIApi: GeneratedApis.TravelSegmentAPIApi;
    wipDashboardApi: GeneratedApis.WIPDashboardApi;
    workOrderAPIApi: GeneratedApis.WorkOrderAPIApi;
    workSessionAPIApi: GeneratedApis.WorkSessionAPIApi;
    workexecTimeTrackingAPIApi: GeneratedApis.WorkexecTimeTrackingAPIApi;
    workorderDetailApi: GeneratedApis.WorkorderDetailApi;
    workorderLaborAPIApi: GeneratedApis.WorkorderLaborAPIApi;
    workorderPartAdjustmentsApi: GeneratedApis.WorkorderPartAdjustmentsApi;
    workorderPartsUsageApi: GeneratedApis.WorkorderPartsUsageApi;
};
export { WorkorderEstimateWorkflow } from './workflows/workorderEstimateWorkflow';
export { WorkorderChangeRequestWorkflow } from './workflows/workorderChangeRequestWorkflow';
export * from './runtime';
export * from './apis/index';
export * from './models/index';
