/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Customer API
 * API documentation for the Customer service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BulkIngestRequestCommercialBulkIngestRecord,
  BulkIngestResponse,
} from '../models/index';
import {
    BulkIngestRequestCommercialBulkIngestRecordFromJSON,
    BulkIngestRequestCommercialBulkIngestRecordToJSON,
    BulkIngestResponseFromJSON,
    BulkIngestResponseToJSON,
} from '../models/index';

export interface BulkIngestCommercialAccountsRequest {
    bulkIngestRequestCommercialBulkIngestRecord: BulkIngestRequestCommercialBulkIngestRecord;
}

/**
 * 
 */
export class CommercialBulkIngestAPIApi extends runtime.BaseAPI {

    /**
     * Imports a batch of commercial account records, creating each one through the same path as createCrmCommercialAccount and reporting a per-row success or failure result without aborting the batch. Use this tool for migrations and file imports of commercial fleets; individual customers go through bulkIngestCustomers instead. Preconditions: none beyond authorization; rows that fail are reported with errorCode COMMERCIAL_INGEST_FAILED while the rest of the batch proceeds. Required inputs: jobId (UUID), locationId (UUID), and a non-empty records list where each record has legalName (max 255); displayName defaults to the legal name, and taxId and billingTermsId are optional; when contactFirstName and contactLastName are both present, a primary contact person is created (canonical identity lands in pos-people-contact, with contactEmail/contactPhone as its contact points) and attached with the PRIMARY_CONTACT role effective today. Customer numbers are always generated by the service; supplied numbers cannot be preserved, and rows are not deduplicated, so re-running a batch creates duplicate accounts. Account creation and contact attachment are separate transactions: a row whose contact step fails is reported as failed even though its account may already exist. Emits a CUSTOMER_COMMERCIAL_BULK_INGEST event, and each successful row publishes a party-changed customer fact. Returns 200 with per-row results including failures, and 400 when jobId, locationId, or the records list is missing or empty. 
     * Bulk Ingest Commercial Account Records
     */
    async bulkIngestCommercialAccountsRaw(requestParameters: BulkIngestCommercialAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkIngestResponse>> {
        if (requestParameters['bulkIngestRequestCommercialBulkIngestRecord'] == null) {
            throw new runtime.RequiredError(
                'bulkIngestRequestCommercialBulkIngestRecord',
                'Required parameter "bulkIngestRequestCommercialBulkIngestRecord" was null or undefined when calling bulkIngestCommercialAccounts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["crm:party:create"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/customer/commercial/bulk-ingest`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkIngestRequestCommercialBulkIngestRecordToJSON(requestParameters['bulkIngestRequestCommercialBulkIngestRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkIngestResponseFromJSON(jsonValue));
    }

    /**
     * Imports a batch of commercial account records, creating each one through the same path as createCrmCommercialAccount and reporting a per-row success or failure result without aborting the batch. Use this tool for migrations and file imports of commercial fleets; individual customers go through bulkIngestCustomers instead. Preconditions: none beyond authorization; rows that fail are reported with errorCode COMMERCIAL_INGEST_FAILED while the rest of the batch proceeds. Required inputs: jobId (UUID), locationId (UUID), and a non-empty records list where each record has legalName (max 255); displayName defaults to the legal name, and taxId and billingTermsId are optional; when contactFirstName and contactLastName are both present, a primary contact person is created (canonical identity lands in pos-people-contact, with contactEmail/contactPhone as its contact points) and attached with the PRIMARY_CONTACT role effective today. Customer numbers are always generated by the service; supplied numbers cannot be preserved, and rows are not deduplicated, so re-running a batch creates duplicate accounts. Account creation and contact attachment are separate transactions: a row whose contact step fails is reported as failed even though its account may already exist. Emits a CUSTOMER_COMMERCIAL_BULK_INGEST event, and each successful row publishes a party-changed customer fact. Returns 200 with per-row results including failures, and 400 when jobId, locationId, or the records list is missing or empty. 
     * Bulk Ingest Commercial Account Records
     */
    async bulkIngestCommercialAccounts(requestParameters: BulkIngestCommercialAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkIngestResponse> {
        const response = await this.bulkIngestCommercialAccountsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
