"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Customer API
 * API documentation for the Customer service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetContactsRolesEnum = exports.CRMPartyRelationshipsApi = void 0;
const runtime = __importStar(require("../runtime"));
const index_1 = require("../models/index");
/**
 *
 */
class CRMPartyRelationshipsApi extends runtime.BaseAPI {
    /**
     * Creates a relationship between a commercial account and an individual person
     * Create a party relationship
     */
    async createRelationshipRaw(requestParameters, initOverrides) {
        if (requestParameters['partyId'] == null) {
            throw new runtime.RequiredError('partyId', 'Required parameter "partyId" was null or undefined when calling createRelationship().');
        }
        if (requestParameters['createPartyRelationshipRequest'] == null) {
            throw new runtime.RequiredError('createPartyRelationshipRequest', 'Required parameter "createPartyRelationshipRequest" was null or undefined when calling createRelationship().');
        }
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        const response = await this.request({
            path: `/v1/crm/commercial-accounts/{partyId}/relationships`.replace(`{${"partyId"}}`, encodeURIComponent(String(requestParameters['partyId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: (0, index_1.CreatePartyRelationshipRequestToJSON)(requestParameters['createPartyRelationshipRequest']),
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.CreatePartyRelationshipResponseFromJSON)(jsonValue));
    }
    /**
     * Creates a relationship between a commercial account and an individual person
     * Create a party relationship
     */
    async createRelationship(requestParameters, initOverrides) {
        const response = await this.createRelationshipRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Soft-deletes a relationship by setting its effective end date
     * Deactivate a party relationship
     */
    async deactivateRelationshipRaw(requestParameters, initOverrides) {
        if (requestParameters['partyId'] == null) {
            throw new runtime.RequiredError('partyId', 'Required parameter "partyId" was null or undefined when calling deactivateRelationship().');
        }
        if (requestParameters['relationshipId'] == null) {
            throw new runtime.RequiredError('relationshipId', 'Required parameter "relationshipId" was null or undefined when calling deactivateRelationship().');
        }
        const queryParameters = {};
        const headerParameters = {};
        const response = await this.request({
            path: `/v1/crm/commercial-accounts/{partyId}/relationships/{relationshipId}`.replace(`{${"partyId"}}`, encodeURIComponent(String(requestParameters['partyId']))).replace(`{${"relationshipId"}}`, encodeURIComponent(String(requestParameters['relationshipId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.VoidApiResponse(response);
    }
    /**
     * Soft-deletes a relationship by setting its effective end date
     * Deactivate a party relationship
     */
    async deactivateRelationship(requestParameters, initOverrides) {
        await this.deactivateRelationshipRaw(requestParameters, initOverrides);
    }
    /**
     * Sets a relationship as the primary billing contact, demoting any existing primary
     * Designate primary billing contact
     */
    async designatePrimaryBillingContactRaw(requestParameters, initOverrides) {
        if (requestParameters['partyId'] == null) {
            throw new runtime.RequiredError('partyId', 'Required parameter "partyId" was null or undefined when calling designatePrimaryBillingContact().');
        }
        if (requestParameters['relationshipId'] == null) {
            throw new runtime.RequiredError('relationshipId', 'Required parameter "relationshipId" was null or undefined when calling designatePrimaryBillingContact().');
        }
        const queryParameters = {};
        const headerParameters = {};
        const response = await this.request({
            path: `/v1/crm/commercial-accounts/{partyId}/relationships/{relationshipId}/primary-billing`.replace(`{${"partyId"}}`, encodeURIComponent(String(requestParameters['partyId']))).replace(`{${"relationshipId"}}`, encodeURIComponent(String(requestParameters['relationshipId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.VoidApiResponse(response);
    }
    /**
     * Sets a relationship as the primary billing contact, demoting any existing primary
     * Designate primary billing contact
     */
    async designatePrimaryBillingContact(requestParameters, initOverrides) {
        await this.designatePrimaryBillingContactRaw(requestParameters, initOverrides);
    }
    /**
     * Retrieves all individuals associated with a commercial account with their roles
     * Get contacts for a commercial account
     */
    async getContactsRaw(requestParameters, initOverrides) {
        if (requestParameters['partyId'] == null) {
            throw new runtime.RequiredError('partyId', 'Required parameter "partyId" was null or undefined when calling getContacts().');
        }
        const queryParameters = {};
        if (requestParameters['roles'] != null) {
            queryParameters['roles'] = requestParameters['roles'];
        }
        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }
        const headerParameters = {};
        const response = await this.request({
            path: `/v1/crm/commercial-accounts/{partyId}/contacts`.replace(`{${"partyId"}}`, encodeURIComponent(String(requestParameters['partyId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.GetCommercialAccountContactsResponseFromJSON)(jsonValue));
    }
    /**
     * Retrieves all individuals associated with a commercial account with their roles
     * Get contacts for a commercial account
     */
    async getContacts(requestParameters, initOverrides) {
        const response = await this.getContactsRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
exports.CRMPartyRelationshipsApi = CRMPartyRelationshipsApi;
/**
  * @export
  * @enum {string}
  */
var GetContactsRolesEnum;
(function (GetContactsRolesEnum) {
    GetContactsRolesEnum["Approver"] = "APPROVER";
    GetContactsRolesEnum["Billing"] = "BILLING";
    GetContactsRolesEnum["PrimaryContact"] = "PRIMARY_CONTACT";
    GetContactsRolesEnum["Driver"] = "DRIVER";
    GetContactsRolesEnum["Technical"] = "TECHNICAL";
})(GetContactsRolesEnum || (exports.GetContactsRolesEnum = GetContactsRolesEnum = {}));
