/* tslint:disable */
/* eslint-disable */
/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for setting the tenant's accounting-calendar time zone
 * @export
 * @interface AccountingTimeZoneUpdateRequest
 */
export interface AccountingTimeZoneUpdateRequest {
    /**
     * IANA region id of the tenant's accounting calendar, such as America/Chicago. Every settlement, application and posting is dated, and every period is cut, in this zone. Fixed offsets (+05:00, UTC+05:00, Etc/GMT+5) and SystemV ids are rejected; UTC is accepted.
     * @type {string}
     * @memberof AccountingTimeZoneUpdateRequest
     */
    timeZone: string;
}

/**
 * Check if a given object implements the AccountingTimeZoneUpdateRequest interface.
 */
export function instanceOfAccountingTimeZoneUpdateRequest(value: object): boolean {
    if (!('timeZone' in value)) return false;
    return true;
}

export function AccountingTimeZoneUpdateRequestFromJSON(json: any): AccountingTimeZoneUpdateRequest {
    return AccountingTimeZoneUpdateRequestFromJSONTyped(json, false);
}

export function AccountingTimeZoneUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingTimeZoneUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'timeZone': json['timeZone'],
    };
}

export function AccountingTimeZoneUpdateRequestToJSON(value?: AccountingTimeZoneUpdateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'timeZone': value['timeZone'],
    };
}

