/* tslint:disable */
/* eslint-disable */
/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A payment application made automatically, with what it did and whether it was undone
 * @export
 * @interface AutomaticPaymentApplicationRow
 */
export interface AutomaticPaymentApplicationRow {
    /**
     * Commands the caller may run on this row: UNDO when it is not reversed and the caller holds accounting:payment:reverse, else empty
     * @type {Array<string>}
     * @memberof AutomaticPaymentApplicationRow
     */
    actions: Array<string>;
    /**
     * Amount applied to the invoice
     * @type {number}
     * @memberof AutomaticPaymentApplicationRow
     */
    appliedAmount: number;
    /**
     * Application date: the settlement instant for PAYMENT_SETTLED
     * @type {Date}
     * @memberof AutomaticPaymentApplicationRow
     */
    appliedAt: Date;
    /**
     * Customer credit the same application created for an amount beyond the invoice's balance; null when none
     * @type {number}
     * @memberof AutomaticPaymentApplicationRow
     */
    creditCreatedAmount?: number;
    /**
     * Currency (ISO 4217)
     * @type {string}
     * @memberof AutomaticPaymentApplicationRow
     */
    currency: string;
    /**
     * Customer name from accounting's customer replica; null when unknown
     * @type {string}
     * @memberof AutomaticPaymentApplicationRow
     */
    customerDisplayName?: string;
    /**
     * Customer number from accounting's customer replica; null when unknown
     * @type {string}
     * @memberof AutomaticPaymentApplicationRow
     */
    customerReference?: string;
    /**
     * Invoice the payment was applied to
     * @type {string}
     * @memberof AutomaticPaymentApplicationRow
     */
    invoiceId: string;
    /**
     * Invoice number from accounting's invoice replica; null when unknown
     * @type {string}
     * @memberof AutomaticPaymentApplicationRow
     */
    invoiceNumber?: string;
    /**
     * Payment application identifier, for reversePaymentApplication
     * @type {string}
     * @memberof AutomaticPaymentApplicationRow
     */
    paymentApplicationId: string;
    /**
     * Receivable payment applied
     * @type {string}
     * @memberof AutomaticPaymentApplicationRow
     */
    paymentId: string;
    /**
     * Whether the application has been undone (reversed)
     * @type {boolean}
     * @memberof AutomaticPaymentApplicationRow
     */
    reversed: boolean;
    /**
     * When the application was undone; null when it was not
     * @type {Date}
     * @memberof AutomaticPaymentApplicationRow
     */
    reversedAt?: Date;
    /**
     * Path that made the application: PAYMENT_SETTLED (when the payment settled) or INVOICE_PAYMENT (the INVOICE_PAYMENT accounting event)
     * @type {string}
     * @memberof AutomaticPaymentApplicationRow
     */
    source: AutomaticPaymentApplicationRowSourceEnum;
}

/**
* @export
* @enum {string}
*/
export enum AutomaticPaymentApplicationRowSourceEnum {
    PaymentSettled = 'PAYMENT_SETTLED',
    InvoicePayment = 'INVOICE_PAYMENT'
}


/**
 * Check if a given object implements the AutomaticPaymentApplicationRow interface.
 */
export function instanceOfAutomaticPaymentApplicationRow(value: object): boolean {
    if (!('actions' in value)) return false;
    if (!('appliedAmount' in value)) return false;
    if (!('appliedAt' in value)) return false;
    if (!('currency' in value)) return false;
    if (!('invoiceId' in value)) return false;
    if (!('paymentApplicationId' in value)) return false;
    if (!('paymentId' in value)) return false;
    if (!('reversed' in value)) return false;
    if (!('source' in value)) return false;
    return true;
}

export function AutomaticPaymentApplicationRowFromJSON(json: any): AutomaticPaymentApplicationRow {
    return AutomaticPaymentApplicationRowFromJSONTyped(json, false);
}

export function AutomaticPaymentApplicationRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutomaticPaymentApplicationRow {
    if (json == null) {
        return json;
    }
    return {
        
        'actions': json['actions'],
        'appliedAmount': json['appliedAmount'],
        'appliedAt': (new Date(json['appliedAt'])),
        'creditCreatedAmount': json['creditCreatedAmount'] == null ? undefined : json['creditCreatedAmount'],
        'currency': json['currency'],
        'customerDisplayName': json['customerDisplayName'] == null ? undefined : json['customerDisplayName'],
        'customerReference': json['customerReference'] == null ? undefined : json['customerReference'],
        'invoiceId': json['invoiceId'],
        'invoiceNumber': json['invoiceNumber'] == null ? undefined : json['invoiceNumber'],
        'paymentApplicationId': json['paymentApplicationId'],
        'paymentId': json['paymentId'],
        'reversed': json['reversed'],
        'reversedAt': json['reversedAt'] == null ? undefined : (new Date(json['reversedAt'])),
        'source': json['source'],
    };
}

export function AutomaticPaymentApplicationRowToJSON(value?: AutomaticPaymentApplicationRow | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'actions': value['actions'],
        'appliedAmount': value['appliedAmount'],
        'appliedAt': ((value['appliedAt']).toISOString()),
        'creditCreatedAmount': value['creditCreatedAmount'],
        'currency': value['currency'],
        'customerDisplayName': value['customerDisplayName'],
        'customerReference': value['customerReference'],
        'invoiceId': value['invoiceId'],
        'invoiceNumber': value['invoiceNumber'],
        'paymentApplicationId': value['paymentApplicationId'],
        'paymentId': value['paymentId'],
        'reversed': value['reversed'],
        'reversedAt': value['reversedAt'] == null ? undefined : ((value['reversedAt'] as any).toISOString()),
        'source': value['source'],
    };
}

