/* tslint:disable */
/* eslint-disable */
/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A single field definition in an event envelope contract
 * @export
 * @interface ContractField
 */
export interface ContractField {
    /**
     * 
     * @type {string}
     * @memberof ContractField
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractField
     */
    jsonPath?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractField
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ContractField
     */
    required?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ContractField
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ContractField
     */
    enumValues?: Array<string>;
}

/**
 * Check if a given object implements the ContractField interface.
 */
export function instanceOfContractField(value: object): boolean {
    return true;
}

export function ContractFieldFromJSON(json: any): ContractField {
    return ContractFieldFromJSONTyped(json, false);
}

export function ContractFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractField {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'jsonPath': json['jsonPath'] == null ? undefined : json['jsonPath'],
        'type': json['type'] == null ? undefined : json['type'],
        'required': json['required'] == null ? undefined : json['required'],
        'description': json['description'] == null ? undefined : json['description'],
        'enumValues': json['enumValues'] == null ? undefined : json['enumValues'],
    };
}

export function ContractFieldToJSON(value?: ContractField | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'jsonPath': value['jsonPath'],
        'type': value['type'],
        'required': value['required'],
        'description': value['description'],
        'enumValues': value['enumValues'],
    };
}

