/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CustomerCreditInfo
 */
export interface CustomerCreditInfo {
    /**
     *
     * @type {string}
     * @memberof CustomerCreditInfo
     */
    creditId?: string;
    /**
     *
     * @type {number}
     * @memberof CustomerCreditInfo
     */
    amount?: number;
    /**
     *
     * @type {Date}
     * @memberof CustomerCreditInfo
     */
    createdAt?: Date;
}
/**
 * Check if a given object implements the CustomerCreditInfo interface.
 */
export declare function instanceOfCustomerCreditInfo(value: object): boolean;
export declare function CustomerCreditInfoFromJSON(json: any): CustomerCreditInfo;
export declare function CustomerCreditInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerCreditInfo;
export declare function CustomerCreditInfoToJSON(value?: CustomerCreditInfo | null): any;
