/* tslint:disable */
/* eslint-disable */
/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Refund an open customer credit as cash back to the customer
 * @export
 * @interface CustomerCreditRefundRequest
 */
export interface CustomerCreditRefundRequest {
    /**
     * Amount to refund. Must not exceed the credit's open amount
     * @type {number}
     * @memberof CustomerCreditRefundRequest
     */
    amount: number;
    /**
     * Optional audit note explaining why the credit is being refunded
     * @type {string}
     * @memberof CustomerCreditRefundRequest
     */
    note?: string;
    /**
     * Caller-supplied idempotency key. Replaying the same key returns the original refund instead of relieving the credit liability twice
     * @type {string}
     * @memberof CustomerCreditRefundRequest
     */
    requestId: string;
}

/**
 * Check if a given object implements the CustomerCreditRefundRequest interface.
 */
export function instanceOfCustomerCreditRefundRequest(value: object): boolean {
    if (!('amount' in value)) return false;
    if (!('requestId' in value)) return false;
    return true;
}

export function CustomerCreditRefundRequestFromJSON(json: any): CustomerCreditRefundRequest {
    return CustomerCreditRefundRequestFromJSONTyped(json, false);
}

export function CustomerCreditRefundRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerCreditRefundRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'note': json['note'] == null ? undefined : json['note'],
        'requestId': json['requestId'],
    };
}

export function CustomerCreditRefundRequestToJSON(value?: CustomerCreditRefundRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'note': value['note'],
        'requestId': value['requestId'],
    };
}

