/* tslint:disable */
/* eslint-disable */
/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A single customer-credit draw-down and the credit state it left behind
 * @export
 * @interface CustomerCreditTransactionResponse
 */
export interface CustomerCreditTransactionResponse {
    /**
     * Amount drawn down
     * @type {number}
     * @memberof CustomerCreditTransactionResponse
     */
    amount?: number;
    /**
     * When the draw-down was recorded
     * @type {Date}
     * @memberof CustomerCreditTransactionResponse
     */
    createdAt?: Date;
    /**
     * Credit that was drawn down
     * @type {string}
     * @memberof CustomerCreditTransactionResponse
     */
    creditId?: string;
    /**
     * Credit's remaining open amount after this draw-down
     * @type {number}
     * @memberof CustomerCreditTransactionResponse
     */
    creditOpenAmountAfter?: number;
    /**
     * Draw-down identifier
     * @type {string}
     * @memberof CustomerCreditTransactionResponse
     */
    creditTransactionId?: string;
    /**
     * Currency (ISO 4217)
     * @type {string}
     * @memberof CustomerCreditTransactionResponse
     */
    currency?: string;
    /**
     * Invoice balance after the credit was applied; null for a REFUND
     * @type {number}
     * @memberof CustomerCreditTransactionResponse
     */
    invoiceBalanceAfter?: number;
    /**
     * Invoice settled by an APPLICATION; null for a REFUND
     * @type {string}
     * @memberof CustomerCreditTransactionResponse
     */
    invoiceId?: string;
    /**
     * True when this response replays an already-processed request id rather than recording a new draw-down
     * @type {boolean}
     * @memberof CustomerCreditTransactionResponse
     */
    replayed?: boolean;
    /**
     * Caller-supplied idempotency key this draw-down was recorded under
     * @type {string}
     * @memberof CustomerCreditTransactionResponse
     */
    requestId?: string;
    /**
     * Whether the credit settled an invoice or was refunded as cash
     * @type {string}
     * @memberof CustomerCreditTransactionResponse
     */
    transactionType?: CustomerCreditTransactionResponseTransactionTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum CustomerCreditTransactionResponseTransactionTypeEnum {
    Application = 'APPLICATION',
    Refund = 'REFUND'
}


/**
 * Check if a given object implements the CustomerCreditTransactionResponse interface.
 */
export function instanceOfCustomerCreditTransactionResponse(value: object): boolean {
    return true;
}

export function CustomerCreditTransactionResponseFromJSON(json: any): CustomerCreditTransactionResponse {
    return CustomerCreditTransactionResponseFromJSONTyped(json, false);
}

export function CustomerCreditTransactionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerCreditTransactionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'creditId': json['creditId'] == null ? undefined : json['creditId'],
        'creditOpenAmountAfter': json['creditOpenAmountAfter'] == null ? undefined : json['creditOpenAmountAfter'],
        'creditTransactionId': json['creditTransactionId'] == null ? undefined : json['creditTransactionId'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'invoiceBalanceAfter': json['invoiceBalanceAfter'] == null ? undefined : json['invoiceBalanceAfter'],
        'invoiceId': json['invoiceId'] == null ? undefined : json['invoiceId'],
        'replayed': json['replayed'] == null ? undefined : json['replayed'],
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'transactionType': json['transactionType'] == null ? undefined : json['transactionType'],
    };
}

export function CustomerCreditTransactionResponseToJSON(value?: CustomerCreditTransactionResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'creditId': value['creditId'],
        'creditOpenAmountAfter': value['creditOpenAmountAfter'],
        'creditTransactionId': value['creditTransactionId'],
        'currency': value['currency'],
        'invoiceBalanceAfter': value['invoiceBalanceAfter'],
        'invoiceId': value['invoiceId'],
        'replayed': value['replayed'],
        'requestId': value['requestId'],
        'transactionType': value['transactionType'],
    };
}

