/* tslint:disable */
/* eslint-disable */
/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Entry-number gap-check result for one monthly sequence scope; absent gaps mean a clean ledger
 * @export
 * @interface EntryNumberGapCheck
 */
export interface EntryNumberGapCheck {
    /**
     * Ascending sequence numbers handed out but missing from the ledger for this scope
     * @type {Array<number>}
     * @memberof EntryNumberGapCheck
     */
    missingNumbers: Array<number>;
    /**
     * Monthly sequence scope key
     * @type {string}
     * @memberof EntryNumberGapCheck
     */
    scopeKey: string;
}

/**
 * Check if a given object implements the EntryNumberGapCheck interface.
 */
export function instanceOfEntryNumberGapCheck(value: object): boolean {
    if (!('missingNumbers' in value)) return false;
    if (!('scopeKey' in value)) return false;
    return true;
}

export function EntryNumberGapCheckFromJSON(json: any): EntryNumberGapCheck {
    return EntryNumberGapCheckFromJSONTyped(json, false);
}

export function EntryNumberGapCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntryNumberGapCheck {
    if (json == null) {
        return json;
    }
    return {
        
        'missingNumbers': json['missingNumbers'],
        'scopeKey': json['scopeKey'],
    };
}

export function EntryNumberGapCheckToJSON(value?: EntryNumberGapCheck | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'missingNumbers': value['missingNumbers'],
        'scopeKey': value['scopeKey'],
    };
}

