/* tslint:disable */
/* eslint-disable */
/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FactConsumptionIdempotency } from './FactConsumptionIdempotency';
import {
    FactConsumptionIdempotencyFromJSON,
    FactConsumptionIdempotencyFromJSONTyped,
    FactConsumptionIdempotencyToJSON,
} from './FactConsumptionIdempotency';
import type { RestSubmissionIdempotency } from './RestSubmissionIdempotency';
import {
    RestSubmissionIdempotencyFromJSON,
    RestSubmissionIdempotencyFromJSONTyped,
    RestSubmissionIdempotencyToJSON,
} from './RestSubmissionIdempotency';

/**
 * The two idempotency mechanisms used by the accounting event ingestion pipeline
 * @export
 * @interface IdempotencyOutcomesContract
 */
export interface IdempotencyOutcomesContract {
    /**
     * 
     * @type {FactConsumptionIdempotency}
     * @memberof IdempotencyOutcomesContract
     */
    factConsumption: FactConsumptionIdempotency;
    /**
     * 
     * @type {RestSubmissionIdempotency}
     * @memberof IdempotencyOutcomesContract
     */
    restSubmission: RestSubmissionIdempotency;
}

/**
 * Check if a given object implements the IdempotencyOutcomesContract interface.
 */
export function instanceOfIdempotencyOutcomesContract(value: object): boolean {
    if (!('factConsumption' in value)) return false;
    if (!('restSubmission' in value)) return false;
    return true;
}

export function IdempotencyOutcomesContractFromJSON(json: any): IdempotencyOutcomesContract {
    return IdempotencyOutcomesContractFromJSONTyped(json, false);
}

export function IdempotencyOutcomesContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdempotencyOutcomesContract {
    if (json == null) {
        return json;
    }
    return {
        
        'factConsumption': FactConsumptionIdempotencyFromJSON(json['factConsumption']),
        'restSubmission': RestSubmissionIdempotencyFromJSON(json['restSubmission']),
    };
}

export function IdempotencyOutcomesContractToJSON(value?: IdempotencyOutcomesContract | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'factConsumption': FactConsumptionIdempotencyToJSON(value['factConsumption']),
        'restSubmission': RestSubmissionIdempotencyToJSON(value['restSubmission']),
    };
}

