/* tslint:disable */
/* eslint-disable */
/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An account recovered tax posts to
 * @export
 * @interface InputTaxRecoveryAccount
 */
export interface InputTaxRecoveryAccount {
    /**
     * Account number
     * @type {string}
     * @memberof InputTaxRecoveryAccount
     */
    code: string;
    /**
     * Account name
     * @type {string}
     * @memberof InputTaxRecoveryAccount
     */
    name: string;
}

/**
 * Check if a given object implements the InputTaxRecoveryAccount interface.
 */
export function instanceOfInputTaxRecoveryAccount(value: object): boolean {
    if (!('code' in value)) return false;
    if (!('name' in value)) return false;
    return true;
}

export function InputTaxRecoveryAccountFromJSON(json: any): InputTaxRecoveryAccount {
    return InputTaxRecoveryAccountFromJSONTyped(json, false);
}

export function InputTaxRecoveryAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): InputTaxRecoveryAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'],
    };
}

export function InputTaxRecoveryAccountToJSON(value?: InputTaxRecoveryAccount | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'name': value['name'],
    };
}

