"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfInvoiceApplication = instanceOfInvoiceApplication;
exports.InvoiceApplicationFromJSON = InvoiceApplicationFromJSON;
exports.InvoiceApplicationFromJSONTyped = InvoiceApplicationFromJSONTyped;
exports.InvoiceApplicationToJSON = InvoiceApplicationToJSON;
/**
 * Check if a given object implements the InvoiceApplication interface.
 */
function instanceOfInvoiceApplication(value) {
    if (!('invoiceId' in value))
        return false;
    if (!('amountToApply' in value))
        return false;
    return true;
}
function InvoiceApplicationFromJSON(json) {
    return InvoiceApplicationFromJSONTyped(json, false);
}
function InvoiceApplicationFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'invoiceId': json['invoiceId'],
        'amountToApply': json['amountToApply'],
    };
}
function InvoiceApplicationToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'invoiceId': value['invoiceId'],
        'amountToApply': value['amountToApply'],
    };
}
