/* tslint:disable */
/* eslint-disable */
/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Single invoice application within a payment application request
 * @export
 * @interface InvoiceApplication
 */
export interface InvoiceApplication {
    /**
     * Amount of the payment to apply to this invoice
     * @type {number}
     * @memberof InvoiceApplication
     */
    amountToApply: number;
    /**
     * Identifier of the invoice the payment is applied to
     * @type {string}
     * @memberof InvoiceApplication
     */
    invoiceId: string;
}

/**
 * Check if a given object implements the InvoiceApplication interface.
 */
export function instanceOfInvoiceApplication(value: object): boolean {
    if (!('amountToApply' in value)) return false;
    if (!('invoiceId' in value)) return false;
    return true;
}

export function InvoiceApplicationFromJSON(json: any): InvoiceApplication {
    return InvoiceApplicationFromJSONTyped(json, false);
}

export function InvoiceApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceApplication {
    if (json == null) {
        return json;
    }
    return {
        
        'amountToApply': json['amountToApply'],
        'invoiceId': json['invoiceId'],
    };
}

export function InvoiceApplicationToJSON(value?: InvoiceApplication | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amountToApply': value['amountToApply'],
        'invoiceId': value['invoiceId'],
    };
}

