/* tslint:disable */
/* eslint-disable */
/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceApplication } from './InvoiceApplication';
import {
    InvoiceApplicationFromJSON,
    InvoiceApplicationFromJSONTyped,
    InvoiceApplicationToJSON,
} from './InvoiceApplication';

/**
 * 
 * @export
 * @interface PaymentApplicationRequest
 */
export interface PaymentApplicationRequest {
    /**
     * 
     * @type {string}
     * @memberof PaymentApplicationRequest
     */
    applicationRequestId: string;
    /**
     * 
     * @type {Array<InvoiceApplication>}
     * @memberof PaymentApplicationRequest
     */
    applications: Array<InvoiceApplication>;
}

/**
 * Check if a given object implements the PaymentApplicationRequest interface.
 */
export function instanceOfPaymentApplicationRequest(value: object): boolean {
    if (!('applicationRequestId' in value)) return false;
    if (!('applications' in value)) return false;
    return true;
}

export function PaymentApplicationRequestFromJSON(json: any): PaymentApplicationRequest {
    return PaymentApplicationRequestFromJSONTyped(json, false);
}

export function PaymentApplicationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentApplicationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'applicationRequestId': json['applicationRequestId'],
        'applications': ((json['applications'] as Array<any>).map(InvoiceApplicationFromJSON)),
    };
}

export function PaymentApplicationRequestToJSON(value?: PaymentApplicationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'applicationRequestId': value['applicationRequestId'],
        'applications': ((value['applications'] as Array<any>).map(InvoiceApplicationToJSON)),
    };
}

