/* tslint:disable */
/* eslint-disable */
/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Line item received from vendor
 * @export
 * @interface ReceivedLineItem
 */
export interface ReceivedLineItem {
    /**
     * Product/SKU UUID
     * @type {string}
     * @memberof ReceivedLineItem
     */
    productId: string;
    /**
     * Product description
     * @type {string}
     * @memberof ReceivedLineItem
     */
    description: string;
    /**
     * Quantity received
     * @type {number}
     * @memberof ReceivedLineItem
     */
    quantity: number;
    /**
     * Unit price from PO
     * @type {number}
     * @memberof ReceivedLineItem
     */
    unitPrice: number;
    /**
     * Is this an inventory item (true) or expense item (false)
     * @type {boolean}
     * @memberof ReceivedLineItem
     */
    isInventoryItem?: boolean;
}

/**
 * Check if a given object implements the ReceivedLineItem interface.
 */
export function instanceOfReceivedLineItem(value: object): boolean {
    if (!('productId' in value)) return false;
    if (!('description' in value)) return false;
    if (!('quantity' in value)) return false;
    if (!('unitPrice' in value)) return false;
    return true;
}

export function ReceivedLineItemFromJSON(json: any): ReceivedLineItem {
    return ReceivedLineItemFromJSONTyped(json, false);
}

export function ReceivedLineItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceivedLineItem {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'],
        'description': json['description'],
        'quantity': json['quantity'],
        'unitPrice': json['unitPrice'],
        'isInventoryItem': json['isInventoryItem'] == null ? undefined : json['isInventoryItem'],
    };
}

export function ReceivedLineItemToJSON(value?: ReceivedLineItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'productId': value['productId'],
        'description': value['description'],
        'quantity': value['quantity'],
        'unitPrice': value['unitPrice'],
        'isInventoryItem': value['isInventoryItem'],
    };
}

