/* tslint:disable */
/* eslint-disable */
/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefundRequest
 */
export interface RefundRequest {
    /**
     * 
     * @type {string}
     * @memberof RefundRequest
     */
    invoiceId: string;
    /**
     * 
     * @type {string}
     * @memberof RefundRequest
     */
    paymentId: string;
    /**
     * 
     * @type {string}
     * @memberof RefundRequest
     */
    refundType: RefundRequestRefundTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof RefundRequest
     */
    refundAmount: number;
    /**
     * 
     * @type {string}
     * @memberof RefundRequest
     */
    originalPaymentStatus: RefundRequestOriginalPaymentStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof RefundRequest
     */
    actorId?: string;
    /**
     * 
     * @type {string}
     * @memberof RefundRequest
     */
    actorRole: string;
    /**
     * 
     * @type {string}
     * @memberof RefundRequest
     */
    reason: string;
}

/**
* @export
* @enum {string}
*/
export enum RefundRequestRefundTypeEnum {
    Reversal = 'REVERSAL',
    CreditMemo = 'CREDIT_MEMO',
    Adjustment = 'ADJUSTMENT'
}
/**
* @export
* @enum {string}
*/
export enum RefundRequestOriginalPaymentStatusEnum {
    Pending = 'PENDING',
    Settled = 'SETTLED',
    Failed = 'FAILED',
    Authorized = 'AUTHORIZED'
}


/**
 * Check if a given object implements the RefundRequest interface.
 */
export function instanceOfRefundRequest(value: object): boolean {
    if (!('invoiceId' in value)) return false;
    if (!('paymentId' in value)) return false;
    if (!('refundType' in value)) return false;
    if (!('refundAmount' in value)) return false;
    if (!('originalPaymentStatus' in value)) return false;
    if (!('actorRole' in value)) return false;
    if (!('reason' in value)) return false;
    return true;
}

export function RefundRequestFromJSON(json: any): RefundRequest {
    return RefundRequestFromJSONTyped(json, false);
}

export function RefundRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'invoiceId': json['invoiceId'],
        'paymentId': json['paymentId'],
        'refundType': json['refundType'],
        'refundAmount': json['refundAmount'],
        'originalPaymentStatus': json['originalPaymentStatus'],
        'actorId': json['actorId'] == null ? undefined : json['actorId'],
        'actorRole': json['actorRole'],
        'reason': json['reason'],
    };
}

export function RefundRequestToJSON(value?: RefundRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'invoiceId': value['invoiceId'],
        'paymentId': value['paymentId'],
        'refundType': value['refundType'],
        'refundAmount': value['refundAmount'],
        'originalPaymentStatus': value['originalPaymentStatus'],
        'actorId': value['actorId'],
        'actorRole': value['actorRole'],
        'reason': value['reason'],
    };
}

