/* tslint:disable */
/* eslint-disable */
/**
 * POS Bulk Loader Service API
 * Bulk loader service for importing and processing POS data in bulk.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuditRecordResponse,
} from '../models/index';
import {
    AuditRecordResponseFromJSON,
    AuditRecordResponseToJSON,
} from '../models/index';

export interface DownloadErrorReportRequest {
    jobId: string;
}

export interface GetAuditRecordsRequest {
    jobId: string;
}

/**
 * 
 */
export class ReviewQueueAPIApi extends runtime.BaseAPI {

    /**
     * Generates and downloads a CSV file containing all error records for the specified bulk load job.
     * Download error report as CSV for a bulk load job
     */
    async downloadErrorReportRaw(requestParameters: DownloadErrorReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling downloadErrorReport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["bulkImport:upload:execute", "bulkImport:status:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/bulk-jobs/{jobId}/error-report`.replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Generates and downloads a CSV file containing all error records for the specified bulk load job.
     * Download error report as CSV for a bulk load job
     */
    async downloadErrorReport(requestParameters: DownloadErrorReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadErrorReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of audit records for the specified bulk load job, including review status and details for each record.
     * Get audit records for a bulk load job
     */
    async getAuditRecordsRaw(requestParameters: GetAuditRecordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AuditRecordResponse>>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getAuditRecords().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["bulkImport:upload:execute", "bulkImport:status:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/bulk-jobs/{jobId}/audit`.replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AuditRecordResponseFromJSON));
    }

    /**
     * Returns a list of audit records for the specified bulk load job, including review status and details for each record.
     * Get audit records for a bulk load job
     */
    async getAuditRecords(requestParameters: GetAuditRecordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AuditRecordResponse>> {
        const response = await this.getAuditRecordsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
