/**
 * Vehicle Inventory API
 * API for managing vehicle inventory in the POS system
 *
 * The version of the OpenAPI document: 1.0
 * Contact: platform@durion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface VehicleCarePreferenceResponse
 */
export interface VehicleCarePreferenceResponse {
    /**
     *
     * @type {string}
     * @memberof VehicleCarePreferenceResponse
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof VehicleCarePreferenceResponse
     */
    vehicleId?: string;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof VehicleCarePreferenceResponse
     */
    preferences?: {
        [key: string]: any;
    };
    /**
     *
     * @type {string}
     * @memberof VehicleCarePreferenceResponse
     */
    serviceNotes?: string;
    /**
     *
     * @type {string}
     * @memberof VehicleCarePreferenceResponse
     */
    createdByUserId?: string;
    /**
     *
     * @type {string}
     * @memberof VehicleCarePreferenceResponse
     */
    updatedByUserId?: string;
    /**
     *
     * @type {Date}
     * @memberof VehicleCarePreferenceResponse
     */
    createdAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof VehicleCarePreferenceResponse
     */
    updatedAt?: Date;
    /**
     *
     * @type {number}
     * @memberof VehicleCarePreferenceResponse
     */
    version?: number;
}
/**
 * Check if a given object implements the VehicleCarePreferenceResponse interface.
 */
export declare function instanceOfVehicleCarePreferenceResponse(value: object): boolean;
export declare function VehicleCarePreferenceResponseFromJSON(json: any): VehicleCarePreferenceResponse;
export declare function VehicleCarePreferenceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleCarePreferenceResponse;
export declare function VehicleCarePreferenceResponseToJSON(value?: VehicleCarePreferenceResponse | null): any;
