/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ToolPermissionRequest,
  ToolPermissionsResponse,
} from '../models/index';
import {
    ToolPermissionRequestFromJSON,
    ToolPermissionRequestToJSON,
    ToolPermissionsResponseFromJSON,
    ToolPermissionsResponseToJSON,
} from '../models/index';

export interface GrantToolPermissionRequest {
    toolName: string;
    toolPermissionRequest: ToolPermissionRequest;
}

export interface ListToolPermissionsRequest {
    toolName: string;
}

export interface RevokeToolPermissionRequest {
    toolName: string;
    permissionCode: string;
}

/**
 * 
 */
export class MCPToolPermissionsApi extends runtime.BaseAPI {

    /**
     * Grants a permission code to a discovered OpenAPI tool so callers holding that code can select the tool during chat. Use this tool to open up a fail-closed discovered operation; do not use revokeToolPermission, which removes a grant. Preconditions: the named tool must exist as a discovered (source openapi) tool; granting a code that is already present changes nothing. Required inputs: toolName as a path parameter and permissionCode in the body, either the literal AUTHENTICATED or a domain:resource:action code such as event-receiver:event_type:view. Emits a MCP_TOOL_PERMISSION_GRANT event; when the grant set actually changes, cached role agents are invalidated so the tool becomes selectable on the next chat turn. Returns 201 with the tool\'s full permission set (idempotently for repeated grants), 404 when no discovered OpenAPI tool has the given name, and 400 when the permission code does not match the required pattern. 
     * Grant a Permission to a Tool
     */
    async grantToolPermissionRaw(requestParameters: GrantToolPermissionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ToolPermissionsResponse>> {
        if (requestParameters['toolName'] == null) {
            throw new runtime.RequiredError(
                'toolName',
                'Required parameter "toolName" was null or undefined when calling grantToolPermission().'
            );
        }

        if (requestParameters['toolPermissionRequest'] == null) {
            throw new runtime.RequiredError(
                'toolPermissionRequest',
                'Required parameter "toolPermissionRequest" was null or undefined when calling grantToolPermission().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/tools/{toolName}/permissions`.replace(`{${"toolName"}}`, encodeURIComponent(String(requestParameters['toolName']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ToolPermissionRequestToJSON(requestParameters['toolPermissionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ToolPermissionsResponseFromJSON(jsonValue));
    }

    /**
     * Grants a permission code to a discovered OpenAPI tool so callers holding that code can select the tool during chat. Use this tool to open up a fail-closed discovered operation; do not use revokeToolPermission, which removes a grant. Preconditions: the named tool must exist as a discovered (source openapi) tool; granting a code that is already present changes nothing. Required inputs: toolName as a path parameter and permissionCode in the body, either the literal AUTHENTICATED or a domain:resource:action code such as event-receiver:event_type:view. Emits a MCP_TOOL_PERMISSION_GRANT event; when the grant set actually changes, cached role agents are invalidated so the tool becomes selectable on the next chat turn. Returns 201 with the tool\'s full permission set (idempotently for repeated grants), 404 when no discovered OpenAPI tool has the given name, and 400 when the permission code does not match the required pattern. 
     * Grant a Permission to a Tool
     */
    async grantToolPermission(requestParameters: GrantToolPermissionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ToolPermissionsResponse> {
        const response = await this.grantToolPermissionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the permission codes currently granted to a discovered OpenAPI tool. Use this tool to inspect why a discovered tool is or is not selectable for a caller; use grantToolPermission or revokeToolPermission instead to change the grants. Preconditions: the named tool must exist as a discovered (source openapi) tool; discovered tools are fail-closed and unselectable until at least one grant exists. Required inputs: toolName as a path parameter, matching the tool\'s registered name exactly. No events are emitted and no state changes; this is a read-only projection. Returns 200 with the grant set (possibly empty), and 404 when no discovered OpenAPI tool has the given name. 
     * List a Tool\'s Permission Grants
     */
    async listToolPermissionsRaw(requestParameters: ListToolPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ToolPermissionsResponse>> {
        if (requestParameters['toolName'] == null) {
            throw new runtime.RequiredError(
                'toolName',
                'Required parameter "toolName" was null or undefined when calling listToolPermissions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/tools/{toolName}/permissions`.replace(`{${"toolName"}}`, encodeURIComponent(String(requestParameters['toolName']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ToolPermissionsResponseFromJSON(jsonValue));
    }

    /**
     * Returns the permission codes currently granted to a discovered OpenAPI tool. Use this tool to inspect why a discovered tool is or is not selectable for a caller; use grantToolPermission or revokeToolPermission instead to change the grants. Preconditions: the named tool must exist as a discovered (source openapi) tool; discovered tools are fail-closed and unselectable until at least one grant exists. Required inputs: toolName as a path parameter, matching the tool\'s registered name exactly. No events are emitted and no state changes; this is a read-only projection. Returns 200 with the grant set (possibly empty), and 404 when no discovered OpenAPI tool has the given name. 
     * List a Tool\'s Permission Grants
     */
    async listToolPermissions(requestParameters: ListToolPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ToolPermissionsResponse> {
        const response = await this.listToolPermissionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revokes a permission code from a discovered OpenAPI tool, removing it from the set that makes the tool selectable. Use this tool to withdraw chat access to a discovered operation; do not use grantToolPermission, which adds a grant. Preconditions: the named tool must exist as a discovered (source openapi) tool; revoking a code that is not granted changes nothing. Required inputs: toolName as a path parameter and permissionCode as a query parameter; there is no request body. Emits a MCP_TOOL_PERMISSION_REVOKE event; when the grant set actually changes, cached role agents are invalidated so the tool stops being selectable. Returns 204 whether or not the code was granted (idempotent), 404 when no discovered OpenAPI tool has the given name, and 400 when the permission code is blank. 
     * Revoke a Permission From a Tool
     */
    async revokeToolPermissionRaw(requestParameters: RevokeToolPermissionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['toolName'] == null) {
            throw new runtime.RequiredError(
                'toolName',
                'Required parameter "toolName" was null or undefined when calling revokeToolPermission().'
            );
        }

        if (requestParameters['permissionCode'] == null) {
            throw new runtime.RequiredError(
                'permissionCode',
                'Required parameter "permissionCode" was null or undefined when calling revokeToolPermission().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['permissionCode'] != null) {
            queryParameters['permissionCode'] = requestParameters['permissionCode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/tools/{toolName}/permissions`.replace(`{${"toolName"}}`, encodeURIComponent(String(requestParameters['toolName']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revokes a permission code from a discovered OpenAPI tool, removing it from the set that makes the tool selectable. Use this tool to withdraw chat access to a discovered operation; do not use grantToolPermission, which adds a grant. Preconditions: the named tool must exist as a discovered (source openapi) tool; revoking a code that is not granted changes nothing. Required inputs: toolName as a path parameter and permissionCode as a query parameter; there is no request body. Emits a MCP_TOOL_PERMISSION_REVOKE event; when the grant set actually changes, cached role agents are invalidated so the tool stops being selectable. Returns 204 whether or not the code was granted (idempotent), 404 when no discovered OpenAPI tool has the given name, and 400 when the permission code is blank. 
     * Revoke a Permission From a Tool
     */
    async revokeToolPermission(requestParameters: RevokeToolPermissionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.revokeToolPermissionRaw(requestParameters, initOverrides);
    }

}
