/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional confirmation payload
 * @export
 * @interface ConfirmWritePlanRequest
 */
export interface ConfirmWritePlanRequest {
    /**
     * Idempotency key from the plan preview; when present it must match the plan
     * @type {string}
     * @memberof ConfirmWritePlanRequest
     */
    idempotencyKey?: string;
}

/**
 * Check if a given object implements the ConfirmWritePlanRequest interface.
 */
export function instanceOfConfirmWritePlanRequest(value: object): boolean {
    return true;
}

export function ConfirmWritePlanRequestFromJSON(json: any): ConfirmWritePlanRequest {
    return ConfirmWritePlanRequestFromJSONTyped(json, false);
}

export function ConfirmWritePlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmWritePlanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'idempotencyKey': json['idempotencyKey'] == null ? undefined : json['idempotencyKey'],
    };
}

export function ConfirmWritePlanRequestToJSON(value?: ConfirmWritePlanRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idempotencyKey': value['idempotencyKey'],
    };
}

