/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Asynchronous document ingestion job status
 * @export
 * @interface DocumentIngestionJobResponse
 */
export interface DocumentIngestionJobResponse {
    /**
     * Number of chunks produced from the document
     * @type {number}
     * @memberof DocumentIngestionJobResponse
     */
    chunkCount?: number;
    /**
     * Timestamp when ingestion processing completed (ISO 8601)
     * @type {Date}
     * @memberof DocumentIngestionJobResponse
     */
    completedAt?: Date;
    /**
     * Timestamp when the job was created (ISO 8601)
     * @type {Date}
     * @memberof DocumentIngestionJobResponse
     */
    createdAt: Date;
    /**
     * Identifier of the document being ingested
     * @type {string}
     * @memberof DocumentIngestionJobResponse
     */
    documentId: string;
    /**
     * Error message describing why ingestion failed, when applicable
     * @type {string}
     * @memberof DocumentIngestionJobResponse
     */
    errorMessage?: string;
    /**
     * Unique identifier of the ingestion job
     * @type {string}
     * @memberof DocumentIngestionJobResponse
     */
    jobId: string;
    /**
     * Timestamp when ingestion processing started (ISO 8601)
     * @type {Date}
     * @memberof DocumentIngestionJobResponse
     */
    startedAt?: Date;
    /**
     * Current status of the ingestion job
     * @type {string}
     * @memberof DocumentIngestionJobResponse
     */
    status: DocumentIngestionJobResponseStatusEnum;
    /**
     * Timestamp when the job was last updated (ISO 8601)
     * @type {Date}
     * @memberof DocumentIngestionJobResponse
     */
    updatedAt: Date;
}

/**
* @export
* @enum {string}
*/
export enum DocumentIngestionJobResponseStatusEnum {
    Pending = 'PENDING',
    Running = 'RUNNING',
    Succeeded = 'SUCCEEDED',
    Failed = 'FAILED'
}


/**
 * Check if a given object implements the DocumentIngestionJobResponse interface.
 */
export function instanceOfDocumentIngestionJobResponse(value: object): boolean {
    if (!('createdAt' in value)) return false;
    if (!('documentId' in value)) return false;
    if (!('jobId' in value)) return false;
    if (!('status' in value)) return false;
    if (!('updatedAt' in value)) return false;
    return true;
}

export function DocumentIngestionJobResponseFromJSON(json: any): DocumentIngestionJobResponse {
    return DocumentIngestionJobResponseFromJSONTyped(json, false);
}

export function DocumentIngestionJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentIngestionJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'chunkCount': json['chunkCount'] == null ? undefined : json['chunkCount'],
        'completedAt': json['completedAt'] == null ? undefined : (new Date(json['completedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'documentId': json['documentId'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'jobId': json['jobId'],
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'status': json['status'],
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function DocumentIngestionJobResponseToJSON(value?: DocumentIngestionJobResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chunkCount': value['chunkCount'],
        'completedAt': value['completedAt'] == null ? undefined : ((value['completedAt']).toISOString()),
        'createdAt': ((value['createdAt']).toISOString()),
        'documentId': value['documentId'],
        'errorMessage': value['errorMessage'],
        'jobId': value['jobId'],
        'startedAt': value['startedAt'] == null ? undefined : ((value['startedAt']).toISOString()),
        'status': value['status'],
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

