/**
 * POS Workorder Service API
 * Workorder service for managing workorders and tasks
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { LineItemApprovalDto } from './LineItemApprovalDto';
/**
 * Request to approve a work order with customer signature
 * @export
 * @interface ApproveWorkorderRequest
 */
export interface ApproveWorkorderRequest {
    /**
     * Customer ID who is approving the work order
     * @type {string}
     * @memberof ApproveWorkorderRequest
     */
    customerId: string;
    /**
     * Base64-encoded signature image data (PNG format recommended)
     * @type {string}
     * @memberof ApproveWorkorderRequest
     */
    signatureData?: string;
    /**
     * MIME type of signature (e.g., image/png, image/jpeg)
     * @type {string}
     * @memberof ApproveWorkorderRequest
     */
    signatureMimeType?: string;
    /**
     * Name of person providing signature
     * @type {string}
     * @memberof ApproveWorkorderRequest
     */
    signerName?: string;
    /**
     * Additional notes or comments
     * @type {string}
     * @memberof ApproveWorkorderRequest
     */
    notes?: string;
    /**
     * Individual line item approvals/rejections. If omitted, all items are considered approved.
     * @type {Array<LineItemApprovalDto>}
     * @memberof ApproveWorkorderRequest
     */
    lineItemApprovals?: Array<LineItemApprovalDto>;
}
/**
 * Check if a given object implements the ApproveWorkorderRequest interface.
 */
export declare function instanceOfApproveWorkorderRequest(value: object): boolean;
export declare function ApproveWorkorderRequestFromJSON(json: any): ApproveWorkorderRequest;
export declare function ApproveWorkorderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApproveWorkorderRequest;
export declare function ApproveWorkorderRequestToJSON(value?: ApproveWorkorderRequest | null): any;
