"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * POS Workorder Service API
 * Workorder service for managing workorders and tasks
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRejectTimeEntryRequest = instanceOfRejectTimeEntryRequest;
exports.RejectTimeEntryRequestFromJSON = RejectTimeEntryRequestFromJSON;
exports.RejectTimeEntryRequestFromJSONTyped = RejectTimeEntryRequestFromJSONTyped;
exports.RejectTimeEntryRequestToJSON = RejectTimeEntryRequestToJSON;
/**
 * Check if a given object implements the RejectTimeEntryRequest interface.
 */
function instanceOfRejectTimeEntryRequest(value) {
    if (!('rejectionReason' in value))
        return false;
    return true;
}
function RejectTimeEntryRequestFromJSON(json) {
    return RejectTimeEntryRequestFromJSONTyped(json, false);
}
function RejectTimeEntryRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'rejectionReason': json['rejectionReason'],
    };
}
function RejectTimeEntryRequestToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'rejectionReason': value['rejectionReason'],
    };
}
