/**
 * POS Workorder Service API
 * Workorder service for managing workorders and tasks
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Response payload for workorder part usage events
 * @export
 * @interface WorkorderPartUsageEventResponse
 */
export interface WorkorderPartUsageEventResponse {
    /**
     * Usage event identifier
     * @type {string}
     * @memberof WorkorderPartUsageEventResponse
     */
    id?: string;
    /**
     * Workorder part identifier
     * @type {string}
     * @memberof WorkorderPartUsageEventResponse
     */
    workorderPartId?: string;
    /**
     * Workorder identifier
     * @type {string}
     * @memberof WorkorderPartUsageEventResponse
     */
    workorderId?: string;
    /**
     * Event type
     * @type {string}
     * @memberof WorkorderPartUsageEventResponse
     */
    eventType?: string;
    /**
     * Quantity associated with event
     * @type {number}
     * @memberof WorkorderPartUsageEventResponse
     */
    quantity?: number;
    /**
     * Actor identifier who performed event
     * @type {string}
     * @memberof WorkorderPartUsageEventResponse
     */
    performedBy?: string;
    /**
     * Event timestamp
     * @type {Date}
     * @memberof WorkorderPartUsageEventResponse
     */
    performedAt?: Date;
    /**
     * Optional event notes
     * @type {string}
     * @memberof WorkorderPartUsageEventResponse
     */
    notes?: string;
    /**
     * Part description for display
     * @type {string}
     * @memberof WorkorderPartUsageEventResponse
     */
    partDescription?: string;
}
/**
 * Check if a given object implements the WorkorderPartUsageEventResponse interface.
 */
export declare function instanceOfWorkorderPartUsageEventResponse(value: object): boolean;
export declare function WorkorderPartUsageEventResponseFromJSON(json: any): WorkorderPartUsageEventResponse;
export declare function WorkorderPartUsageEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkorderPartUsageEventResponse;
export declare function WorkorderPartUsageEventResponseToJSON(value?: WorkorderPartUsageEventResponse | null): any;
