/* tslint:disable */
/* eslint-disable */
/**
 * POS Workorder Service API
 * Workorder service for managing workorders and tasks
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Labor entry response
 * @export
 * @interface WorkorderLaborEntryResponse
 */
export interface WorkorderLaborEntryResponse {
    /**
     * Whether this session is still active (not stopped)
     * @type {boolean}
     * @memberof WorkorderLaborEntryResponse
     */
    active: boolean;
    /**
     * Adjustment reason (if hours were manually adjusted)
     * @type {string}
     * @memberof WorkorderLaborEntryResponse
     */
    adjustmentReason?: string;
    /**
     * Creation timestamp
     * @type {Date}
     * @memberof WorkorderLaborEntryResponse
     */
    createdAt?: Date;
    /**
     * User who created this entry
     * @type {string}
     * @memberof WorkorderLaborEntryResponse
     */
    createdBy?: string;
    /**
     * Labor session end time (null if still active)
     * @type {Date}
     * @memberof WorkorderLaborEntryResponse
     */
    endTime?: Date;
    /**
     * Hours worked
     * @type {number}
     * @memberof WorkorderLaborEntryResponse
     */
    hoursWorked?: number;
    /**
     * Unique ID of the labor entry
     * @type {string}
     * @memberof WorkorderLaborEntryResponse
     */
    id: string;
    /**
     * Session notes
     * @type {string}
     * @memberof WorkorderLaborEntryResponse
     */
    notes?: string;
    /**
     * Labor session start time
     * @type {Date}
     * @memberof WorkorderLaborEntryResponse
     */
    startTime?: Date;
    /**
     * Technician ID who performed the work
     * @type {string}
     * @memberof WorkorderLaborEntryResponse
     */
    technicianId?: string;
    /**
     * Workorder ID
     * @type {string}
     * @memberof WorkorderLaborEntryResponse
     */
    workorderId: string;
    /**
     * Service line item ID
     * @type {string}
     * @memberof WorkorderLaborEntryResponse
     */
    workorderServiceId?: string;
}

/**
 * Check if a given object implements the WorkorderLaborEntryResponse interface.
 */
export function instanceOfWorkorderLaborEntryResponse(value: object): boolean {
    if (!('active' in value)) return false;
    if (!('id' in value)) return false;
    if (!('workorderId' in value)) return false;
    return true;
}

export function WorkorderLaborEntryResponseFromJSON(json: any): WorkorderLaborEntryResponse {
    return WorkorderLaborEntryResponseFromJSONTyped(json, false);
}

export function WorkorderLaborEntryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkorderLaborEntryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'],
        'adjustmentReason': json['adjustmentReason'] == null ? undefined : json['adjustmentReason'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'endTime': json['endTime'] == null ? undefined : (new Date(json['endTime'])),
        'hoursWorked': json['hoursWorked'] == null ? undefined : json['hoursWorked'],
        'id': json['id'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'startTime': json['startTime'] == null ? undefined : (new Date(json['startTime'])),
        'technicianId': json['technicianId'] == null ? undefined : json['technicianId'],
        'workorderId': json['workorderId'],
        'workorderServiceId': json['workorderServiceId'] == null ? undefined : json['workorderServiceId'],
    };
}

export function WorkorderLaborEntryResponseToJSON(value?: WorkorderLaborEntryResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'active': value['active'],
        'adjustmentReason': value['adjustmentReason'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'createdBy': value['createdBy'],
        'endTime': value['endTime'] == null ? undefined : ((value['endTime']).toISOString()),
        'hoursWorked': value['hoursWorked'],
        'id': value['id'],
        'notes': value['notes'],
        'startTime': value['startTime'] == null ? undefined : ((value['startTime']).toISOString()),
        'technicianId': value['technicianId'],
        'workorderId': value['workorderId'],
        'workorderServiceId': value['workorderServiceId'],
    };
}

