/* tslint:disable */
/* eslint-disable */
/**
 * POS Workorder Service API
 * Workorder service for managing workorders and tasks
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkorderSummary
 */
export interface WorkorderSummary {
    /**
     * 
     * @type {string}
     * @memberof WorkorderSummary
     */
    workorderId?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkorderSummary
     */
    workorderNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkorderSummary
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkorderSummary
     */
    customerName?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkorderSummary
     */
    vehicleDescription?: string;
    /**
     * 
     * @type {Date}
     * @memberof WorkorderSummary
     */
    scheduledDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof WorkorderSummary
     */
    assignedMechanicId?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkorderSummary
     */
    assignedBayId?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkorderSummary
     */
    estimatedLaborHours?: number;
}

/**
 * Check if a given object implements the WorkorderSummary interface.
 */
export function instanceOfWorkorderSummary(value: object): boolean {
    return true;
}

export function WorkorderSummaryFromJSON(json: any): WorkorderSummary {
    return WorkorderSummaryFromJSONTyped(json, false);
}

export function WorkorderSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkorderSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'workorderId': json['workorderId'] == null ? undefined : json['workorderId'],
        'workorderNumber': json['workorderNumber'] == null ? undefined : json['workorderNumber'],
        'status': json['status'] == null ? undefined : json['status'],
        'customerName': json['customerName'] == null ? undefined : json['customerName'],
        'vehicleDescription': json['vehicleDescription'] == null ? undefined : json['vehicleDescription'],
        'scheduledDate': json['scheduledDate'] == null ? undefined : (new Date(json['scheduledDate'])),
        'assignedMechanicId': json['assignedMechanicId'] == null ? undefined : json['assignedMechanicId'],
        'assignedBayId': json['assignedBayId'] == null ? undefined : json['assignedBayId'],
        'estimatedLaborHours': json['estimatedLaborHours'] == null ? undefined : json['estimatedLaborHours'],
    };
}

export function WorkorderSummaryToJSON(value?: WorkorderSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'workorderId': value['workorderId'],
        'workorderNumber': value['workorderNumber'],
        'status': value['status'],
        'customerName': value['customerName'],
        'vehicleDescription': value['vehicleDescription'],
        'scheduledDate': value['scheduledDate'] == null ? undefined : ((value['scheduledDate']).toISOString().substring(0,10)),
        'assignedMechanicId': value['assignedMechanicId'],
        'assignedBayId': value['assignedBayId'],
        'estimatedLaborHours': value['estimatedLaborHours'],
    };
}

