/* tslint:disable */
/* eslint-disable */
/**
 * POS Workorder Service API
 * Workorder service for managing workorders and tasks
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTravelSegmentAdjustmentRequest,
  StartTravelSegmentRequest,
  StopTravelSegmentRequest,
  SubmitTravelSegmentsRequest,
  TravelSegmentAdjustmentResponse,
  TravelSegmentResponse,
} from '../models/index';
import {
    CreateTravelSegmentAdjustmentRequestFromJSON,
    CreateTravelSegmentAdjustmentRequestToJSON,
    StartTravelSegmentRequestFromJSON,
    StartTravelSegmentRequestToJSON,
    StopTravelSegmentRequestFromJSON,
    StopTravelSegmentRequestToJSON,
    SubmitTravelSegmentsRequestFromJSON,
    SubmitTravelSegmentsRequestToJSON,
    TravelSegmentAdjustmentResponseFromJSON,
    TravelSegmentAdjustmentResponseToJSON,
    TravelSegmentResponseFromJSON,
    TravelSegmentResponseToJSON,
} from '../models/index';

export interface CreateTravelSegmentAdjustmentOperationRequest {
    travelSegmentId: string;
    createTravelSegmentAdjustmentRequest: CreateTravelSegmentAdjustmentRequest;
}

export interface StartTravelSegmentOperationRequest {
    startTravelSegmentRequest: StartTravelSegmentRequest;
}

export interface StopTravelSegmentOperationRequest {
    travelSegmentId: string;
    stopTravelSegmentRequest: StopTravelSegmentRequest;
}

export interface SubmitTravelSegmentsOperationRequest {
    mobileWorkAssignmentId: string;
    submitTravelSegmentsRequest: SubmitTravelSegmentsRequest;
}

/**
 * 
 */
export class TravelSegmentAPIApi extends runtime.BaseAPI {

    /**
     * Creates an adjustment record against an APPROVED travel segment, capturing corrected start and end times and a reason while leaving the original segment untouched. Use this tool when approved travel times need correction after the fact; do not use stopTravelSegment or submitTravelSegments, which drive the normal pre-approval lifecycle. Preconditions: the segment must exist and be in APPROVED status — adjustments cannot be created for IN_PROGRESS, COMPLETED, or SUBMITTED segments. Required inputs: travelSegmentId (UUID) as a path parameter and a body with a non-blank adjustmentReason; adjustedStartAt and adjustedEndAt (ISO instants) are optional. Emits a WORKORDER_TRAVEL_SEGMENT_ADJUSTMENT event; the adjusting user is recorded from the security context. Returns 201 with the adjustment, 404 when no segment exists for the id, and 409 when the segment is not APPROVED. 
     * Create Post-Approval Travel Adjustment
     */
    async createTravelSegmentAdjustmentRaw(requestParameters: CreateTravelSegmentAdjustmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TravelSegmentAdjustmentResponse>> {
        if (requestParameters['travelSegmentId'] == null) {
            throw new runtime.RequiredError(
                'travelSegmentId',
                'Required parameter "travelSegmentId" was null or undefined when calling createTravelSegmentAdjustment().'
            );
        }

        if (requestParameters['createTravelSegmentAdjustmentRequest'] == null) {
            throw new runtime.RequiredError(
                'createTravelSegmentAdjustmentRequest',
                'Required parameter "createTravelSegmentAdjustmentRequest" was null or undefined when calling createTravelSegmentAdjustment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["workorder:labor:add"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/workorders/travelSegments/{travelSegmentId}/adjustments`.replace(`{${"travelSegmentId"}}`, encodeURIComponent(String(requestParameters['travelSegmentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTravelSegmentAdjustmentRequestToJSON(requestParameters['createTravelSegmentAdjustmentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TravelSegmentAdjustmentResponseFromJSON(jsonValue));
    }

    /**
     * Creates an adjustment record against an APPROVED travel segment, capturing corrected start and end times and a reason while leaving the original segment untouched. Use this tool when approved travel times need correction after the fact; do not use stopTravelSegment or submitTravelSegments, which drive the normal pre-approval lifecycle. Preconditions: the segment must exist and be in APPROVED status — adjustments cannot be created for IN_PROGRESS, COMPLETED, or SUBMITTED segments. Required inputs: travelSegmentId (UUID) as a path parameter and a body with a non-blank adjustmentReason; adjustedStartAt and adjustedEndAt (ISO instants) are optional. Emits a WORKORDER_TRAVEL_SEGMENT_ADJUSTMENT event; the adjusting user is recorded from the security context. Returns 201 with the adjustment, 404 when no segment exists for the id, and 409 when the segment is not APPROVED. 
     * Create Post-Approval Travel Adjustment
     */
    async createTravelSegmentAdjustment(requestParameters: CreateTravelSegmentAdjustmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TravelSegmentAdjustmentResponse> {
        const response = await this.createTravelSegmentAdjustmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Starts an IN_PROGRESS travel segment for a mobile technician, stamping the start time from the server clock and recording who created it. Use this tool when a technician begins travel tied to a mobile work assignment; do not use stopTravelSegment, which ends an already-running segment. Preconditions: no IN_PROGRESS travel segment may exist for the same mobile work assignment, and when actedForPersonId is set an onBehalfReasonCode is mandatory. Required inputs: mobileWorkAssignmentId (UUID), technicianId (UUID), and segmentType (DEPART_SHOP, ARRIVE_CUSTOMER_SITE, DEPART_CUSTOMER_SITE, ARRIVE_SHOP, TRAVEL_BETWEEN_SITES, or DEADHEAD); fromLocationId, toLocationId, workOrderId, actedForPersonId, and onBehalfReasonCode (TECHNICIAN_UNAVAILABLE, FORGOT_TO_CLOCK, DATA_ENTRY_ERROR) are optional. Emits a WORKORDER_TRAVEL_SEGMENT_START event. Returns 201 with the new segment, 400 when actedForPersonId is given without onBehalfReasonCode, and 409 when an active segment already exists for the assignment. 
     * Start a Travel Segment
     */
    async startTravelSegmentRaw(requestParameters: StartTravelSegmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TravelSegmentResponse>> {
        if (requestParameters['startTravelSegmentRequest'] == null) {
            throw new runtime.RequiredError(
                'startTravelSegmentRequest',
                'Required parameter "startTravelSegmentRequest" was null or undefined when calling startTravelSegment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["workorder:labor:add"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/workorders/travelSegments/start`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartTravelSegmentRequestToJSON(requestParameters['startTravelSegmentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TravelSegmentResponseFromJSON(jsonValue));
    }

    /**
     * Starts an IN_PROGRESS travel segment for a mobile technician, stamping the start time from the server clock and recording who created it. Use this tool when a technician begins travel tied to a mobile work assignment; do not use stopTravelSegment, which ends an already-running segment. Preconditions: no IN_PROGRESS travel segment may exist for the same mobile work assignment, and when actedForPersonId is set an onBehalfReasonCode is mandatory. Required inputs: mobileWorkAssignmentId (UUID), technicianId (UUID), and segmentType (DEPART_SHOP, ARRIVE_CUSTOMER_SITE, DEPART_CUSTOMER_SITE, ARRIVE_SHOP, TRAVEL_BETWEEN_SITES, or DEADHEAD); fromLocationId, toLocationId, workOrderId, actedForPersonId, and onBehalfReasonCode (TECHNICIAN_UNAVAILABLE, FORGOT_TO_CLOCK, DATA_ENTRY_ERROR) are optional. Emits a WORKORDER_TRAVEL_SEGMENT_START event. Returns 201 with the new segment, 400 when actedForPersonId is given without onBehalfReasonCode, and 409 when an active segment already exists for the assignment. 
     * Start a Travel Segment
     */
    async startTravelSegment(requestParameters: StartTravelSegmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TravelSegmentResponse> {
        const response = await this.startTravelSegmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Stops an IN_PROGRESS travel segment, transitioning it to COMPLETED and computing the duration in whole minutes from the server clock. Use this tool when a technician arrives and the travel leg ends; do not use submitTravelSegments, which batches finished segments for approval. Preconditions: the segment must exist and be IN_PROGRESS; COMPLETED, SUBMITTED, or APPROVED segments cannot be stopped again. Required inputs: travelSegmentId (UUID) as a path parameter; toLocationId in the body is optional and overrides the destination recorded at start. Emits a WORKORDER_TRAVEL_SEGMENT_STOP event carrying the computed duration. Returns 404 when no segment exists for the id, and 409 when the segment is not IN_PROGRESS. 
     * Stop an Active Travel Segment
     */
    async stopTravelSegmentRaw(requestParameters: StopTravelSegmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TravelSegmentResponse>> {
        if (requestParameters['travelSegmentId'] == null) {
            throw new runtime.RequiredError(
                'travelSegmentId',
                'Required parameter "travelSegmentId" was null or undefined when calling stopTravelSegment().'
            );
        }

        if (requestParameters['stopTravelSegmentRequest'] == null) {
            throw new runtime.RequiredError(
                'stopTravelSegmentRequest',
                'Required parameter "stopTravelSegmentRequest" was null or undefined when calling stopTravelSegment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["workorder:labor:add"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/workorders/travelSegments/{travelSegmentId}/stop`.replace(`{${"travelSegmentId"}}`, encodeURIComponent(String(requestParameters['travelSegmentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StopTravelSegmentRequestToJSON(requestParameters['stopTravelSegmentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TravelSegmentResponseFromJSON(jsonValue));
    }

    /**
     * Stops an IN_PROGRESS travel segment, transitioning it to COMPLETED and computing the duration in whole minutes from the server clock. Use this tool when a technician arrives and the travel leg ends; do not use submitTravelSegments, which batches finished segments for approval. Preconditions: the segment must exist and be IN_PROGRESS; COMPLETED, SUBMITTED, or APPROVED segments cannot be stopped again. Required inputs: travelSegmentId (UUID) as a path parameter; toLocationId in the body is optional and overrides the destination recorded at start. Emits a WORKORDER_TRAVEL_SEGMENT_STOP event carrying the computed duration. Returns 404 when no segment exists for the id, and 409 when the segment is not IN_PROGRESS. 
     * Stop an Active Travel Segment
     */
    async stopTravelSegment(requestParameters: StopTravelSegmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TravelSegmentResponse> {
        const response = await this.stopTravelSegmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submits the calling technician\'s IN_PROGRESS and COMPLETED travel segments for a mobile work assignment, transitioning them all to SUBMITTED for downstream approval. Use this tool at end of day when travel is ready for review; do not use stopTravelSegment, which ends a single running leg without submitting it. Preconditions: the security-context username must parse as the technician\'s UUID, and at least one IN_PROGRESS or COMPLETED segment must exist for that technician on the assignment. Required inputs: mobileWorkAssignmentId (UUID) as a path parameter and a body with workDate (ISO date); the body is validated but submission is keyed entirely on the path id and the caller\'s identity. Emits a WORKORDER_TRAVEL_SEGMENT_SUBMIT event. Returns 200 with the submitted segments, 400 when the caller\'s username is not a UUID, and 404 when no submittable segments exist for the assignment. 
     * Submit Travel Segments for Approval
     */
    async submitTravelSegmentsRaw(requestParameters: SubmitTravelSegmentsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TravelSegmentResponse>>> {
        if (requestParameters['mobileWorkAssignmentId'] == null) {
            throw new runtime.RequiredError(
                'mobileWorkAssignmentId',
                'Required parameter "mobileWorkAssignmentId" was null or undefined when calling submitTravelSegments().'
            );
        }

        if (requestParameters['submitTravelSegmentsRequest'] == null) {
            throw new runtime.RequiredError(
                'submitTravelSegmentsRequest',
                'Required parameter "submitTravelSegmentsRequest" was null or undefined when calling submitTravelSegments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["workorder:labor:add"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/workorders/travelSegments/submit/{mobileWorkAssignmentId}`.replace(`{${"mobileWorkAssignmentId"}}`, encodeURIComponent(String(requestParameters['mobileWorkAssignmentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmitTravelSegmentsRequestToJSON(requestParameters['submitTravelSegmentsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TravelSegmentResponseFromJSON));
    }

    /**
     * Submits the calling technician\'s IN_PROGRESS and COMPLETED travel segments for a mobile work assignment, transitioning them all to SUBMITTED for downstream approval. Use this tool at end of day when travel is ready for review; do not use stopTravelSegment, which ends a single running leg without submitting it. Preconditions: the security-context username must parse as the technician\'s UUID, and at least one IN_PROGRESS or COMPLETED segment must exist for that technician on the assignment. Required inputs: mobileWorkAssignmentId (UUID) as a path parameter and a body with workDate (ISO date); the body is validated but submission is keyed entirely on the path id and the caller\'s identity. Emits a WORKORDER_TRAVEL_SEGMENT_SUBMIT event. Returns 200 with the submitted segments, 400 when the caller\'s username is not a UUID, and 404 when no submittable segments exist for the assignment. 
     * Submit Travel Segments for Approval
     */
    async submitTravelSegments(requestParameters: SubmitTravelSegmentsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TravelSegmentResponse>> {
        const response = await this.submitTravelSegmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
