"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * POS Workorder Service API
 * Workorder service for managing workorders and tasks
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.WorkorderDetailApi = void 0;
const runtime = __importStar(require("../runtime"));
/**
 *
 */
class WorkorderDetailApi extends runtime.BaseAPI {
    /**
     * Returns comprehensive workorder detail. Financial fields are conditionally included based on user authorities. Capability flags indicate which actions the user can perform.
     * Get workorder detail with role-based visibility
     */
    async getWorkorderDetailRaw(requestParameters, initOverrides) {
        if (requestParameters['workorderId'] == null) {
            throw new runtime.RequiredError('workorderId', 'Required parameter "workorderId" was null or undefined when calling getWorkorderDetail().');
        }
        const queryParameters = {};
        const headerParameters = {};
        if (requestParameters['xAuthorities'] != null) {
            headerParameters['X-Authorities'] = String(requestParameters['xAuthorities']);
        }
        const response = await this.request({
            path: `/v1/workorders/{workorderId}/detail`.replace(`{${"workorderId"}}`, encodeURIComponent(String(requestParameters['workorderId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse(response);
        }
        else {
            return new runtime.TextApiResponse(response);
        }
    }
    /**
     * Returns comprehensive workorder detail. Financial fields are conditionally included based on user authorities. Capability flags indicate which actions the user can perform.
     * Get workorder detail with role-based visibility
     */
    async getWorkorderDetail(requestParameters, initOverrides) {
        const response = await this.getWorkorderDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
exports.WorkorderDetailApi = WorkorderDetailApi;
