/* tslint:disable */
/* eslint-disable */
/**
 * Marketing API
 * API for marketing campaigns, message templates, audience binding, send orchestration, and campaign analytics in the POS system
 *
 * The version of the OpenAPI document: 1.0
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CampaignStatsResponse } from './CampaignStatsResponse';
import {
    CampaignStatsResponseFromJSON,
    CampaignStatsResponseFromJSONTyped,
    CampaignStatsResponseToJSON,
} from './CampaignStatsResponse';

/**
 * Campaign program rollup comparing commercial and individual arms
 * @export
 * @interface ProgramStatsResponse
 */
export interface ProgramStatsResponse {
    /**
     * One entry per campaign in the program
     * @type {Array<CampaignStatsResponse>}
     * @memberof ProgramStatsResponse
     */
    arms: Array<CampaignStatsResponse>;
    /**
     * Program identifier
     * @type {string}
     * @memberof ProgramStatsResponse
     */
    campaignProgramId: string;
}

/**
 * Check if a given object implements the ProgramStatsResponse interface.
 */
export function instanceOfProgramStatsResponse(value: object): boolean {
    if (!('arms' in value)) return false;
    if (!('campaignProgramId' in value)) return false;
    return true;
}

export function ProgramStatsResponseFromJSON(json: any): ProgramStatsResponse {
    return ProgramStatsResponseFromJSONTyped(json, false);
}

export function ProgramStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProgramStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'arms': ((json['arms'] as Array<any>).map(CampaignStatsResponseFromJSON)),
        'campaignProgramId': json['campaignProgramId'],
    };
}

export function ProgramStatsResponseToJSON(value?: ProgramStatsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'arms': ((value['arms'] as Array<any>).map(CampaignStatsResponseToJSON)),
        'campaignProgramId': value['campaignProgramId'],
    };
}

