/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { CountEntryResponse, CycleCountTaskResponse } from '../models/index';
export interface GetAuditorTasksRequest {
    auditorId: string;
}
export interface GetCountHistoryRequest {
    taskId: string;
}
export interface GetTaskRequest {
    taskId: string;
}
/**
 *
 */
export declare class CycleCountQueryApi extends runtime.BaseAPI {
    /**
     * Retrieves all cycle count tasks assigned to a specific auditor.
     * Get tasks assigned to an auditor
     */
    getAuditorTasksRaw(requestParameters: GetAuditorTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CycleCountTaskResponse>>;
    /**
     * Retrieves all cycle count tasks assigned to a specific auditor.
     * Get tasks assigned to an auditor
     */
    getAuditorTasks(requestParameters: GetAuditorTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CycleCountTaskResponse>;
    /**
     * Retrieves all count entries (original + recounts) for a task, ordered by sequence.
     * Get count history for a task
     */
    getCountHistoryRaw(requestParameters: GetCountHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CountEntryResponse>>;
    /**
     * Retrieves all count entries (original + recounts) for a task, ordered by sequence.
     * Get count history for a task
     */
    getCountHistory(requestParameters: GetCountHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CountEntryResponse>;
    /**
     * Retrieves details of a specific cycle count task.
     * Get cycle count task details
     */
    getTaskRaw(requestParameters: GetTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CycleCountTaskResponse>>;
    /**
     * Retrieves details of a specific cycle count task.
     * Get cycle count task details
     */
    getTask(requestParameters: GetTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CycleCountTaskResponse>;
}
