/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  ConfirmPickTaskRequest,
  CreatePickListRequest,
  PickListResponse,
  PickTaskResponse,
  UpdatePickListStatusRequest,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    ConfirmPickTaskRequestFromJSON,
    ConfirmPickTaskRequestToJSON,
    CreatePickListRequestFromJSON,
    CreatePickListRequestToJSON,
    PickListResponseFromJSON,
    PickListResponseToJSON,
    PickTaskResponseFromJSON,
    PickTaskResponseToJSON,
    UpdatePickListStatusRequestFromJSON,
    UpdatePickListStatusRequestToJSON,
} from '../models/index';

export interface CancelPickListRequest {
    pickListId: string;
}

export interface ConfirmPickTaskOperationRequest {
    pickListId: string;
    taskId: string;
    confirmPickTaskRequest: ConfirmPickTaskRequest;
}

export interface CreatePickListOperationRequest {
    createPickListRequest: CreatePickListRequest;
}

export interface GetPickListRequest {
    pickListId: string;
}

export interface ListPickListsForWorkorderRequest {
    workorderId: string;
}

export interface ListPickTasksForPickListRequest {
    pickListId: string;
}

export interface ReleasePickListRequest {
    pickListId: string;
}

export interface UpdatePickListStatusOperationRequest {
    pickListId: string;
    updatePickListStatusRequest: UpdatePickListStatusRequest;
}

/**
 * 
 */
export class PickListsApi extends runtime.BaseAPI {

    /**
     * Cancels a pick list by setting its status to CANCELLED; individual task statuses are left unchanged. Use this tool to abandon picking for a workorder; do not use cancelReservation, which releases the reservation and its allocations — cancelling a pick list neither releases allocations nor writes ledger entries. Preconditions: none are enforced; cancelling an unknown pick list is a silent no-op. Required inputs: pickListId (UUID) path parameter; there is no request body. Emits an INVENTORY_PICK_LIST_CANCEL event; no ledger entries are written. Returns 204 even when the pick list does not exist, because the cancel is then a no-op. 
     * Cancel pick list
     */
    async cancelPickListRaw(requestParameters: CancelPickListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pickListId'] == null) {
            throw new runtime.RequiredError(
                'pickListId',
                'Required parameter "pickListId" was null or undefined when calling cancelPickList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:pick_list:execute"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/pick-lists/{pickListId}`.replace(`{${"pickListId"}}`, encodeURIComponent(String(requestParameters['pickListId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cancels a pick list by setting its status to CANCELLED; individual task statuses are left unchanged. Use this tool to abandon picking for a workorder; do not use cancelReservation, which releases the reservation and its allocations — cancelling a pick list neither releases allocations nor writes ledger entries. Preconditions: none are enforced; cancelling an unknown pick list is a silent no-op. Required inputs: pickListId (UUID) path parameter; there is no request body. Emits an INVENTORY_PICK_LIST_CANCEL event; no ledger entries are written. Returns 204 even when the pick list does not exist, because the cancel is then a no-op. 
     * Cancel pick list
     */
    async cancelPickList(requestParameters: CancelPickListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cancelPickListRaw(requestParameters, initOverrides);
    }

    /**
     * Confirms one pick task against scanned data, marking it PICKED with the quantity picked and the lot the units were taken from; when every task on the list is PICKED the pick list flips to COMPLETED. Use this tool once per physical pick; do not use confirmPickingList on the pickingLists path, which is an unimplemented stub that always returns 501, and do not use consumePickedItems until after confirmation — consumption posts the stock decrement, while confirmation posts no ledger entries. Preconditions: the pick task must exist and belong to the pick list; for a LOT-tracked SKU the lot must be keyed and resolve to an existing ACTIVE lot. Required inputs: pickListId and taskId (UUIDs) as path parameters, plus scannedSkuId (UUID), scannedLocationId (UUID) and quantityPicked (positive, at most the task\'s required quantity); lotNumber is required for LOT-tracked SKUs, ignored for untracked ones, and overrides the task\'s advisory suggestedLotNumber. Emits an INVENTORY_PICK_TASK_CONFIRM event; the resolved pickedLotId is stored on the task and travels to the consumption posting. Returns 404 when the pick list or task is unknown or the task belongs to another list, 422 with PICK_SCAN_MISMATCH when scannedSkuId differs from the task\'s product, 422 with LOT_NUMBER_REQUIRED, LOT_UNKNOWN or LOT_NOT_AVAILABLE for lot failures, and 400 when quantityPicked exceeds the required quantity. 
     * Confirm pick task
     */
    async confirmPickTaskRaw(requestParameters: ConfirmPickTaskOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PickTaskResponse>> {
        if (requestParameters['pickListId'] == null) {
            throw new runtime.RequiredError(
                'pickListId',
                'Required parameter "pickListId" was null or undefined when calling confirmPickTask().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling confirmPickTask().'
            );
        }

        if (requestParameters['confirmPickTaskRequest'] == null) {
            throw new runtime.RequiredError(
                'confirmPickTaskRequest',
                'Required parameter "confirmPickTaskRequest" was null or undefined when calling confirmPickTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:pick_list:execute"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/pick-lists/{pickListId}/tasks/{taskId}/confirm`.replace(`{${"pickListId"}}`, encodeURIComponent(String(requestParameters['pickListId']))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters['taskId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmPickTaskRequestToJSON(requestParameters['confirmPickTaskRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PickTaskResponseFromJSON(jsonValue));
    }

    /**
     * Confirms one pick task against scanned data, marking it PICKED with the quantity picked and the lot the units were taken from; when every task on the list is PICKED the pick list flips to COMPLETED. Use this tool once per physical pick; do not use confirmPickingList on the pickingLists path, which is an unimplemented stub that always returns 501, and do not use consumePickedItems until after confirmation — consumption posts the stock decrement, while confirmation posts no ledger entries. Preconditions: the pick task must exist and belong to the pick list; for a LOT-tracked SKU the lot must be keyed and resolve to an existing ACTIVE lot. Required inputs: pickListId and taskId (UUIDs) as path parameters, plus scannedSkuId (UUID), scannedLocationId (UUID) and quantityPicked (positive, at most the task\'s required quantity); lotNumber is required for LOT-tracked SKUs, ignored for untracked ones, and overrides the task\'s advisory suggestedLotNumber. Emits an INVENTORY_PICK_TASK_CONFIRM event; the resolved pickedLotId is stored on the task and travels to the consumption posting. Returns 404 when the pick list or task is unknown or the task belongs to another list, 422 with PICK_SCAN_MISMATCH when scannedSkuId differs from the task\'s product, 422 with LOT_NUMBER_REQUIRED, LOT_UNKNOWN or LOT_NOT_AVAILABLE for lot failures, and 400 when quantityPicked exceeds the required quantity. 
     * Confirm pick task
     */
    async confirmPickTask(requestParameters: ConfirmPickTaskOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PickTaskResponse> {
        const response = await this.confirmPickTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a pick list for a workorder in DRAFT status; pick tasks are not generated by this call — they are attached by the pick-list generation flow, and releasePickList later opens the list for execution. Use this tool to start pick planning for a workorder; do not use releasePickList, which only transitions an existing list to READY_TO_PICK, and do not use updatePickListStatus for creation even though it tolerates unknown ids. Preconditions: none are checked — the workorder id is not validated against the workorder service. Required inputs: workorderId (UUID); dueAt (ISO-8601 instant), priority (non-negative integer, default 0) and reservationId (UUID) are optional. Emits an INVENTORY_PICK_LIST_CREATE event; no ledger entries or allocations are written. Returns 201 with the created pick list, and 400 when workorderId is missing or priority is negative. 
     * Create pick list
     */
    async createPickListRaw(requestParameters: CreatePickListOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PickListResponse>> {
        if (requestParameters['createPickListRequest'] == null) {
            throw new runtime.RequiredError(
                'createPickListRequest',
                'Required parameter "createPickListRequest" was null or undefined when calling createPickList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:pick_list:create"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/pick-lists`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePickListRequestToJSON(requestParameters['createPickListRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PickListResponseFromJSON(jsonValue));
    }

    /**
     * Creates a pick list for a workorder in DRAFT status; pick tasks are not generated by this call — they are attached by the pick-list generation flow, and releasePickList later opens the list for execution. Use this tool to start pick planning for a workorder; do not use releasePickList, which only transitions an existing list to READY_TO_PICK, and do not use updatePickListStatus for creation even though it tolerates unknown ids. Preconditions: none are checked — the workorder id is not validated against the workorder service. Required inputs: workorderId (UUID); dueAt (ISO-8601 instant), priority (non-negative integer, default 0) and reservationId (UUID) are optional. Emits an INVENTORY_PICK_LIST_CREATE event; no ledger entries or allocations are written. Returns 201 with the created pick list, and 400 when workorderId is missing or priority is negative. 
     * Create pick list
     */
    async createPickList(requestParameters: CreatePickListOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PickListResponse> {
        const response = await this.createPickListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns one pick list header with its workorder linkage, lifecycle status, priority and due timestamp. Use this tool when the pickListId is already known; use listPickListsForWorkorder instead to find lists by workorder, and listPickTasksForPickList for the list\'s tasks. Preconditions: the pick list must exist. Required inputs: pickListId (UUID) path parameter; there is no request body. No events are emitted and no state changes; this is a read-only projection. Returns 404 when no pick list exists for the supplied id. 
     * Get pick list
     */
    async getPickListRaw(requestParameters: GetPickListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PickListResponse>> {
        if (requestParameters['pickListId'] == null) {
            throw new runtime.RequiredError(
                'pickListId',
                'Required parameter "pickListId" was null or undefined when calling getPickList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:pick_list:view"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/pick-lists/{pickListId}`.replace(`{${"pickListId"}}`, encodeURIComponent(String(requestParameters['pickListId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PickListResponseFromJSON(jsonValue));
    }

    /**
     * Returns one pick list header with its workorder linkage, lifecycle status, priority and due timestamp. Use this tool when the pickListId is already known; use listPickListsForWorkorder instead to find lists by workorder, and listPickTasksForPickList for the list\'s tasks. Preconditions: the pick list must exist. Required inputs: pickListId (UUID) path parameter; there is no request body. No events are emitted and no state changes; this is a read-only projection. Returns 404 when no pick list exists for the supplied id. 
     * Get pick list
     */
    async getPickList(requestParameters: GetPickListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PickListResponse> {
        const response = await this.getPickListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns every pick list linked to a workorder. Use this tool to find a workorder\'s pick lists and their statuses; use getPickList instead when the pickListId is already known. Preconditions: none; an unknown workorderId simply yields an empty array. Required inputs: workorderId (UUID) as a query parameter; there is no request body. No events are emitted and no state changes; this is a read-only projection. Returns 200 with an empty array when the workorder has no pick lists. 
     * List pick lists for workorder
     */
    async listPickListsForWorkorderRaw(requestParameters: ListPickListsForWorkorderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PickListResponse>>> {
        if (requestParameters['workorderId'] == null) {
            throw new runtime.RequiredError(
                'workorderId',
                'Required parameter "workorderId" was null or undefined when calling listPickListsForWorkorder().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workorderId'] != null) {
            queryParameters['workorderId'] = requestParameters['workorderId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:pick_list:view"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/pick-lists`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PickListResponseFromJSON));
    }

    /**
     * Returns every pick list linked to a workorder. Use this tool to find a workorder\'s pick lists and their statuses; use getPickList instead when the pickListId is already known. Preconditions: none; an unknown workorderId simply yields an empty array. Required inputs: workorderId (UUID) as a query parameter; there is no request body. No events are emitted and no state changes; this is a read-only projection. Returns 200 with an empty array when the workorder has no pick lists. 
     * List pick lists for workorder
     */
    async listPickListsForWorkorder(requestParameters: ListPickListsForWorkorderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PickListResponse>> {
        const response = await this.listPickListsForWorkorderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the pick tasks of a pick list with their status, quantities, suggested location and lot fields. Use this tool to drive a picking screen after releasePickList; use getPickList instead for the list header only. Preconditions: none are enforced — an unknown pickListId yields an empty array rather than a 404. Required inputs: pickListId (UUID) path parameter; there is no request body. No events are emitted and no state changes; this is a read-only projection. Returns 200 with an empty array when the pick list has no tasks or does not exist. 
     * List pick tasks for pick list
     */
    async listPickTasksForPickListRaw(requestParameters: ListPickTasksForPickListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PickTaskResponse>>> {
        if (requestParameters['pickListId'] == null) {
            throw new runtime.RequiredError(
                'pickListId',
                'Required parameter "pickListId" was null or undefined when calling listPickTasksForPickList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:pick_list:view"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/pick-lists/{pickListId}/tasks`.replace(`{${"pickListId"}}`, encodeURIComponent(String(requestParameters['pickListId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PickTaskResponseFromJSON));
    }

    /**
     * Returns the pick tasks of a pick list with their status, quantities, suggested location and lot fields. Use this tool to drive a picking screen after releasePickList; use getPickList instead for the list header only. Preconditions: none are enforced — an unknown pickListId yields an empty array rather than a 404. Required inputs: pickListId (UUID) path parameter; there is no request body. No events are emitted and no state changes; this is a read-only projection. Returns 200 with an empty array when the pick list has no tasks or does not exist. 
     * List pick tasks for pick list
     */
    async listPickTasksForPickList(requestParameters: ListPickTasksForPickListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PickTaskResponse>> {
        const response = await this.listPickTasksForPickListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Releases a pick list by setting its status to READY_TO_PICK so its pick tasks can be executed. Use this tool when planning is done and picking should start, then confirm each task with confirmPickTask; do not use updatePickListStatus for release — it applies any status without this operation\'s intent. Preconditions: the pick list must exist; no prior-status guard is enforced, so releasing an already released or completed list simply re-applies READY_TO_PICK. Required inputs: pickListId (UUID) path parameter; there is no request body. Emits an INVENTORY_PICK_LIST_RELEASE event; no ledger entries are written. Returns 404 when no pick list exists for the supplied id. 
     * Release pick list
     */
    async releasePickListRaw(requestParameters: ReleasePickListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PickListResponse>> {
        if (requestParameters['pickListId'] == null) {
            throw new runtime.RequiredError(
                'pickListId',
                'Required parameter "pickListId" was null or undefined when calling releasePickList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:pick_list:execute"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/pick-lists/{pickListId}/release`.replace(`{${"pickListId"}}`, encodeURIComponent(String(requestParameters['pickListId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PickListResponseFromJSON(jsonValue));
    }

    /**
     * Releases a pick list by setting its status to READY_TO_PICK so its pick tasks can be executed. Use this tool when planning is done and picking should start, then confirm each task with confirmPickTask; do not use updatePickListStatus for release — it applies any status without this operation\'s intent. Preconditions: the pick list must exist; no prior-status guard is enforced, so releasing an already released or completed list simply re-applies READY_TO_PICK. Required inputs: pickListId (UUID) path parameter; there is no request body. Emits an INVENTORY_PICK_LIST_RELEASE event; no ledger entries are written. Returns 404 when no pick list exists for the supplied id. 
     * Release pick list
     */
    async releasePickList(requestParameters: ReleasePickListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PickListResponse> {
        const response = await this.releasePickListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Applies a lifecycle status (DRAFT, READY_TO_PICK, IN_PROGRESS, COMPLETED or CANCELLED) to a pick list. Use this tool for manual status corrections; do not use it in place of releasePickList, the intended release transition, or cancelPickList, the intended cancel. Preconditions: none are enforced — no transition rules apply, and an unknown pickListId is not rejected: a new pick list row is created under that id with the requested status. Required inputs: pickListId (UUID) path parameter and status in the body. Emits an INVENTORY_PICK_LIST_STATUS_UPDATE event; no ledger entries are written and task statuses are not touched. Returns 400 when status is missing; it never returns 404 because an unknown id upserts a new row. 
     * Update pick list status
     */
    async updatePickListStatusRaw(requestParameters: UpdatePickListStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PickListResponse>> {
        if (requestParameters['pickListId'] == null) {
            throw new runtime.RequiredError(
                'pickListId',
                'Required parameter "pickListId" was null or undefined when calling updatePickListStatus().'
            );
        }

        if (requestParameters['updatePickListStatusRequest'] == null) {
            throw new runtime.RequiredError(
                'updatePickListStatusRequest',
                'Required parameter "updatePickListStatusRequest" was null or undefined when calling updatePickListStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:pick_list:execute"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/pick-lists/{pickListId}/status`.replace(`{${"pickListId"}}`, encodeURIComponent(String(requestParameters['pickListId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePickListStatusRequestToJSON(requestParameters['updatePickListStatusRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PickListResponseFromJSON(jsonValue));
    }

    /**
     * Applies a lifecycle status (DRAFT, READY_TO_PICK, IN_PROGRESS, COMPLETED or CANCELLED) to a pick list. Use this tool for manual status corrections; do not use it in place of releasePickList, the intended release transition, or cancelPickList, the intended cancel. Preconditions: none are enforced — no transition rules apply, and an unknown pickListId is not rejected: a new pick list row is created under that id with the requested status. Required inputs: pickListId (UUID) path parameter and status in the body. Emits an INVENTORY_PICK_LIST_STATUS_UPDATE event; no ledger entries are written and task statuses are not touched. Returns 400 when status is missing; it never returns 404 because an unknown id upserts a new row. 
     * Update pick list status
     */
    async updatePickListStatus(requestParameters: UpdatePickListStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PickListResponse> {
        const response = await this.updatePickListStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
