/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  CreateTransferOrderRequest,
  DispatchTransferOrderRequest,
  ReceiveTransferOrderRequest,
  ShortCloseTransferOrderRequest,
  TransferOrderResponse,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    CreateTransferOrderRequestFromJSON,
    CreateTransferOrderRequestToJSON,
    DispatchTransferOrderRequestFromJSON,
    DispatchTransferOrderRequestToJSON,
    ReceiveTransferOrderRequestFromJSON,
    ReceiveTransferOrderRequestToJSON,
    ShortCloseTransferOrderRequestFromJSON,
    ShortCloseTransferOrderRequestToJSON,
    TransferOrderResponseFromJSON,
    TransferOrderResponseToJSON,
} from '../models/index';

export interface ApproveTransferOrderRequest {
    transferOrderId: string;
}

export interface CancelTransferOrderRequest {
    transferOrderId: string;
}

export interface CreateTransferOrderOperationRequest {
    createTransferOrderRequest: CreateTransferOrderRequest;
}

export interface DispatchTransferOrderOperationRequest {
    transferOrderId: string;
    dispatchTransferOrderRequest?: DispatchTransferOrderRequest;
}

export interface GetTransferOrderRequest {
    transferOrderId: string;
}

export interface ListTransferOrdersRequest {
    status?: ListTransferOrdersStatusEnum;
    sourceLocationId?: string;
    destinationLocationId?: string;
}

export interface ReceiveTransferOrderOperationRequest {
    transferOrderId: string;
    receiveTransferOrderRequest?: ReceiveTransferOrderRequest;
}

export interface ShortCloseTransferOrderOperationRequest {
    transferOrderId: string;
    shortCloseTransferOrderRequest: ShortCloseTransferOrderRequest;
}

/**
 * 
 */
export class TransferOrdersApi extends runtime.BaseAPI {

    /**
     * Approves a DRAFT transfer order, moving it to APPROVED so it becomes dispatchable when the approval step is enabled (decision D-8). Use this tool only when the deployment sets pos.inventory.transfer.approval-required=true; do not use dispatchTransferOrder to approve, and with the flag off (the default) skip approval entirely because DRAFT orders dispatch directly and this call returns 409. Preconditions: the approval flag must be on and the order must be in DRAFT. Required inputs: transferOrderId (UUID) as a path parameter; there is no request body. Emits an INVENTORY_TRANSFER_ORDER_APPROVE event and queues a TransferOrderUpdatedV1 fact; no stock moves. Returns 404 when the order does not exist, and 409 when the approval step is disabled or the order is not in DRAFT. 
     * Approve transfer order
     */
    async approveTransferOrderRaw(requestParameters: ApproveTransferOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferOrderResponse>> {
        if (requestParameters['transferOrderId'] == null) {
            throw new runtime.RequiredError(
                'transferOrderId',
                'Required parameter "transferOrderId" was null or undefined when calling approveTransferOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:transfer:dispatch"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/transfer-orders/{transferOrderId}/approve`.replace(`{${"transferOrderId"}}`, encodeURIComponent(String(requestParameters['transferOrderId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferOrderResponseFromJSON(jsonValue));
    }

    /**
     * Approves a DRAFT transfer order, moving it to APPROVED so it becomes dispatchable when the approval step is enabled (decision D-8). Use this tool only when the deployment sets pos.inventory.transfer.approval-required=true; do not use dispatchTransferOrder to approve, and with the flag off (the default) skip approval entirely because DRAFT orders dispatch directly and this call returns 409. Preconditions: the approval flag must be on and the order must be in DRAFT. Required inputs: transferOrderId (UUID) as a path parameter; there is no request body. Emits an INVENTORY_TRANSFER_ORDER_APPROVE event and queues a TransferOrderUpdatedV1 fact; no stock moves. Returns 404 when the order does not exist, and 409 when the approval step is disabled or the order is not in DRAFT. 
     * Approve transfer order
     */
    async approveTransferOrder(requestParameters: ApproveTransferOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferOrderResponse> {
        const response = await this.approveTransferOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Cancels a transfer order before dispatch, moving DRAFT or APPROVED to the terminal CANCELLED status. Use this tool to abandon an order whose stock has not moved; do not use it after dispatch — the stock has physically moved, so resolve discrepancies with shortCloseTransferOrder instead. Preconditions: the order must be in DRAFT or APPROVED. Required inputs: transferOrderId (UUID) as a path parameter; there is no request body. Emits an INVENTORY_TRANSFER_ORDER_CANCEL event and queues a TransferOrderUpdatedV1 fact; no ledger entries are posted. Returns 404 when the order does not exist, and 409 when it has already been dispatched or is terminal. 
     * Cancel transfer order
     */
    async cancelTransferOrderRaw(requestParameters: CancelTransferOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferOrderResponse>> {
        if (requestParameters['transferOrderId'] == null) {
            throw new runtime.RequiredError(
                'transferOrderId',
                'Required parameter "transferOrderId" was null or undefined when calling cancelTransferOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:transfer:create"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/transfer-orders/{transferOrderId}/cancel`.replace(`{${"transferOrderId"}}`, encodeURIComponent(String(requestParameters['transferOrderId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferOrderResponseFromJSON(jsonValue));
    }

    /**
     * Cancels a transfer order before dispatch, moving DRAFT or APPROVED to the terminal CANCELLED status. Use this tool to abandon an order whose stock has not moved; do not use it after dispatch — the stock has physically moved, so resolve discrepancies with shortCloseTransferOrder instead. Preconditions: the order must be in DRAFT or APPROVED. Required inputs: transferOrderId (UUID) as a path parameter; there is no request body. Emits an INVENTORY_TRANSFER_ORDER_CANCEL event and queues a TransferOrderUpdatedV1 fact; no ledger entries are posted. Returns 404 when the order does not exist, and 409 when it has already been dispatched or is terminal. 
     * Cancel transfer order
     */
    async cancelTransferOrder(requestParameters: CancelTransferOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferOrderResponse> {
        const response = await this.cancelTransferOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a cross-site transfer order in DRAFT that will carry stock between two different sites through an explicit dispatch/receive lifecycle. Use this tool when stock must move between sites; do not use it for intra-site bin moves, which post immediately through the stock-movements endpoint, and do not use dispatchTransferOrder, which ships an order that already exists. Preconditions: source and destination must be different sites, both present in the location roster with status ACTIVE (DECISION-INVENTORY-009); an optional bin-level storage location must belong to its site when the storage-location replica knows it. Required inputs: sourceLocationId and destinationLocationId (UUID site ids) and at least one line with sku and a positive requestedQty; sourceStorageLocationId, destinationStorageLocationId and notes are optional. Emits an INVENTORY_TRANSFER_ORDER_CREATE event and queues a TransferOrderUpdatedV1 fact; no stock moves until dispatch. Returns 404 when a site is not in the location roster, 422 with TRANSFER_LOCATION_NOT_ELIGIBLE when a site is INACTIVE or PENDING, and 400 when source equals destination, a storage location belongs to another site, lines are empty or a quantity is not positive. 
     * Create transfer order
     */
    async createTransferOrderRaw(requestParameters: CreateTransferOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferOrderResponse>> {
        if (requestParameters['createTransferOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'createTransferOrderRequest',
                'Required parameter "createTransferOrderRequest" was null or undefined when calling createTransferOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:transfer:create"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/transfer-orders`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTransferOrderRequestToJSON(requestParameters['createTransferOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferOrderResponseFromJSON(jsonValue));
    }

    /**
     * Creates a cross-site transfer order in DRAFT that will carry stock between two different sites through an explicit dispatch/receive lifecycle. Use this tool when stock must move between sites; do not use it for intra-site bin moves, which post immediately through the stock-movements endpoint, and do not use dispatchTransferOrder, which ships an order that already exists. Preconditions: source and destination must be different sites, both present in the location roster with status ACTIVE (DECISION-INVENTORY-009); an optional bin-level storage location must belong to its site when the storage-location replica knows it. Required inputs: sourceLocationId and destinationLocationId (UUID site ids) and at least one line with sku and a positive requestedQty; sourceStorageLocationId, destinationStorageLocationId and notes are optional. Emits an INVENTORY_TRANSFER_ORDER_CREATE event and queues a TransferOrderUpdatedV1 fact; no stock moves until dispatch. Returns 404 when a site is not in the location roster, 422 with TRANSFER_LOCATION_NOT_ELIGIBLE when a site is INACTIVE or PENDING, and 400 when source equals destination, a storage location belongs to another site, lines are empty or a quantity is not positive. 
     * Create transfer order
     */
    async createTransferOrder(requestParameters: CreateTransferOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferOrderResponse> {
        const response = await this.createTransferOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Dispatches a transfer order from the source site, posting one TRANSFER_OUT per line through the ledger funnel that decrements source on-hand and raises the destination in-transit quantity. Use this tool when the stock physically leaves the source; do not use receiveTransferOrder, which books arrival at the destination, and do not use createTransferOrder, which only drafts the order. Preconditions: the order must be in DRAFT (or APPROVED when pos.inventory.transfer.approval-required=true), both sites must still be ACTIVE for movement, source on-hand must cover each dispatched quantity, and each LOT-tracked SKU must name an existing ACTIVE lot, which is pinned on the line for receive and short-close. Required inputs: transferOrderId (UUID) path parameter; the body is optional — lines pin a per-line quantity (at most the requested quantity) and a lotNumber for LOT-tracked SKUs, and omitted lines dispatch their full requested quantity. Emits an INVENTORY_TRANSFER_ORDER_DISPATCH event, posts the ledger batch with sourceTransactionId = transferOrderId and queues a TransferOrderUpdatedV1 fact. Returns 404 when the order does not exist, 409 when it is not dispatchable, 422 with TRANSFER_DISPATCH_EXCEEDS_REQUESTED, INSUFFICIENT_STOCK, TRANSFER_LOCATION_NOT_ELIGIBLE, LOT_NUMBER_REQUIRED, LOT_UNKNOWN or LOT_NOT_AVAILABLE, and 400 for an unknown or duplicate line id. 
     * Dispatch transfer order
     */
    async dispatchTransferOrderRaw(requestParameters: DispatchTransferOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferOrderResponse>> {
        if (requestParameters['transferOrderId'] == null) {
            throw new runtime.RequiredError(
                'transferOrderId',
                'Required parameter "transferOrderId" was null or undefined when calling dispatchTransferOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:transfer:dispatch"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/transfer-orders/{transferOrderId}/dispatch`.replace(`{${"transferOrderId"}}`, encodeURIComponent(String(requestParameters['transferOrderId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DispatchTransferOrderRequestToJSON(requestParameters['dispatchTransferOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferOrderResponseFromJSON(jsonValue));
    }

    /**
     * Dispatches a transfer order from the source site, posting one TRANSFER_OUT per line through the ledger funnel that decrements source on-hand and raises the destination in-transit quantity. Use this tool when the stock physically leaves the source; do not use receiveTransferOrder, which books arrival at the destination, and do not use createTransferOrder, which only drafts the order. Preconditions: the order must be in DRAFT (or APPROVED when pos.inventory.transfer.approval-required=true), both sites must still be ACTIVE for movement, source on-hand must cover each dispatched quantity, and each LOT-tracked SKU must name an existing ACTIVE lot, which is pinned on the line for receive and short-close. Required inputs: transferOrderId (UUID) path parameter; the body is optional — lines pin a per-line quantity (at most the requested quantity) and a lotNumber for LOT-tracked SKUs, and omitted lines dispatch their full requested quantity. Emits an INVENTORY_TRANSFER_ORDER_DISPATCH event, posts the ledger batch with sourceTransactionId = transferOrderId and queues a TransferOrderUpdatedV1 fact. Returns 404 when the order does not exist, 409 when it is not dispatchable, 422 with TRANSFER_DISPATCH_EXCEEDS_REQUESTED, INSUFFICIENT_STOCK, TRANSFER_LOCATION_NOT_ELIGIBLE, LOT_NUMBER_REQUIRED, LOT_UNKNOWN or LOT_NOT_AVAILABLE, and 400 for an unknown or duplicate line id. 
     * Dispatch transfer order
     */
    async dispatchTransferOrder(requestParameters: DispatchTransferOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferOrderResponse> {
        const response = await this.dispatchTransferOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns one transfer order with its lifecycle status, per-line requested, dispatched and received quantities, pinned lots and any short-close disposition. Use this tool when the transferOrderId is already known; use listTransferOrders instead to search by status, source or destination site. Preconditions: the transfer order must exist. Required inputs: transferOrderId (UUID) as a path parameter; there is no request body. No events are emitted and no state changes; this is a read-only projection. Returns 404 when no transfer order exists for the supplied id. 
     * Get transfer order
     */
    async getTransferOrderRaw(requestParameters: GetTransferOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferOrderResponse>> {
        if (requestParameters['transferOrderId'] == null) {
            throw new runtime.RequiredError(
                'transferOrderId',
                'Required parameter "transferOrderId" was null or undefined when calling getTransferOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:transfer:view"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/transfer-orders/{transferOrderId}`.replace(`{${"transferOrderId"}}`, encodeURIComponent(String(requestParameters['transferOrderId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferOrderResponseFromJSON(jsonValue));
    }

    /**
     * Returns one transfer order with its lifecycle status, per-line requested, dispatched and received quantities, pinned lots and any short-close disposition. Use this tool when the transferOrderId is already known; use listTransferOrders instead to search by status, source or destination site. Preconditions: the transfer order must exist. Required inputs: transferOrderId (UUID) as a path parameter; there is no request body. No events are emitted and no state changes; this is a read-only projection. Returns 404 when no transfer order exists for the supplied id. 
     * Get transfer order
     */
    async getTransferOrder(requestParameters: GetTransferOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferOrderResponse> {
        const response = await this.getTransferOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists transfer orders newest first, optionally filtered by lifecycle status, source site and destination site. Use this tool to discover transferOrderIds or survey in-flight transfers; use getTransferOrder instead when the id is already known. Preconditions: none; every filter is optional and omitted filters match everything. Required inputs: none; status (TransferOrderStatus), sourceLocationId and destinationLocationId are optional query parameters. No events are emitted and no state changes; this is a read-only projection. Returns 200 with an empty array when nothing matches, so an empty result is not an error condition. 
     * List transfer orders
     */
    async listTransferOrdersRaw(requestParameters: ListTransferOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TransferOrderResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['sourceLocationId'] != null) {
            queryParameters['sourceLocationId'] = requestParameters['sourceLocationId'];
        }

        if (requestParameters['destinationLocationId'] != null) {
            queryParameters['destinationLocationId'] = requestParameters['destinationLocationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:transfer:view"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/transfer-orders`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TransferOrderResponseFromJSON));
    }

    /**
     * Lists transfer orders newest first, optionally filtered by lifecycle status, source site and destination site. Use this tool to discover transferOrderIds or survey in-flight transfers; use getTransferOrder instead when the id is already known. Preconditions: none; every filter is optional and omitted filters match everything. Required inputs: none; status (TransferOrderStatus), sourceLocationId and destinationLocationId are optional query parameters. No events are emitted and no state changes; this is a read-only projection. Returns 200 with an empty array when nothing matches, so an empty result is not an error condition. 
     * List transfer orders
     */
    async listTransferOrders(requestParameters: ListTransferOrdersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TransferOrderResponse>> {
        const response = await this.listTransferOrdersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Receives dispatched quantities at the destination site, posting one TRANSFER_IN per line through the ledger funnel that raises destination on-hand and drains the in-transit quantity. Use this tool when goods arrive at the destination; do not use dispatchTransferOrder, which ships from the source, and use shortCloseTransferOrder instead when the remainder will never arrive. Preconditions: the order must be DISPATCHED or PARTIALLY_RECEIVED and the destination site must still be ACTIVE for movement; each line receives against the lot pinned at dispatch, never a request-keyed one. Required inputs: transferOrderId (UUID) path parameter; the body is optional — lines pin a per-line quantity (at most dispatched minus already received), and omitted lines receive their full un-received remainder. Emits an INVENTORY_TRANSFER_ORDER_RECEIVE event and queues a TransferOrderUpdatedV1 fact; the status becomes RECEIVED when every line is fully received, else PARTIALLY_RECEIVED with the remainder still in transit. Returns 404 when the order does not exist, 409 when it is not receivable, 422 with TRANSFER_RECEIVE_EXCEEDS_DISPATCHED or TRANSFER_LOCATION_NOT_ELIGIBLE, and 400 for an unknown or duplicate line id. 
     * Receive transfer order
     */
    async receiveTransferOrderRaw(requestParameters: ReceiveTransferOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferOrderResponse>> {
        if (requestParameters['transferOrderId'] == null) {
            throw new runtime.RequiredError(
                'transferOrderId',
                'Required parameter "transferOrderId" was null or undefined when calling receiveTransferOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:transfer:receive"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/transfer-orders/{transferOrderId}/receive`.replace(`{${"transferOrderId"}}`, encodeURIComponent(String(requestParameters['transferOrderId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReceiveTransferOrderRequestToJSON(requestParameters['receiveTransferOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferOrderResponseFromJSON(jsonValue));
    }

    /**
     * Receives dispatched quantities at the destination site, posting one TRANSFER_IN per line through the ledger funnel that raises destination on-hand and drains the in-transit quantity. Use this tool when goods arrive at the destination; do not use dispatchTransferOrder, which ships from the source, and use shortCloseTransferOrder instead when the remainder will never arrive. Preconditions: the order must be DISPATCHED or PARTIALLY_RECEIVED and the destination site must still be ACTIVE for movement; each line receives against the lot pinned at dispatch, never a request-keyed one. Required inputs: transferOrderId (UUID) path parameter; the body is optional — lines pin a per-line quantity (at most dispatched minus already received), and omitted lines receive their full un-received remainder. Emits an INVENTORY_TRANSFER_ORDER_RECEIVE event and queues a TransferOrderUpdatedV1 fact; the status becomes RECEIVED when every line is fully received, else PARTIALLY_RECEIVED with the remainder still in transit. Returns 404 when the order does not exist, 409 when it is not receivable, 422 with TRANSFER_RECEIVE_EXCEEDS_DISPATCHED or TRANSFER_LOCATION_NOT_ELIGIBLE, and 400 for an unknown or duplicate line id. 
     * Receive transfer order
     */
    async receiveTransferOrder(requestParameters: ReceiveTransferOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferOrderResponse> {
        const response = await this.receiveTransferOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Short-closes a transfer order whose in-transit remainder will never be received normally, resolving every line\'s dispatched-minus-received quantity with one whole-order disposition. Use this tool for stock lost or turned back in transit; do not use cancelTransferOrder, which only works before dispatch, and do not use receiveTransferOrder, which books a normal arrival. Preconditions: the order must be DISPATCHED or PARTIALLY_RECEIVED with a positive in-transit remainder; for RETURNED_TO_SOURCE the source site must still be ACTIVE for movement, while LOST_IN_TRANSIT deliberately skips the eligibility check so a loss can be resolved toward a deactivated destination. Required inputs: transferOrderId (UUID) path parameter plus a body with disposition (LOST_IN_TRANSIT writes the remainder off via a paired constructive TRANSFER_IN and SCRAP_OUT with reason LOST at the destination; RETURNED_TO_SOURCE restores it to source on-hand), and mandatory reason and notes. Emits an INVENTORY_TRANSFER_ORDER_SHORT_CLOSE event; all ledger entries post atomically with sourceTransactionId = transferOrderId, destination in-transit zeroes, the order reaches the terminal SHORT_CLOSED status, and the TransferOrderUpdatedV1 fact carries the disposition — no scrap document is created. Returns 404 when the order does not exist, 409 when it is not short-closable or has no outstanding remainder, 422 with TRANSFER_LOCATION_NOT_ELIGIBLE for RETURNED_TO_SOURCE toward an ineligible source, and 400 when disposition, reason or notes are missing. 
     * Short-close transfer order
     */
    async shortCloseTransferOrderRaw(requestParameters: ShortCloseTransferOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferOrderResponse>> {
        if (requestParameters['transferOrderId'] == null) {
            throw new runtime.RequiredError(
                'transferOrderId',
                'Required parameter "transferOrderId" was null or undefined when calling shortCloseTransferOrder().'
            );
        }

        if (requestParameters['shortCloseTransferOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'shortCloseTransferOrderRequest',
                'Required parameter "shortCloseTransferOrderRequest" was null or undefined when calling shortCloseTransferOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["inventory:transfer:short_close"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/inventory/transfer-orders/{transferOrderId}/short-close`.replace(`{${"transferOrderId"}}`, encodeURIComponent(String(requestParameters['transferOrderId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ShortCloseTransferOrderRequestToJSON(requestParameters['shortCloseTransferOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferOrderResponseFromJSON(jsonValue));
    }

    /**
     * Short-closes a transfer order whose in-transit remainder will never be received normally, resolving every line\'s dispatched-minus-received quantity with one whole-order disposition. Use this tool for stock lost or turned back in transit; do not use cancelTransferOrder, which only works before dispatch, and do not use receiveTransferOrder, which books a normal arrival. Preconditions: the order must be DISPATCHED or PARTIALLY_RECEIVED with a positive in-transit remainder; for RETURNED_TO_SOURCE the source site must still be ACTIVE for movement, while LOST_IN_TRANSIT deliberately skips the eligibility check so a loss can be resolved toward a deactivated destination. Required inputs: transferOrderId (UUID) path parameter plus a body with disposition (LOST_IN_TRANSIT writes the remainder off via a paired constructive TRANSFER_IN and SCRAP_OUT with reason LOST at the destination; RETURNED_TO_SOURCE restores it to source on-hand), and mandatory reason and notes. Emits an INVENTORY_TRANSFER_ORDER_SHORT_CLOSE event; all ledger entries post atomically with sourceTransactionId = transferOrderId, destination in-transit zeroes, the order reaches the terminal SHORT_CLOSED status, and the TransferOrderUpdatedV1 fact carries the disposition — no scrap document is created. Returns 404 when the order does not exist, 409 when it is not short-closable or has no outstanding remainder, 422 with TRANSFER_LOCATION_NOT_ELIGIBLE for RETURNED_TO_SOURCE toward an ineligible source, and 400 when disposition, reason or notes are missing. 
     * Short-close transfer order
     */
    async shortCloseTransferOrder(requestParameters: ShortCloseTransferOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferOrderResponse> {
        const response = await this.shortCloseTransferOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum ListTransferOrdersStatusEnum {
    Draft = 'DRAFT',
    Approved = 'APPROVED',
    Dispatched = 'DISPATCHED',
    PartiallyReceived = 'PARTIALLY_RECEIVED',
    Received = 'RECEIVED',
    ShortClosed = 'SHORT_CLOSED',
    Cancelled = 'CANCELLED'
}
