/* tslint:disable */
/* eslint-disable */
/**
 * POS Shop Manager Service API
 * Shop Manager service for managing shop operations and staff
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BayCapacityView } from './BayCapacityView';
import {
    BayCapacityViewFromJSON,
    BayCapacityViewFromJSONTyped,
    BayCapacityViewToJSON,
} from './BayCapacityView';

/**
 * Bay occupancy for a single date
 * @export
 * @interface DayCapacityView
 */
export interface DayCapacityView {
    /**
     * Every active bay at the location with its occupancy for this date. Empty unless status is OK — a bay with zero appointments is still listed, with occupiedMinutes 0 (AC9).
     * @type {Array<BayCapacityView>}
     * @memberof DayCapacityView
     */
    bays: Array<BayCapacityView>;
    /**
     * Reason recorded against the holiday closure covering this date; set only when status is HOLIDAY
     * @type {string}
     * @memberof DayCapacityView
     */
    closureReason?: string;
    /**
     * Calendar date (ISO-8601)
     * @type {Date}
     * @memberof DayCapacityView
     */
    date: Date;
    /**
     * End of this date's operating window, from this date's own hours entry. Null unless status is OK.
     * @type {Date}
     * @memberof DayCapacityView
     */
    dayEndAt?: Date;
    /**
     * Start of this date's operating window, from this date's own hours entry. Null unless status is OK.
     * @type {Date}
     * @memberof DayCapacityView
     */
    dayStartAt?: Date;
    /**
     * Assembly outcome for this date
     * @type {string}
     * @memberof DayCapacityView
     */
    status: DayCapacityViewStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum DayCapacityViewStatusEnum {
    Ok = 'OK',
    Closed = 'CLOSED',
    Holiday = 'HOLIDAY',
    Unavailable = 'UNAVAILABLE'
}


/**
 * Check if a given object implements the DayCapacityView interface.
 */
export function instanceOfDayCapacityView(value: object): boolean {
    if (!('bays' in value)) return false;
    if (!('date' in value)) return false;
    if (!('status' in value)) return false;
    return true;
}

export function DayCapacityViewFromJSON(json: any): DayCapacityView {
    return DayCapacityViewFromJSONTyped(json, false);
}

export function DayCapacityViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayCapacityView {
    if (json == null) {
        return json;
    }
    return {
        
        'bays': ((json['bays'] as Array<any>).map(BayCapacityViewFromJSON)),
        'closureReason': json['closureReason'] == null ? undefined : json['closureReason'],
        'date': (new Date(json['date'])),
        'dayEndAt': json['dayEndAt'] == null ? undefined : (new Date(json['dayEndAt'])),
        'dayStartAt': json['dayStartAt'] == null ? undefined : (new Date(json['dayStartAt'])),
        'status': json['status'],
    };
}

export function DayCapacityViewToJSON(value?: DayCapacityView | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bays': ((value['bays'] as Array<any>).map(BayCapacityViewToJSON)),
        'closureReason': value['closureReason'],
        'date': ((value['date']).toISOString().substring(0,10)),
        'dayEndAt': value['dayEndAt'] == null ? undefined : ((value['dayEndAt']).toISOString()),
        'dayStartAt': value['dayStartAt'] == null ? undefined : ((value['dayStartAt']).toISOString()),
        'status': value['status'],
    };
}

