"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * POS Shop Manager Service API
 * Shop Manager service for managing shop operations and staff
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MechanicAssignmentItemRoleEnum = void 0;
exports.instanceOfMechanicAssignmentItem = instanceOfMechanicAssignmentItem;
exports.MechanicAssignmentItemFromJSON = MechanicAssignmentItemFromJSON;
exports.MechanicAssignmentItemFromJSONTyped = MechanicAssignmentItemFromJSONTyped;
exports.MechanicAssignmentItemToJSON = MechanicAssignmentItemToJSON;
/**
* @export
* @enum {string}
*/
var MechanicAssignmentItemRoleEnum;
(function (MechanicAssignmentItemRoleEnum) {
    MechanicAssignmentItemRoleEnum["Lead"] = "LEAD";
    MechanicAssignmentItemRoleEnum["Assist"] = "ASSIST";
})(MechanicAssignmentItemRoleEnum || (exports.MechanicAssignmentItemRoleEnum = MechanicAssignmentItemRoleEnum = {}));
/**
 * Check if a given object implements the MechanicAssignmentItem interface.
 */
function instanceOfMechanicAssignmentItem(value) {
    return true;
}
function MechanicAssignmentItemFromJSON(json) {
    return MechanicAssignmentItemFromJSONTyped(json, false);
}
function MechanicAssignmentItemFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'mechanicPersonId': json['mechanicPersonId'] == null ? undefined : json['mechanicPersonId'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}
function MechanicAssignmentItemToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'mechanicPersonId': value['mechanicPersonId'],
        'role': value['role'],
    };
}
