/* tslint:disable */
/* eslint-disable */
/**
 * POS Shop Manager Service API
 * Shop Manager service for managing shop operations and staff
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConflictDetails } from './ConflictDetails';
import {
    ConflictDetailsFromJSON,
    ConflictDetailsFromJSONTyped,
    ConflictDetailsToJSON,
} from './ConflictDetails';

/**
 * A single event displayed within a resource lane
 * @export
 * @interface ScheduleEventView
 */
export interface ScheduleEventView {
    /**
     * 
     * @type {ConflictDetails}
     * @memberof ScheduleEventView
     */
    conflictDetails?: ConflictDetails;
    /**
     * Event end instant in UTC (ISO-8601)
     * @type {Date}
     * @memberof ScheduleEventView
     */
    endTime: Date;
    /**
     * Event identifier
     * @type {string}
     * @memberof ScheduleEventView
     */
    eventId: string;
    /**
     * Event type (e.g. APPOINTMENT, SHIFT, PTO)
     * @type {string}
     * @memberof ScheduleEventView
     */
    eventType: string;
    /**
     * Whether this event has a scheduling conflict
     * @type {boolean}
     * @memberof ScheduleEventView
     */
    hasConflict: boolean;
    /**
     * Conflict severity when hasConflict is true (HARD or SOFT)
     * @type {string}
     * @memberof ScheduleEventView
     */
    severity?: string;
    /**
     * Event start instant in UTC (ISO-8601)
     * @type {Date}
     * @memberof ScheduleEventView
     */
    startTime: Date;
    /**
     * Event sub-type, when applicable
     * @type {string}
     * @memberof ScheduleEventView
     */
    subType?: string;
    /**
     * Event display title
     * @type {string}
     * @memberof ScheduleEventView
     */
    title?: string;
}

/**
 * Check if a given object implements the ScheduleEventView interface.
 */
export function instanceOfScheduleEventView(value: object): boolean {
    if (!('endTime' in value)) return false;
    if (!('eventId' in value)) return false;
    if (!('eventType' in value)) return false;
    if (!('hasConflict' in value)) return false;
    if (!('startTime' in value)) return false;
    return true;
}

export function ScheduleEventViewFromJSON(json: any): ScheduleEventView {
    return ScheduleEventViewFromJSONTyped(json, false);
}

export function ScheduleEventViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleEventView {
    if (json == null) {
        return json;
    }
    return {
        
        'conflictDetails': json['conflictDetails'] == null ? undefined : ConflictDetailsFromJSON(json['conflictDetails']),
        'endTime': (new Date(json['endTime'])),
        'eventId': json['eventId'],
        'eventType': json['eventType'],
        'hasConflict': json['hasConflict'],
        'severity': json['severity'] == null ? undefined : json['severity'],
        'startTime': (new Date(json['startTime'])),
        'subType': json['subType'] == null ? undefined : json['subType'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function ScheduleEventViewToJSON(value?: ScheduleEventView | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'conflictDetails': ConflictDetailsToJSON(value['conflictDetails']),
        'endTime': ((value['endTime']).toISOString()),
        'eventId': value['eventId'],
        'eventType': value['eventType'],
        'hasConflict': value['hasConflict'],
        'severity': value['severity'],
        'startTime': ((value['startTime']).toISOString()),
        'subType': value['subType'],
        'title': value['title'],
    };
}

