/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Order API
 * API documentation for the Order service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for adding an item line to a cart
 * @export
 * @interface AddItemRequest
 */
export interface AddItemRequest {
    /**
     * Customer-visible line note
     * @type {string}
     * @memberof AddItemRequest
     */
    customerNote?: string;
    /**
     * Shop-internal line note
     * @type {string}
     * @memberof AddItemRequest
     */
    internalNote?: string;
    /**
     * Stock keeping unit identifying the item to add
     * @type {string}
     * @memberof AddItemRequest
     */
    itemSku: string;
    /**
     * Client-supplied stable line identity; a replayed add with a known lineUuid updates the existing line instead of duplicating it
     * @type {string}
     * @memberof AddItemRequest
     */
    lineUuid?: string;
    /**
     * Manual unit price override for the item, when applicable
     * @type {number}
     * @memberof AddItemRequest
     */
    manualPrice?: number;
    /**
     * Quantity of the item to add to the cart
     * @type {number}
     * @memberof AddItemRequest
     */
    quantity: number;
    /**
     * Reason code justifying a manual price or special handling
     * @type {string}
     * @memberof AddItemRequest
     */
    reasonCode?: string;
    /**
     * Captured lot/serial numbers for tracked products (count must not exceed quantity; SERIAL-tracked products require one per unit at checkout, LOT-tracked at least one)
     * @type {Array<string>}
     * @memberof AddItemRequest
     */
    serialNumbers?: Array<string>;
}

/**
 * Check if a given object implements the AddItemRequest interface.
 */
export function instanceOfAddItemRequest(value: object): boolean {
    if (!('itemSku' in value)) return false;
    if (!('quantity' in value)) return false;
    return true;
}

export function AddItemRequestFromJSON(json: any): AddItemRequest {
    return AddItemRequestFromJSONTyped(json, false);
}

export function AddItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customerNote': json['customerNote'] == null ? undefined : json['customerNote'],
        'internalNote': json['internalNote'] == null ? undefined : json['internalNote'],
        'itemSku': json['itemSku'],
        'lineUuid': json['lineUuid'] == null ? undefined : json['lineUuid'],
        'manualPrice': json['manualPrice'] == null ? undefined : json['manualPrice'],
        'quantity': json['quantity'],
        'reasonCode': json['reasonCode'] == null ? undefined : json['reasonCode'],
        'serialNumbers': json['serialNumbers'] == null ? undefined : json['serialNumbers'],
    };
}

export function AddItemRequestToJSON(value?: AddItemRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'customerNote': value['customerNote'],
        'internalNote': value['internalNote'],
        'itemSku': value['itemSku'],
        'lineUuid': value['lineUuid'],
        'manualPrice': value['manualPrice'],
        'quantity': value['quantity'],
        'reasonCode': value['reasonCode'],
        'serialNumbers': value['serialNumbers'],
    };
}

