/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Order API
 * API documentation for the Order service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApprovePriceOverrideRequest
 */
export interface ApprovePriceOverrideRequest {
    /**
     * 
     * @type {string}
     * @memberof ApprovePriceOverrideRequest
     */
    comments?: string;
}

/**
 * Check if a given object implements the ApprovePriceOverrideRequest interface.
 */
export function instanceOfApprovePriceOverrideRequest(value: object): boolean {
    return true;
}

export function ApprovePriceOverrideRequestFromJSON(json: any): ApprovePriceOverrideRequest {
    return ApprovePriceOverrideRequestFromJSONTyped(json, false);
}

export function ApprovePriceOverrideRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApprovePriceOverrideRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'comments': json['comments'] == null ? undefined : json['comments'],
    };
}

export function ApprovePriceOverrideRequestToJSON(value?: ApprovePriceOverrideRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'comments': value['comments'],
    };
}

