/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Order API
 * API documentation for the Order service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One returned line
 * @export
 * @interface Line
 */
export interface Line {
    /**
     * 
     * @type {string}
     * @memberof Line
     */
    condition?: string;
    /**
     * 
     * @type {string}
     * @memberof Line
     */
    itemSku?: string;
    /**
     * 
     * @type {number}
     * @memberof Line
     */
    lineRefund?: number;
    /**
     * 
     * @type {string}
     * @memberof Line
     */
    originalOrderLineId?: string;
    /**
     * 
     * @type {string}
     * @memberof Line
     */
    returnLineId?: string;
    /**
     * 
     * @type {number}
     * @memberof Line
     */
    returnQty?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Line
     */
    serialNumbers?: Array<string>;
}

/**
 * Check if a given object implements the Line interface.
 */
export function instanceOfLine(value: object): boolean {
    return true;
}

export function LineFromJSON(json: any): Line {
    return LineFromJSONTyped(json, false);
}

export function LineFromJSONTyped(json: any, ignoreDiscriminator: boolean): Line {
    if (json == null) {
        return json;
    }
    return {
        
        'condition': json['condition'] == null ? undefined : json['condition'],
        'itemSku': json['itemSku'] == null ? undefined : json['itemSku'],
        'lineRefund': json['lineRefund'] == null ? undefined : json['lineRefund'],
        'originalOrderLineId': json['originalOrderLineId'] == null ? undefined : json['originalOrderLineId'],
        'returnLineId': json['returnLineId'] == null ? undefined : json['returnLineId'],
        'returnQty': json['returnQty'] == null ? undefined : json['returnQty'],
        'serialNumbers': json['serialNumbers'] == null ? undefined : json['serialNumbers'],
    };
}

export function LineToJSON(value?: Line | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'condition': value['condition'],
        'itemSku': value['itemSku'],
        'lineRefund': value['lineRefund'],
        'originalOrderLineId': value['originalOrderLineId'],
        'returnLineId': value['returnLineId'],
        'returnQty': value['returnQty'],
        'serialNumbers': value['serialNumbers'],
    };
}

