/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Order API
 * API documentation for the Order service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Change } from './Change';
import {
    ChangeFromJSON,
    ChangeFromJSONTyped,
    ChangeToJSON,
} from './Change';
import type { TypePolicy } from './TypePolicy';
import {
    TypePolicyFromJSON,
    TypePolicyFromJSONTyped,
    TypePolicyToJSON,
} from './TypePolicy';

/**
 * The tenant's drawer policy: allowed and cashier limit per movement type, tolerance and history
 * @export
 * @interface SessionPolicyResponse
 */
export interface SessionPolicyResponse {
    /**
     * ISO 4217 code of the limits and the tolerance: the functional currency
     * @type {string}
     * @memberof SessionPolicyResponse
     */
    currencyCode?: string;
    /**
     * Every change, newest first
     * @type {Array<Change>}
     * @memberof SessionPolicyResponse
     */
    history?: Array<Change>;
    /**
     * Over/short above which a close needs order:session:approve_variance
     * @type {number}
     * @memberof SessionPolicyResponse
     */
    overShortTolerance?: number;
    /**
     * One row per movement type; only PETTY_EXPENSE and VENDOR_COD are editable
     * @type {Array<TypePolicy>}
     * @memberof SessionPolicyResponse
     */
    types?: Array<TypePolicy>;
    /**
     * The stored policy's version; null while the defaults apply
     * @type {number}
     * @memberof SessionPolicyResponse
     */
    version?: number;
}

/**
 * Check if a given object implements the SessionPolicyResponse interface.
 */
export function instanceOfSessionPolicyResponse(value: object): boolean {
    return true;
}

export function SessionPolicyResponseFromJSON(json: any): SessionPolicyResponse {
    return SessionPolicyResponseFromJSONTyped(json, false);
}

export function SessionPolicyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionPolicyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'currencyCode': json['currencyCode'] == null ? undefined : json['currencyCode'],
        'history': json['history'] == null ? undefined : ((json['history'] as Array<any>).map(ChangeFromJSON)),
        'overShortTolerance': json['overShortTolerance'] == null ? undefined : json['overShortTolerance'],
        'types': json['types'] == null ? undefined : ((json['types'] as Array<any>).map(TypePolicyFromJSON)),
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function SessionPolicyResponseToJSON(value?: SessionPolicyResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'currencyCode': value['currencyCode'],
        'history': value['history'] == null ? undefined : ((value['history'] as Array<any>).map(ChangeToJSON)),
        'overShortTolerance': value['overShortTolerance'],
        'types': value['types'] == null ? undefined : ((value['types'] as Array<any>).map(TypePolicyToJSON)),
        'version': value['version'],
    };
}

