/* tslint:disable */
/* eslint-disable */
/**
 * POS Security Service API
 * API documentation for POS Security Service
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  LoginRequest,
  SelfRegistrationRequest,
  SelfRegistrationResponse,
  TokenPairResponse,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    SelfRegistrationRequestFromJSON,
    SelfRegistrationRequestToJSON,
    SelfRegistrationResponseFromJSON,
    SelfRegistrationResponseToJSON,
    TokenPairResponseFromJSON,
    TokenPairResponseToJSON,
} from '../models/index';

export interface LoginOperationRequest {
    loginRequest: LoginRequest;
}

export interface SelfRegisterRequest {
    selfRegistrationRequest: SelfRegistrationRequest;
}

/**
 * 
 */
export class AuthAPIApi extends runtime.BaseAPI {

    /**
     * Authenticates a user with username and password and returns a JWT token pair.
     * User login
     */
    async loginRaw(requestParameters: LoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenPairResponse>> {
        if (requestParameters['loginRequest'] == null) {
            throw new runtime.RequiredError(
                'loginRequest',
                'Required parameter "loginRequest" was null or undefined when calling login().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenPairResponseFromJSON(jsonValue));
    }

    /**
     * Authenticates a user with username and password and returns a JWT token pair.
     * User login
     */
    async login(requestParameters: LoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenPairResponse> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a low-privilege customer account after resolving or creating a linked person record. Successful registration requires a follow-up login and does not issue tokens immediately. Conflict responses include operator guidance for recovery, linked-account, and CRM identity-review cases.
     * Self-register a new user
     */
    async selfRegisterRaw(requestParameters: SelfRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SelfRegistrationResponse>> {
        if (requestParameters['selfRegistrationRequest'] == null) {
            throw new runtime.RequiredError(
                'selfRegistrationRequest',
                'Required parameter "selfRegistrationRequest" was null or undefined when calling selfRegister().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/auth/self-register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SelfRegistrationRequestToJSON(requestParameters['selfRegistrationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SelfRegistrationResponseFromJSON(jsonValue));
    }

    /**
     * Creates a low-privilege customer account after resolving or creating a linked person record. Successful registration requires a follow-up login and does not issue tokens immediately. Conflict responses include operator guidance for recovery, linked-account, and CRM identity-review cases.
     * Self-register a new user
     */
    async selfRegister(requestParameters: SelfRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SelfRegistrationResponse> {
        const response = await this.selfRegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
