/* tslint:disable */
/* eslint-disable */
/**
 * Warranty API
 * API for warranty policies, claims, settlements, reimbursements, and part returns in the POS system
 *
 * The version of the OpenAPI document: 1.0
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ReimbursementResponse,
  ReimbursementSubmitRequest,
  ReimbursementUpdateRequest,
} from '../models/index';
import {
    ReimbursementResponseFromJSON,
    ReimbursementResponseToJSON,
    ReimbursementSubmitRequestFromJSON,
    ReimbursementSubmitRequestToJSON,
    ReimbursementUpdateRequestFromJSON,
    ReimbursementUpdateRequestToJSON,
} from '../models/index';

export interface ListReimbursementsRequest {
    status?: ListReimbursementsStatusEnum;
    providerId?: string;
}

export interface SubmitReimbursementRequest {
    id: string;
    reimbursementSubmitRequest: ReimbursementSubmitRequest;
}

export interface UpdateReimbursementRequest {
    id: string;
    reimbursementUpdateRequest: ReimbursementUpdateRequest;
}

/**
 * 
 */
export class WarrantyReimbursementsApi extends runtime.BaseAPI {

    /**
     * Returns the back-office worklist of vendor reimbursements across all claims, optionally filtered by status and provider. Use this tool to work open vendor credits; use getClaim instead to see the reimbursement of one specific claim. Preconditions: none — an empty list is returned when nothing matches. Required inputs: status and providerId are optional query parameters and combine as AND when both are given; omitting both returns every reimbursement. No events are emitted and no state changes; this is a read-only projection. Returns 200 with the list, which is empty rather than 404 when nothing matches. 
     * Reimbursement worklist
     */
    async listReimbursementsRaw(requestParameters: ListReimbursementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ReimbursementResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['providerId'] != null) {
            queryParameters['providerId'] = requestParameters['providerId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/warranty/reimbursements`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReimbursementResponseFromJSON));
    }

    /**
     * Returns the back-office worklist of vendor reimbursements across all claims, optionally filtered by status and provider. Use this tool to work open vendor credits; use getClaim instead to see the reimbursement of one specific claim. Preconditions: none — an empty list is returned when nothing matches. Required inputs: status and providerId are optional query parameters and combine as AND when both are given; omitting both returns every reimbursement. No events are emitted and no state changes; this is a read-only projection. Returns 200 with the list, which is empty rather than 404 when nothing matches. 
     * Reimbursement worklist
     */
    async listReimbursements(requestParameters: ListReimbursementsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ReimbursementResponse>> {
        const response = await this.listReimbursementsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submits the claim\'s single vendor reimbursement to the warranty provider, creating the record if needed and moving it NOT_SUBMITTED to SUBMITTED. Use this tool for the back-office recovery step after the customer is settled; do not use updateReimbursement, which records the vendor\'s decision, credit receipt, or write-off on an already-submitted reimbursement. Preconditions: the claim must be APPROVED or SETTLED (settle-customer-first), must have a provider assigned, the provider must not be DEALER-funded (self-funded programs are NOT_APPLICABLE), and the reimbursement must still be NOT_SUBMITTED — each claim has at most one. Required inputs: claim id (UUID) as a path parameter and a body with amountRequested (positive decimal); vendorClaimReference and notes are optional. Emits a WARRANTY_REIMBURSEMENT_SUBMIT event and enqueues warranty.reimbursement.submitted so pos-accounting can expect the vendor credit; the claim\'s own status is never touched. Returns 404 when the claim or its provider cannot be resolved, and 409 when the claim state disallows submission, no provider is assigned, the provider is dealer-funded, or the reimbursement was already submitted (including a concurrent submit). 
     * Submit vendor reimbursement
     */
    async submitReimbursementRaw(requestParameters: SubmitReimbursementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReimbursementResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling submitReimbursement().'
            );
        }

        if (requestParameters['reimbursementSubmitRequest'] == null) {
            throw new runtime.RequiredError(
                'reimbursementSubmitRequest',
                'Required parameter "reimbursementSubmitRequest" was null or undefined when calling submitReimbursement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/warranty/claims/{id}/reimbursement/submit`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReimbursementSubmitRequestToJSON(requestParameters['reimbursementSubmitRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReimbursementResponseFromJSON(jsonValue));
    }

    /**
     * Submits the claim\'s single vendor reimbursement to the warranty provider, creating the record if needed and moving it NOT_SUBMITTED to SUBMITTED. Use this tool for the back-office recovery step after the customer is settled; do not use updateReimbursement, which records the vendor\'s decision, credit receipt, or write-off on an already-submitted reimbursement. Preconditions: the claim must be APPROVED or SETTLED (settle-customer-first), must have a provider assigned, the provider must not be DEALER-funded (self-funded programs are NOT_APPLICABLE), and the reimbursement must still be NOT_SUBMITTED — each claim has at most one. Required inputs: claim id (UUID) as a path parameter and a body with amountRequested (positive decimal); vendorClaimReference and notes are optional. Emits a WARRANTY_REIMBURSEMENT_SUBMIT event and enqueues warranty.reimbursement.submitted so pos-accounting can expect the vendor credit; the claim\'s own status is never touched. Returns 404 when the claim or its provider cannot be resolved, and 409 when the claim state disallows submission, no provider is assigned, the provider is dealer-funded, or the reimbursement was already submitted (including a concurrent submit). 
     * Submit vendor reimbursement
     */
    async submitReimbursement(requestParameters: SubmitReimbursementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReimbursementResponse> {
        const response = await this.submitReimbursementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Records the vendor\'s resolution on a claim\'s reimbursement: a decision (APPROVED, PARTIALLY_APPROVED, DENIED), the credit receipt (CREDIT_RECEIVED), or a write-off (WRITTEN_OFF). Use this tool after the vendor responds; do not use submitReimbursement, which performs the initial NOT_SUBMITTED-to-SUBMITTED move. Preconditions: the claim must have a reimbursement record and the move must be legal in the child state machine — SUBMITTED may resolve to APPROVED, PARTIALLY_APPROVED, or DENIED, approvals may then move to CREDIT_RECEIVED, and any non-terminal state may be WRITTEN_OFF; DENIED, CREDIT_RECEIVED, WRITTEN_OFF, and NOT_APPLICABLE are terminal and unblock claim close. Required inputs: claim id (UUID) as a path parameter and a body with status; amountApproved is required for APPROVED and PARTIALLY_APPROVED, and creditReference typically accompanies CREDIT_RECEIVED. Emits a WARRANTY_REIMBURSEMENT_UPDATE event and enqueues warranty.reimbursement.resolved for every resolution status so pos-accounting can match or stop expecting the vendor credit. Returns 400 when the target status is outside the updatable set or amountApproved is missing, 404 when the claim or its reimbursement record does not exist, and 409 when the transition is illegal from the current status (nextAction lists the legal moves). 
     * Update vendor reimbursement
     */
    async updateReimbursementRaw(requestParameters: UpdateReimbursementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReimbursementResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateReimbursement().'
            );
        }

        if (requestParameters['reimbursementUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'reimbursementUpdateRequest',
                'Required parameter "reimbursementUpdateRequest" was null or undefined when calling updateReimbursement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/warranty/claims/{id}/reimbursement`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ReimbursementUpdateRequestToJSON(requestParameters['reimbursementUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReimbursementResponseFromJSON(jsonValue));
    }

    /**
     * Records the vendor\'s resolution on a claim\'s reimbursement: a decision (APPROVED, PARTIALLY_APPROVED, DENIED), the credit receipt (CREDIT_RECEIVED), or a write-off (WRITTEN_OFF). Use this tool after the vendor responds; do not use submitReimbursement, which performs the initial NOT_SUBMITTED-to-SUBMITTED move. Preconditions: the claim must have a reimbursement record and the move must be legal in the child state machine — SUBMITTED may resolve to APPROVED, PARTIALLY_APPROVED, or DENIED, approvals may then move to CREDIT_RECEIVED, and any non-terminal state may be WRITTEN_OFF; DENIED, CREDIT_RECEIVED, WRITTEN_OFF, and NOT_APPLICABLE are terminal and unblock claim close. Required inputs: claim id (UUID) as a path parameter and a body with status; amountApproved is required for APPROVED and PARTIALLY_APPROVED, and creditReference typically accompanies CREDIT_RECEIVED. Emits a WARRANTY_REIMBURSEMENT_UPDATE event and enqueues warranty.reimbursement.resolved for every resolution status so pos-accounting can match or stop expecting the vendor credit. Returns 400 when the target status is outside the updatable set or amountApproved is missing, 404 when the claim or its reimbursement record does not exist, and 409 when the transition is illegal from the current status (nextAction lists the legal moves). 
     * Update vendor reimbursement
     */
    async updateReimbursement(requestParameters: UpdateReimbursementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReimbursementResponse> {
        const response = await this.updateReimbursementRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum ListReimbursementsStatusEnum {
    NotSubmitted = 'NOT_SUBMITTED',
    Submitted = 'SUBMITTED',
    Approved = 'APPROVED',
    PartiallyApproved = 'PARTIALLY_APPROVED',
    Denied = 'DENIED',
    CreditReceived = 'CREDIT_RECEIVED',
    WrittenOff = 'WRITTEN_OFF',
    NotApplicable = 'NOT_APPLICABLE'
}
