/* tslint:disable */
/* eslint-disable */
/**
 * Warranty API
 * API for warranty policies, claims, settlements, reimbursements, and part returns in the POS system
 *
 * The version of the OpenAPI document: 1.0
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Warranty claim line — one failed part or service, with source provenance and snapshots
 * @export
 * @interface ClaimLineRequest
 */
export interface ClaimLineRequest {
    /**
     * Line description snapshot
     * @type {string}
     * @memberof ClaimLineRequest
     */
    description?: string;
    /**
     * Tire DOT number
     * @type {string}
     * @memberof ClaimLineRequest
     */
    dotNumber?: string;
    /**
     * Measured remaining tread depth in 32nds of an inch
     * @type {number}
     * @memberof ClaimLineRequest
     */
    measuredTreadDepth?: number;
    /**
     * Original tread depth in 32nds of an inch
     * @type {number}
     * @memberof ClaimLineRequest
     */
    originalTreadDepth?: number;
    /**
     * Original unit price snapshot
     * @type {number}
     * @memberof ClaimLineRequest
     */
    originalUnitPrice?: number;
    /**
     * pos-catalog product id, when known
     * @type {string}
     * @memberof ClaimLineRequest
     */
    productEntityId?: string;
    /**
     * Quantity claimed; defaults to 1
     * @type {number}
     * @memberof ClaimLineRequest
     */
    quantity?: number;
    /**
     * Serial number of the failed unit
     * @type {string}
     * @memberof ClaimLineRequest
     */
    serialNumber?: string;
    /**
     * Catalog SKU snapshot
     * @type {string}
     * @memberof ClaimLineRequest
     */
    sku?: string;
    /**
     * Originating invoice or workorder id (null for MANUAL lines)
     * @type {string}
     * @memberof ClaimLineRequest
     */
    sourceId?: string;
    /**
     * Originating invoice/workorder line id (null for MANUAL lines)
     * @type {string}
     * @memberof ClaimLineRequest
     */
    sourceLineId?: string;
    /**
     * Provenance of the line
     * @type {string}
     * @memberof ClaimLineRequest
     */
    sourceType: ClaimLineRequestSourceTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum ClaimLineRequestSourceTypeEnum {
    InvoiceLine = 'INVOICE_LINE',
    WorkorderPart = 'WORKORDER_PART',
    WorkorderService = 'WORKORDER_SERVICE',
    Manual = 'MANUAL'
}


/**
 * Check if a given object implements the ClaimLineRequest interface.
 */
export function instanceOfClaimLineRequest(value: object): boolean {
    if (!('sourceType' in value)) return false;
    return true;
}

export function ClaimLineRequestFromJSON(json: any): ClaimLineRequest {
    return ClaimLineRequestFromJSONTyped(json, false);
}

export function ClaimLineRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimLineRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'dotNumber': json['dotNumber'] == null ? undefined : json['dotNumber'],
        'measuredTreadDepth': json['measuredTreadDepth'] == null ? undefined : json['measuredTreadDepth'],
        'originalTreadDepth': json['originalTreadDepth'] == null ? undefined : json['originalTreadDepth'],
        'originalUnitPrice': json['originalUnitPrice'] == null ? undefined : json['originalUnitPrice'],
        'productEntityId': json['productEntityId'] == null ? undefined : json['productEntityId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'serialNumber': json['serialNumber'] == null ? undefined : json['serialNumber'],
        'sku': json['sku'] == null ? undefined : json['sku'],
        'sourceId': json['sourceId'] == null ? undefined : json['sourceId'],
        'sourceLineId': json['sourceLineId'] == null ? undefined : json['sourceLineId'],
        'sourceType': json['sourceType'],
    };
}

export function ClaimLineRequestToJSON(value?: ClaimLineRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'dotNumber': value['dotNumber'],
        'measuredTreadDepth': value['measuredTreadDepth'],
        'originalTreadDepth': value['originalTreadDepth'],
        'originalUnitPrice': value['originalUnitPrice'],
        'productEntityId': value['productEntityId'],
        'quantity': value['quantity'],
        'serialNumber': value['serialNumber'],
        'sku': value['sku'],
        'sourceId': value['sourceId'],
        'sourceLineId': value['sourceLineId'],
        'sourceType': value['sourceType'],
    };
}

