/* tslint:disable */
/* eslint-disable */
/**
 * POS People Contact Service API
 * Identity, contact, and user-link authority service (ADR-0044 Phase 3)
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User role assignment as exposed by the security service
 * @export
 * @interface UserRoleDto
 */
export interface UserRoleDto {
    /**
     * Whether the assignment is active
     * @type {boolean}
     * @memberof UserRoleDto
     */
    active?: boolean;
    /**
     * Exclusive end of the effective window
     * @type {Date}
     * @memberof UserRoleDto
     */
    endDate?: Date;
    /**
     * Stable role code
     * @type {string}
     * @memberof UserRoleDto
     */
    roleCode?: string;
    /**
     * Inclusive start of the effective window
     * @type {Date}
     * @memberof UserRoleDto
     */
    startDate?: Date;
    /**
     * User identifier
     * @type {string}
     * @memberof UserRoleDto
     */
    userId?: string;
}

/**
 * Check if a given object implements the UserRoleDto interface.
 */
export function instanceOfUserRoleDto(value: object): boolean {
    return true;
}

export function UserRoleDtoFromJSON(json: any): UserRoleDto {
    return UserRoleDtoFromJSONTyped(json, false);
}

export function UserRoleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoleDto {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : json['active'],
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'roleCode': json['roleCode'] == null ? undefined : json['roleCode'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function UserRoleDtoToJSON(value?: UserRoleDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'active': value['active'],
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString()),
        'roleCode': value['roleCode'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString()),
        'userId': value['userId'],
    };
}

