"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Location API
 * API documentation for the Shop Location service, accessible via the API Gateway. Shop locations are Maintenance Bays and Mobile Shops.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.LocationAPIApi = void 0;
const runtime = __importStar(require("../runtime"));
const index_1 = require("../models/index");
/**
 *
 */
class LocationAPIApi extends runtime.BaseAPI {
    /**
     * Add a parent relationship to a location.
     * Add a parent to a location
     */
    async addParentRaw(requestParameters, initOverrides) {
        if (requestParameters['childId'] == null) {
            throw new runtime.RequiredError('childId', 'Required parameter "childId" was null or undefined when calling addParent().');
        }
        if (requestParameters['parentId'] == null) {
            throw new runtime.RequiredError('parentId', 'Required parameter "parentId" was null or undefined when calling addParent().');
        }
        if (requestParameters['parentType'] == null) {
            throw new runtime.RequiredError('parentType', 'Required parameter "parentType" was null or undefined when calling addParent().');
        }
        const queryParameters = {};
        if (requestParameters['parentType'] != null) {
            queryParameters['parentType'] = requestParameters['parentType'];
        }
        const headerParameters = {};
        const response = await this.request({
            path: `/v1/locations/{childId}/parents/{parentId}`.replace(`{${"childId"}}`, encodeURIComponent(String(requestParameters['childId']))).replace(`{${"parentId"}}`, encodeURIComponent(String(requestParameters['parentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.LocationParentResponseDTOFromJSON)(jsonValue));
    }
    /**
     * Add a parent relationship to a location.
     * Add a parent to a location
     */
    async addParent(requestParameters, initOverrides) {
        const response = await this.addParentRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Add a new location to the system.
     * Create a new location
     */
    async createLocationRaw(requestParameters, initOverrides) {
        if (requestParameters['locationRequestDTO'] == null) {
            throw new runtime.RequiredError('locationRequestDTO', 'Required parameter "locationRequestDTO" was null or undefined when calling createLocation().');
        }
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        const response = await this.request({
            path: `/v1/locations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: (0, index_1.LocationRequestDTOToJSON)(requestParameters['locationRequestDTO']),
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.LocationResponseDTOFromJSON)(jsonValue));
    }
    /**
     * Add a new location to the system.
     * Create a new location
     */
    async createLocation(requestParameters, initOverrides) {
        const response = await this.createLocationRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Delete a location by its unique ID.
     * Delete a location
     */
    async deleteLocationRaw(requestParameters, initOverrides) {
        if (requestParameters['locationId'] == null) {
            throw new runtime.RequiredError('locationId', 'Required parameter "locationId" was null or undefined when calling deleteLocation().');
        }
        const queryParameters = {};
        const headerParameters = {};
        const response = await this.request({
            path: `/v1/locations/{locationId}`.replace(`{${"locationId"}}`, encodeURIComponent(String(requestParameters['locationId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.VoidApiResponse(response);
    }
    /**
     * Delete a location by its unique ID.
     * Delete a location
     */
    async deleteLocation(requestParameters, initOverrides) {
        await this.deleteLocationRaw(requestParameters, initOverrides);
    }
    /**
     * Retrieve all child locations for a given parent location.
     * Get all children for a location
     */
    async getAllChildrenRaw(requestParameters, initOverrides) {
        if (requestParameters['locationId'] == null) {
            throw new runtime.RequiredError('locationId', 'Required parameter "locationId" was null or undefined when calling getAllChildren().');
        }
        const queryParameters = {};
        if (requestParameters['parentType'] != null) {
            queryParameters['parentType'] = requestParameters['parentType'];
        }
        const headerParameters = {};
        const response = await this.request({
            path: `/v1/locations/{locationId}/children`.replace(`{${"locationId"}}`, encodeURIComponent(String(requestParameters['locationId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(index_1.LocationResponseDTOFromJSON));
    }
    /**
     * Retrieve all child locations for a given parent location.
     * Get all children for a location
     */
    async getAllChildren(requestParameters, initOverrides) {
        const response = await this.getAllChildrenRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Retrieve a list of all locations.
     * Get all locations
     */
    async getAllLocationsRaw(initOverrides) {
        const queryParameters = {};
        const headerParameters = {};
        const response = await this.request({
            path: `/v1/locations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(index_1.LocationResponseDTOFromJSON));
    }
    /**
     * Retrieve a list of all locations.
     * Get all locations
     */
    async getAllLocations(initOverrides) {
        const response = await this.getAllLocationsRaw(initOverrides);
        return await response.value();
    }
    /**
     * Retrieve all parent relationships for locations.
     * Get all location parents
     */
    async getAllParentsRaw(initOverrides) {
        const queryParameters = {};
        const headerParameters = {};
        const response = await this.request({
            path: `/v1/locations/parents`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(index_1.LocationParentResponseDTOFromJSON));
    }
    /**
     * Retrieve all parent relationships for locations.
     * Get all location parents
     */
    async getAllParents(initOverrides) {
        const response = await this.getAllParentsRaw(initOverrides);
        return await response.value();
    }
    /**
     * Retrieve a location by its unique ID.
     * Get location by ID
     */
    async getLocationByIdRaw(requestParameters, initOverrides) {
        if (requestParameters['locationId'] == null) {
            throw new runtime.RequiredError('locationId', 'Required parameter "locationId" was null or undefined when calling getLocationById().');
        }
        const queryParameters = {};
        const headerParameters = {};
        const response = await this.request({
            path: `/v1/locations/{locationId}`.replace(`{${"locationId"}}`, encodeURIComponent(String(requestParameters['locationId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.LocationResponseDTOFromJSON)(jsonValue));
    }
    /**
     * Retrieve a location by its unique ID.
     * Get location by ID
     */
    async getLocationById(requestParameters, initOverrides) {
        const response = await this.getLocationByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Retrieve the person responsible for a given location.
     * Get responsible person for a location
     */
    async getResponsiblePersonRaw(requestParameters, initOverrides) {
        if (requestParameters['locationId'] == null) {
            throw new runtime.RequiredError('locationId', 'Required parameter "locationId" was null or undefined when calling getResponsiblePerson().');
        }
        const queryParameters = {};
        const headerParameters = {};
        const response = await this.request({
            path: `/v1/locations/{locationId}/responsible-person`.replace(`{${"locationId"}}`, encodeURIComponent(String(requestParameters['locationId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.PersonDTOFromJSON)(jsonValue));
    }
    /**
     * Retrieve the person responsible for a given location.
     * Get responsible person for a location
     */
    async getResponsiblePerson(requestParameters, initOverrides) {
        const response = await this.getResponsiblePersonRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Retrieve paginated location refs for sync consumers.
     * Get location roster
     */
    async getRosterRaw(requestParameters, initOverrides) {
        if (requestParameters['pageable'] == null) {
            throw new runtime.RequiredError('pageable', 'Required parameter "pageable" was null or undefined when calling getRoster().');
        }
        const queryParameters = {};
        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }
        if (requestParameters['sinceUpdatedAt'] != null) {
            queryParameters['sinceUpdatedAt'] = requestParameters['sinceUpdatedAt'].toISOString();
        }
        if (requestParameters['pageable'] != null) {
            queryParameters['pageable'] = requestParameters['pageable'];
        }
        const headerParameters = {};
        const response = await this.request({
            path: `/v1/locations/roster`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.PageLocationRefFromJSON)(jsonValue));
    }
    /**
     * Retrieve paginated location refs for sync consumers.
     * Get location roster
     */
    async getRoster(requestParameters, initOverrides) {
        const response = await this.getRosterRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Patch selected fields for a location.
     * Patch a location
     */
    async patchLocationRaw(requestParameters, initOverrides) {
        if (requestParameters['locationId'] == null) {
            throw new runtime.RequiredError('locationId', 'Required parameter "locationId" was null or undefined when calling patchLocation().');
        }
        if (requestParameters['locationPatchRequest'] == null) {
            throw new runtime.RequiredError('locationPatchRequest', 'Required parameter "locationPatchRequest" was null or undefined when calling patchLocation().');
        }
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        const response = await this.request({
            path: `/v1/locations/{locationId}`.replace(`{${"locationId"}}`, encodeURIComponent(String(requestParameters['locationId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: (0, index_1.LocationPatchRequestToJSON)(requestParameters['locationPatchRequest']),
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.LocationResponseDTOFromJSON)(jsonValue));
    }
    /**
     * Patch selected fields for a location.
     * Patch a location
     */
    async patchLocation(requestParameters, initOverrides) {
        const response = await this.patchLocationRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Update the details of an existing location.
     * Update an existing location
     */
    async updateLocationRaw(requestParameters, initOverrides) {
        if (requestParameters['locationId'] == null) {
            throw new runtime.RequiredError('locationId', 'Required parameter "locationId" was null or undefined when calling updateLocation().');
        }
        if (requestParameters['locationRequestDTO'] == null) {
            throw new runtime.RequiredError('locationRequestDTO', 'Required parameter "locationRequestDTO" was null or undefined when calling updateLocation().');
        }
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        const response = await this.request({
            path: `/v1/locations/{locationId}`.replace(`{${"locationId"}}`, encodeURIComponent(String(requestParameters['locationId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: (0, index_1.LocationRequestDTOToJSON)(requestParameters['locationRequestDTO']),
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.LocationResponseDTOFromJSON)(jsonValue));
    }
    /**
     * Update the details of an existing location.
     * Update an existing location
     */
    async updateLocation(requestParameters, initOverrides) {
        const response = await this.updateLocationRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Return existence and active state for a location ID.
     * Validate location reference
     */
    async validateLocationRaw(requestParameters, initOverrides) {
        if (requestParameters['locationId'] == null) {
            throw new runtime.RequiredError('locationId', 'Required parameter "locationId" was null or undefined when calling validateLocation().');
        }
        const queryParameters = {};
        const headerParameters = {};
        const response = await this.request({
            path: `/v1/locations/{locationId}/validation`.replace(`{${"locationId"}}`, encodeURIComponent(String(requestParameters['locationId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.LocationValidationResponseDTOFromJSON)(jsonValue));
    }
    /**
     * Return existence and active state for a location ID.
     * Validate location reference
     */
    async validateLocation(requestParameters, initOverrides) {
        const response = await this.validateLocationRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
exports.LocationAPIApi = LocationAPIApi;
