/**
 * Positivity Location API
 * API documentation for the Shop Location service, accessible via the API Gateway. Shop locations are Maintenance Bays and Mobile Shops.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { EligibleMobileUnitResponse } from '../models/index';
export interface FindEligibleMobileUnitsRequest {
    postalCode: string;
    countryCode: string;
    at: Date;
}
/**
 *
 */
export declare class MobileUnitEligibilityControllerApi extends runtime.BaseAPI {
    /**
     * Return eligible active units for a service request.
     * Find eligible mobile units
     */
    findEligibleMobileUnitsRaw(requestParameters: FindEligibleMobileUnitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EligibleMobileUnitResponse>>>;
    /**
     * Return eligible active units for a service request.
     * Find eligible mobile units
     */
    findEligibleMobileUnits(requestParameters: FindEligibleMobileUnitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EligibleMobileUnitResponse>>;
}
