/**
 * Positivity Location API
 * API documentation for the Shop Location service, accessible via the API Gateway. Shop locations are Maintenance Bays and Mobile Shops.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { CoverageRuleResponse, MobileUnitRequest, MobileUnitResponse, PageMobileUnitResponse } from '../models/index';
export interface CreateMobileUnitRequest {
    mobileUnitRequest: MobileUnitRequest;
}
export interface GetCoverageRulesRequest {
    id: string;
}
export interface GetMobileUnitByIdRequest {
    id: string;
}
export interface ListMobileUnitsRequest {
    page?: number;
    size?: number;
}
export interface PatchMobileUnitRequest {
    id: string;
    requestBody: {
        [key: string]: any;
    };
}
export interface ReplaceCoverageRulesRequest {
    id: string;
    requestBody: {
        [key: string]: any;
    };
}
/**
 *
 */
export declare class MobileUnitAPIApi extends runtime.BaseAPI {
    /**
     * Create a new mobile unit.
     * Create mobile unit
     */
    createMobileUnitRaw(requestParameters: CreateMobileUnitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MobileUnitResponse>>;
    /**
     * Create a new mobile unit.
     * Create mobile unit
     */
    createMobileUnit(requestParameters: CreateMobileUnitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MobileUnitResponse>;
    /**
     * Get coverage rules for a mobile unit.
     * Get coverage rules
     */
    getCoverageRulesRaw(requestParameters: GetCoverageRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CoverageRuleResponse>>>;
    /**
     * Get coverage rules for a mobile unit.
     * Get coverage rules
     */
    getCoverageRules(requestParameters: GetCoverageRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CoverageRuleResponse>>;
    /**
     * Get a mobile unit by ID.
     * Get mobile unit
     */
    getMobileUnitByIdRaw(requestParameters: GetMobileUnitByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MobileUnitResponse>>;
    /**
     * Get a mobile unit by ID.
     * Get mobile unit
     */
    getMobileUnitById(requestParameters: GetMobileUnitByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MobileUnitResponse>;
    /**
     * List mobile units with pagination.
     * List mobile units
     */
    listMobileUnitsRaw(requestParameters: ListMobileUnitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageMobileUnitResponse>>;
    /**
     * List mobile units with pagination.
     * List mobile units
     */
    listMobileUnits(requestParameters?: ListMobileUnitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageMobileUnitResponse>;
    /**
     * Partially update a mobile unit.
     * Patch mobile unit
     */
    patchMobileUnitRaw(requestParameters: PatchMobileUnitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MobileUnitResponse>>;
    /**
     * Partially update a mobile unit.
     * Patch mobile unit
     */
    patchMobileUnit(requestParameters: PatchMobileUnitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MobileUnitResponse>;
    /**
     * Atomically replace coverage rules for a mobile unit.
     * Replace coverage rules
     */
    replaceCoverageRulesRaw(requestParameters: ReplaceCoverageRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CoverageRuleResponse>>>;
    /**
     * Atomically replace coverage rules for a mobile unit.
     * Replace coverage rules
     */
    replaceCoverageRules(requestParameters: ReplaceCoverageRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CoverageRuleResponse>>;
}
