import { DurionSdkConfig } from '@durion-sdk/transport';
import * as GeneratedApis from './apis';
export declare function createInventoryClient(config: DurionSdkConfig): {
    asnApi: GeneratedApis.ASNApi;
    consumptionApi: GeneratedApis.ConsumptionApi;
    cycleCountAdjustmentsApi: GeneratedApis.CycleCountAdjustmentsApi;
    cycleCountOperationsApi: GeneratedApis.CycleCountOperationsApi;
    cycleCountPlansApi: GeneratedApis.CycleCountPlansApi;
    cycleCountQueryApi: GeneratedApis.CycleCountQueryApi;
    inventoryAvailabilityApi: GeneratedApis.InventoryAvailabilityApi;
    inventoryLocationsApi: GeneratedApis.InventoryLocationsApi;
    inventoryManagementApi: GeneratedApis.InventoryManagementApi;
    inventoryReservationsApi: GeneratedApis.InventoryReservationsApi;
    inventorySitesApi: GeneratedApis.InventorySitesApi;
    pickListsApi: GeneratedApis.PickListsApi;
    pickingListsApi: GeneratedApis.PickingListsApi;
    purchaseOrdersApi: GeneratedApis.PurchaseOrdersApi;
    putawayApi: GeneratedApis.PutawayApi;
    putawayExecutionApi: GeneratedApis.PutawayExecutionApi;
    reallocationApi: GeneratedApis.ReallocationApi;
    receivingApi: GeneratedApis.ReceivingApi;
    replenishmentApi: GeneratedApis.ReplenishmentApi;
    returnsApi: GeneratedApis.ReturnsApi;
    shortageResolutionApi: GeneratedApis.ShortageResolutionApi;
    stockMovementsApi: GeneratedApis.StockMovementsApi;
};
export { InventoryProcureToReceiveWorkflow } from './workflows/inventoryProcureToReceiveWorkflow';
export * from './runtime';
export * from './apis/index';
export * from './models/index';
