/* tslint:disable */
/* eslint-disable */
/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  GLAccountActivateRequest,
  GLAccountBalanceResponse,
  GLAccountCreateRequest,
  GLAccountListResponse,
  GLAccountResponse,
  GLAccountUpdateRequest,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    GLAccountActivateRequestFromJSON,
    GLAccountActivateRequestToJSON,
    GLAccountBalanceResponseFromJSON,
    GLAccountBalanceResponseToJSON,
    GLAccountCreateRequestFromJSON,
    GLAccountCreateRequestToJSON,
    GLAccountListResponseFromJSON,
    GLAccountListResponseToJSON,
    GLAccountResponseFromJSON,
    GLAccountResponseToJSON,
    GLAccountUpdateRequestFromJSON,
    GLAccountUpdateRequestToJSON,
} from '../models/index';

export interface ActivateGLAccountRequest {
    glAccountId: string;
    gLAccountActivateRequest: GLAccountActivateRequest;
}

export interface ArchiveGLAccountRequest {
    glAccountId: string;
    body?: object;
}

export interface CreateGLAccountRequest {
    gLAccountCreateRequest: GLAccountCreateRequest;
}

export interface DeactivateGLAccountRequest {
    glAccountId: string;
    body?: object;
}

export interface GetGLAccountRequest {
    glAccountId: string;
}

export interface GetGLAccountBalanceRequest {
    glAccountId: string;
}

export interface ListGLAccountsRequest {
    sort: string;
    page?: number;
    size?: number;
    status?: string;
}

export interface UpdateGLAccountRequest {
    glAccountId: string;
    gLAccountUpdateRequest: GLAccountUpdateRequest;
}

/**
 * 
 */
export class GLAccountsApi extends runtime.BaseAPI {

    /**
     * Activates a GL account for posting by setting its activation date to the start of the supplied effective date and clearing any deactivation date. Use this tool when re-enabling an inactive account or bringing a not-yet-active account into service; do not use deactivateGLAccount, which does the reverse. Preconditions: the GL account must exist; activation is idempotent and simply resets the effective dates. Required inputs: glAccountId (UUID) as a path parameter and effectiveDate (ISO date) in the body; the account becomes ACTIVE at start of day on that date. Emits an ACCOUNTING_GL_ACCOUNT_ACTIVATE event; no journal entries are created or altered. Returns 404 when no GL account exists for the supplied id. 
     * Activate GL Account
     */
    async activateGLAccountRaw(requestParameters: ActivateGLAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GLAccountResponse>> {
        if (requestParameters['glAccountId'] == null) {
            throw new runtime.RequiredError(
                'glAccountId',
                'Required parameter "glAccountId" was null or undefined when calling activateGLAccount().'
            );
        }

        if (requestParameters['gLAccountActivateRequest'] == null) {
            throw new runtime.RequiredError(
                'gLAccountActivateRequest',
                'Required parameter "gLAccountActivateRequest" was null or undefined when calling activateGLAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["accounting:coa:edit"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/accounting/gl-accounts/{glAccountId}/activate`.replace(`{${"glAccountId"}}`, encodeURIComponent(String(requestParameters['glAccountId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GLAccountActivateRequestToJSON(requestParameters['gLAccountActivateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GLAccountResponseFromJSON(jsonValue));
    }

    /**
     * Activates a GL account for posting by setting its activation date to the start of the supplied effective date and clearing any deactivation date. Use this tool when re-enabling an inactive account or bringing a not-yet-active account into service; do not use deactivateGLAccount, which does the reverse. Preconditions: the GL account must exist; activation is idempotent and simply resets the effective dates. Required inputs: glAccountId (UUID) as a path parameter and effectiveDate (ISO date) in the body; the account becomes ACTIVE at start of day on that date. Emits an ACCOUNTING_GL_ACCOUNT_ACTIVATE event; no journal entries are created or altered. Returns 404 when no GL account exists for the supplied id. 
     * Activate GL Account
     */
    async activateGLAccount(requestParameters: ActivateGLAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GLAccountResponse> {
        const response = await this.activateGLAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Archives an inactive GL account as a soft delete, tagging it [ARCHIVED] while keeping the record and its posting history. Use this tool only after deactivateGLAccount has succeeded; do not use it on an ACTIVE account, which must be deactivated to zero balance first. Preconditions: the GL account must exist and its derived status must be INACTIVE. Required inputs: glAccountId (UUID) as a path parameter; the request body is optional and ignored. Emits an ACCOUNTING_GL_ACCOUNT_ARCHIVE event; the row is never physically deleted. Returns 404 when no GL account exists for the supplied id, and 409 ACCOUNT_NOT_INACTIVE when the account is not INACTIVE. 
     * Archive GL Account
     */
    async archiveGLAccountRaw(requestParameters: ArchiveGLAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GLAccountResponse>> {
        if (requestParameters['glAccountId'] == null) {
            throw new runtime.RequiredError(
                'glAccountId',
                'Required parameter "glAccountId" was null or undefined when calling archiveGLAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["accounting:coa:deactivate"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/accounting/gl-accounts/{glAccountId}/archive`.replace(`{${"glAccountId"}}`, encodeURIComponent(String(requestParameters['glAccountId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GLAccountResponseFromJSON(jsonValue));
    }

    /**
     * Archives an inactive GL account as a soft delete, tagging it [ARCHIVED] while keeping the record and its posting history. Use this tool only after deactivateGLAccount has succeeded; do not use it on an ACTIVE account, which must be deactivated to zero balance first. Preconditions: the GL account must exist and its derived status must be INACTIVE. Required inputs: glAccountId (UUID) as a path parameter; the request body is optional and ignored. Emits an ACCOUNTING_GL_ACCOUNT_ARCHIVE event; the row is never physically deleted. Returns 404 when no GL account exists for the supplied id, and 409 ACCOUNT_NOT_INACTIVE when the account is not INACTIVE. 
     * Archive GL Account
     */
    async archiveGLAccount(requestParameters: ArchiveGLAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GLAccountResponse> {
        const response = await this.archiveGLAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a GL account in the chart of accounts with a unique account code, classification and activation date. Use this tool when adding a new account to the chart; do not use updateGLAccount, which edits the mutable fields of an account that already exists. Preconditions: no account may already exist with the same accountCode; a parentAccountId, when supplied, must reference an existing account. Required inputs: accountCode (pattern #### or ####-###), accountName, accountType (ASSET, LIABILITY, EQUITY, REVENUE or EXPENSE) and activationDate; accountSubtype, description and parentAccountId are optional, and reconcilable defaults to false. Emits an ACCOUNTING_GL_ACCOUNT_CREATE event; the account code and type are immutable after creation. Returns 409 when the account code already exists, and 400 when the parent account cannot be resolved. 
     * Create GL Account
     */
    async createGLAccountRaw(requestParameters: CreateGLAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GLAccountResponse>> {
        if (requestParameters['gLAccountCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'gLAccountCreateRequest',
                'Required parameter "gLAccountCreateRequest" was null or undefined when calling createGLAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["accounting:coa:create"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/accounting/gl-accounts`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GLAccountCreateRequestToJSON(requestParameters['gLAccountCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GLAccountResponseFromJSON(jsonValue));
    }

    /**
     * Creates a GL account in the chart of accounts with a unique account code, classification and activation date. Use this tool when adding a new account to the chart; do not use updateGLAccount, which edits the mutable fields of an account that already exists. Preconditions: no account may already exist with the same accountCode; a parentAccountId, when supplied, must reference an existing account. Required inputs: accountCode (pattern #### or ####-###), accountName, accountType (ASSET, LIABILITY, EQUITY, REVENUE or EXPENSE) and activationDate; accountSubtype, description and parentAccountId are optional, and reconcilable defaults to false. Emits an ACCOUNTING_GL_ACCOUNT_CREATE event; the account code and type are immutable after creation. Returns 409 when the account code already exists, and 400 when the parent account cannot be resolved. 
     * Create GL Account
     */
    async createGLAccount(requestParameters: CreateGLAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GLAccountResponse> {
        const response = await this.createGLAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deactivates a GL account by stamping its deactivation date now, preventing future postings to it. Use this tool when retiring an account from active use; do not use archiveGLAccount, which additionally flags an already-INACTIVE account as archived, and do not use it while the account still carries a balance. Preconditions: the GL account must exist and its posted balance must be exactly zero. Required inputs: glAccountId (UUID) as a path parameter; the request body is optional and ignored. Emits an ACCOUNTING_GL_ACCOUNT_DEACTIVATE event; historical journal entries remain intact. Returns 404 when no GL account exists for the supplied id, and 409 ACCOUNT_NOT_ZERO_BALANCE when the account balance is not zero. 
     * Deactivate GL Account
     */
    async deactivateGLAccountRaw(requestParameters: DeactivateGLAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GLAccountResponse>> {
        if (requestParameters['glAccountId'] == null) {
            throw new runtime.RequiredError(
                'glAccountId',
                'Required parameter "glAccountId" was null or undefined when calling deactivateGLAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["accounting:coa:deactivate"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/accounting/gl-accounts/{glAccountId}/deactivate`.replace(`{${"glAccountId"}}`, encodeURIComponent(String(requestParameters['glAccountId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GLAccountResponseFromJSON(jsonValue));
    }

    /**
     * Deactivates a GL account by stamping its deactivation date now, preventing future postings to it. Use this tool when retiring an account from active use; do not use archiveGLAccount, which additionally flags an already-INACTIVE account as archived, and do not use it while the account still carries a balance. Preconditions: the GL account must exist and its posted balance must be exactly zero. Required inputs: glAccountId (UUID) as a path parameter; the request body is optional and ignored. Emits an ACCOUNTING_GL_ACCOUNT_DEACTIVATE event; historical journal entries remain intact. Returns 404 when no GL account exists for the supplied id, and 409 ACCOUNT_NOT_ZERO_BALANCE when the account balance is not zero. 
     * Deactivate GL Account
     */
    async deactivateGLAccount(requestParameters: DeactivateGLAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GLAccountResponse> {
        const response = await this.deactivateGLAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns one GL account with its code, name, type, subtype, reconcilable flag and derived lifecycle status. Use this tool when the GL account id is already known; use listGLAccounts instead when searching by code, name or status. Preconditions: the GL account must exist. Required inputs: glAccountId (UUID) as a path parameter; there is no request body. No events are emitted and no state changes; this is a read-only projection. Returns 404 when no GL account exists for the supplied id. 
     * Get GL Account
     */
    async getGLAccountRaw(requestParameters: GetGLAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GLAccountResponse>> {
        if (requestParameters['glAccountId'] == null) {
            throw new runtime.RequiredError(
                'glAccountId',
                'Required parameter "glAccountId" was null or undefined when calling getGLAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["accounting:coa:view"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/accounting/gl-accounts/{glAccountId}`.replace(`{${"glAccountId"}}`, encodeURIComponent(String(requestParameters['glAccountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GLAccountResponseFromJSON(jsonValue));
    }

    /**
     * Returns one GL account with its code, name, type, subtype, reconcilable flag and derived lifecycle status. Use this tool when the GL account id is already known; use listGLAccounts instead when searching by code, name or status. Preconditions: the GL account must exist. Required inputs: glAccountId (UUID) as a path parameter; there is no request body. No events are emitted and no state changes; this is a read-only projection. Returns 404 when no GL account exists for the supplied id. 
     * Get GL Account
     */
    async getGLAccount(requestParameters: GetGLAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GLAccountResponse> {
        const response = await this.getGLAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the current posted balance of one GL account, computed from its journal entry lines. Use this tool for a single account\'s balance; use the trial balance report in financial reporting instead when balances for the whole chart are needed. Preconditions: the GL account must exist; an account with no postings reports a zero balance. Required inputs: glAccountId (UUID) as a path parameter; there is no request body. No events are emitted and no state changes; this is a read-only projection. Returns 404 when no GL account exists for the supplied id. 
     * Get GL Account Balance
     */
    async getGLAccountBalanceRaw(requestParameters: GetGLAccountBalanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GLAccountBalanceResponse>> {
        if (requestParameters['glAccountId'] == null) {
            throw new runtime.RequiredError(
                'glAccountId',
                'Required parameter "glAccountId" was null or undefined when calling getGLAccountBalance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["accounting:coa:view"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/accounting/gl-accounts/{glAccountId}/balance`.replace(`{${"glAccountId"}}`, encodeURIComponent(String(requestParameters['glAccountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GLAccountBalanceResponseFromJSON(jsonValue));
    }

    /**
     * Returns the current posted balance of one GL account, computed from its journal entry lines. Use this tool for a single account\'s balance; use the trial balance report in financial reporting instead when balances for the whole chart are needed. Preconditions: the GL account must exist; an account with no postings reports a zero balance. Required inputs: glAccountId (UUID) as a path parameter; there is no request body. No events are emitted and no state changes; this is a read-only projection. Returns 404 when no GL account exists for the supplied id. 
     * Get GL Account Balance
     */
    async getGLAccountBalance(requestParameters: GetGLAccountBalanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GLAccountBalanceResponse> {
        const response = await this.getGLAccountBalanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists the chart of accounts as a paginated projection, optionally filtered by derived lifecycle status and sorted by a named field. Use this tool when browsing or searching the chart of accounts; do not use getGLAccount, which retrieves one account by its known id. Preconditions: none beyond the caller holding accounting:coa:view; an empty chart returns an empty page rather than an error. Required inputs: none; page defaults to 0, size to 20, sort to accountCode ascending (format \'field,direction\'), and status optionally filters by ACTIVE, INACTIVE or NOT_YET_ACTIVE. Emits an ACCOUNTING_GL_ACCOUNT_LIST audit event; no accounting state changes. Returns 400 when the sort property is not one of the supported fields. 
     * List GL Accounts
     */
    async listGLAccountsRaw(requestParameters: ListGLAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GLAccountListResponse>> {
        if (requestParameters['sort'] == null) {
            throw new runtime.RequiredError(
                'sort',
                'Required parameter "sort" was null or undefined when calling listGLAccounts().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["accounting:coa:view"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/accounting/gl-accounts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GLAccountListResponseFromJSON(jsonValue));
    }

    /**
     * Lists the chart of accounts as a paginated projection, optionally filtered by derived lifecycle status and sorted by a named field. Use this tool when browsing or searching the chart of accounts; do not use getGLAccount, which retrieves one account by its known id. Preconditions: none beyond the caller holding accounting:coa:view; an empty chart returns an empty page rather than an error. Required inputs: none; page defaults to 0, size to 20, sort to accountCode ascending (format \'field,direction\'), and status optionally filters by ACTIVE, INACTIVE or NOT_YET_ACTIVE. Emits an ACCOUNTING_GL_ACCOUNT_LIST audit event; no accounting state changes. Returns 400 when the sort property is not one of the supported fields. 
     * List GL Accounts
     */
    async listGLAccounts(requestParameters: ListGLAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GLAccountListResponse> {
        const response = await this.listGLAccountsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the mutable descriptive fields of an existing GL account: name, description, subtype and the reconcilable flag. Use this tool when correcting or enriching an account\'s metadata; do not use createGLAccount, which adds a new account, and note that accountCode and accountType are immutable and cannot be changed by any operation. Preconditions: the GL account must exist. Required inputs: glAccountId (UUID) as a path parameter; all body fields are optional and only supplied fields are changed (accountName max 100 chars, description max 500). Emits an ACCOUNTING_GL_ACCOUNT_UPDATE event; posted journal entries referencing the account are unaffected. Returns 404 when no GL account exists for the supplied id. 
     * Update GL Account
     */
    async updateGLAccountRaw(requestParameters: UpdateGLAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GLAccountResponse>> {
        if (requestParameters['glAccountId'] == null) {
            throw new runtime.RequiredError(
                'glAccountId',
                'Required parameter "glAccountId" was null or undefined when calling updateGLAccount().'
            );
        }

        if (requestParameters['gLAccountUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'gLAccountUpdateRequest',
                'Required parameter "gLAccountUpdateRequest" was null or undefined when calling updateGLAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["accounting:coa:edit"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/accounting/gl-accounts/{glAccountId}`.replace(`{${"glAccountId"}}`, encodeURIComponent(String(requestParameters['glAccountId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: GLAccountUpdateRequestToJSON(requestParameters['gLAccountUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GLAccountResponseFromJSON(jsonValue));
    }

    /**
     * Updates the mutable descriptive fields of an existing GL account: name, description, subtype and the reconcilable flag. Use this tool when correcting or enriching an account\'s metadata; do not use createGLAccount, which adds a new account, and note that accountCode and accountType are immutable and cannot be changed by any operation. Preconditions: the GL account must exist. Required inputs: glAccountId (UUID) as a path parameter; all body fields are optional and only supplied fields are changed (accountName max 100 chars, description max 500). Emits an ACCOUNTING_GL_ACCOUNT_UPDATE event; posted journal entries referencing the account are unaffected. Returns 404 when no GL account exists for the supplied id. 
     * Update GL Account
     */
    async updateGLAccount(requestParameters: UpdateGLAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GLAccountResponse> {
        const response = await this.updateGLAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
