/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { GLMappingCreateRequest, GLMappingCreateResponse, GLMappingResolveRequest, GLMappingResolveResponse } from '../models/index';
export interface CreateGLMappingRequest {
    gLMappingCreateRequest: GLMappingCreateRequest;
}
export interface ResolveGLMappingRequest {
    gLMappingResolveRequest: GLMappingResolveRequest;
}
/**
 *
 */
export declare class GLMappingAPIApi extends runtime.BaseAPI {
    /**
     * Creates a new GL mapping for source-system external code resolution
     * Create GL mapping
     */
    createGLMappingRaw(requestParameters: CreateGLMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GLMappingCreateResponse>>;
    /**
     * Creates a new GL mapping for source-system external code resolution
     * Create GL mapping
     */
    createGLMapping(requestParameters: CreateGLMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GLMappingCreateResponse>;
    /**
     * Resolves source-system external code to a GL account using effective-date rules
     * Resolve GL mapping
     */
    resolveGLMappingRaw(requestParameters: ResolveGLMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GLMappingResolveResponse>>;
    /**
     * Resolves source-system external code to a GL account using effective-date rules
     * Resolve GL mapping
     */
    resolveGLMapping(requestParameters: ResolveGLMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GLMappingResolveResponse>;
}
