/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { MappingKeyCreateRequest, MappingKeyListResponse, MappingKeyResponse, MappingKeyUpdateRequest } from '../models/index';
export interface CreateMappingKeyRequest {
    mappingKeyCreateRequest: MappingKeyCreateRequest;
}
export interface DeactivateMappingKeyRequest {
    mappingKeyId: string;
}
export interface GetMappingKeyRequest {
    mappingKeyId: string;
}
export interface ListMappingKeysByCategoryRequest {
    postingCategoryId: string;
    sort: string;
    page?: number;
    size?: number;
    isActive?: boolean;
}
export interface UpdateMappingKeyRequest {
    mappingKeyId: string;
    mappingKeyUpdateRequest: MappingKeyUpdateRequest;
}
/**
 *
 */
export declare class MappingKeysApi extends runtime.BaseAPI {
    /**
     * Create a new mapping key for a posting category.
     * Create mapping key
     */
    createMappingKeyRaw(requestParameters: CreateMappingKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MappingKeyResponse>>;
    /**
     * Create a new mapping key for a posting category.
     * Create mapping key
     */
    createMappingKey(requestParameters: CreateMappingKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MappingKeyResponse>;
    /**
     * Deactivate a mapping key.
     * Deactivate mapping key
     */
    deactivateMappingKeyRaw(requestParameters: DeactivateMappingKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;
    /**
     * Deactivate a mapping key.
     * Deactivate mapping key
     */
    deactivateMappingKey(requestParameters: DeactivateMappingKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;
    /**
     * Retrieve a mapping key by identifier.
     * Get mapping key
     */
    getMappingKeyRaw(requestParameters: GetMappingKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MappingKeyResponse>>;
    /**
     * Retrieve a mapping key by identifier.
     * Get mapping key
     */
    getMappingKey(requestParameters: GetMappingKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MappingKeyResponse>;
    /**
     * Retrieve paginated mapping keys for a posting category.
     * List mapping keys by category
     */
    listMappingKeysByCategoryRaw(requestParameters: ListMappingKeysByCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MappingKeyListResponse>>;
    /**
     * Retrieve paginated mapping keys for a posting category.
     * List mapping keys by category
     */
    listMappingKeysByCategory(requestParameters: ListMappingKeysByCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MappingKeyListResponse>;
    /**
     * Update an existing mapping key.
     * Update mapping key
     */
    updateMappingKeyRaw(requestParameters: UpdateMappingKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MappingKeyResponse>>;
    /**
     * Update an existing mapping key.
     * Update mapping key
     */
    updateMappingKey(requestParameters: UpdateMappingKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MappingKeyResponse>;
}
