/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Location API
 * API documentation for the Shop Location service, accessible via the API Gateway. Shop locations are Maintenance Bays and Mobile Shops.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One service bay to create at a location
 * @export
 * @interface BayBulkIngestRecord
 */
export interface BayBulkIngestRecord {
    /**
     * Bay type
     * @type {string}
     * @memberof BayBulkIngestRecord
     */
    bayType: string;
    /**
     * Location the bay belongs to. Defaults to the request's locationId when omitted.
     * @type {string}
     * @memberof BayBulkIngestRecord
     */
    locationId?: string;
    /**
     * How many vehicles the bay holds at once
     * @type {number}
     * @memberof BayBulkIngestRecord
     */
    maxConcurrentVehicles: number;
    /**
     * Name of the bay, unique within its location
     * @type {string}
     * @memberof BayBulkIngestRecord
     */
    name: string;
    /**
     * Bay status; defaults to ACTIVE
     * @type {string}
     * @memberof BayBulkIngestRecord
     */
    status?: string;
}

/**
 * Check if a given object implements the BayBulkIngestRecord interface.
 */
export function instanceOfBayBulkIngestRecord(value: object): boolean {
    if (!('bayType' in value)) return false;
    if (!('maxConcurrentVehicles' in value)) return false;
    if (!('name' in value)) return false;
    return true;
}

export function BayBulkIngestRecordFromJSON(json: any): BayBulkIngestRecord {
    return BayBulkIngestRecordFromJSONTyped(json, false);
}

export function BayBulkIngestRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): BayBulkIngestRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'bayType': json['bayType'],
        'locationId': json['locationId'] == null ? undefined : json['locationId'],
        'maxConcurrentVehicles': json['maxConcurrentVehicles'],
        'name': json['name'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function BayBulkIngestRecordToJSON(value?: BayBulkIngestRecord | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bayType': value['bayType'],
        'locationId': value['locationId'],
        'maxConcurrentVehicles': value['maxConcurrentVehicles'],
        'name': value['name'],
        'status': value['status'],
    };
}

