/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Location API
 * API documentation for the Shop Location service, accessible via the API Gateway. Shop locations are Maintenance Bays and Mobile Shops.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocationBulkIngestRecord } from './LocationBulkIngestRecord';
import {
    LocationBulkIngestRecordFromJSON,
    LocationBulkIngestRecordFromJSONTyped,
    LocationBulkIngestRecordToJSON,
} from './LocationBulkIngestRecord';

/**
 * 
 * @export
 * @interface BulkIngestRequestLocationBulkIngestRecord
 */
export interface BulkIngestRequestLocationBulkIngestRecord {
    /**
     * 
     * @type {string}
     * @memberof BulkIngestRequestLocationBulkIngestRecord
     */
    jobId: string;
    /**
     * 
     * @type {string}
     * @memberof BulkIngestRequestLocationBulkIngestRecord
     */
    locationId: string;
    /**
     * 
     * @type {Array<LocationBulkIngestRecord>}
     * @memberof BulkIngestRequestLocationBulkIngestRecord
     */
    records: Array<LocationBulkIngestRecord>;
    /**
     * 
     * @type {string}
     * @memberof BulkIngestRequestLocationBulkIngestRecord
     */
    operatorId?: string;
}

/**
 * Check if a given object implements the BulkIngestRequestLocationBulkIngestRecord interface.
 */
export function instanceOfBulkIngestRequestLocationBulkIngestRecord(value: object): boolean {
    if (!('jobId' in value)) return false;
    if (!('locationId' in value)) return false;
    if (!('records' in value)) return false;
    return true;
}

export function BulkIngestRequestLocationBulkIngestRecordFromJSON(json: any): BulkIngestRequestLocationBulkIngestRecord {
    return BulkIngestRequestLocationBulkIngestRecordFromJSONTyped(json, false);
}

export function BulkIngestRequestLocationBulkIngestRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkIngestRequestLocationBulkIngestRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'],
        'locationId': json['locationId'],
        'records': ((json['records'] as Array<any>).map(LocationBulkIngestRecordFromJSON)),
        'operatorId': json['operatorId'] == null ? undefined : json['operatorId'],
    };
}

export function BulkIngestRequestLocationBulkIngestRecordToJSON(value?: BulkIngestRequestLocationBulkIngestRecord | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jobId': value['jobId'],
        'locationId': value['locationId'],
        'records': ((value['records'] as Array<any>).map(LocationBulkIngestRecordToJSON)),
        'operatorId': value['operatorId'],
    };
}

