/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Location API
 * API documentation for the Shop Location service, accessible via the API Gateway. Shop locations are Maintenance Bays and Mobile Shops.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One mobile unit to create
 * @export
 * @interface MobileUnitBulkIngestRecord
 */
export interface MobileUnitBulkIngestRecord {
    /**
     * Location the unit is based at. Defaults to the request's locationId when omitted.
     * @type {string}
     * @memberof MobileUnitBulkIngestRecord
     */
    baseLocationId?: string;
    /**
     * Name of the unit, unique for its base location
     * @type {string}
     * @memberof MobileUnitBulkIngestRecord
     */
    name: string;
    /**
     * Free-text notes
     * @type {string}
     * @memberof MobileUnitBulkIngestRecord
     */
    notes?: string;
    /**
     * Unit status; defaults to INACTIVE. A unit created ACTIVE must also carry a travel buffer policy, capabilities and coverage rules, none of which this record expresses — so an ACTIVE row is rejected by the service rather than created half-configured.
     * @type {string}
     * @memberof MobileUnitBulkIngestRecord
     */
    status?: string;
}

/**
 * Check if a given object implements the MobileUnitBulkIngestRecord interface.
 */
export function instanceOfMobileUnitBulkIngestRecord(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function MobileUnitBulkIngestRecordFromJSON(json: any): MobileUnitBulkIngestRecord {
    return MobileUnitBulkIngestRecordFromJSONTyped(json, false);
}

export function MobileUnitBulkIngestRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): MobileUnitBulkIngestRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'baseLocationId': json['baseLocationId'] == null ? undefined : json['baseLocationId'],
        'name': json['name'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function MobileUnitBulkIngestRecordToJSON(value?: MobileUnitBulkIngestRecord | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'baseLocationId': value['baseLocationId'],
        'name': value['name'],
        'notes': value['notes'],
        'status': value['status'],
    };
}

