/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Location API
 * API documentation for the Shop Location service, accessible via the API Gateway. Shop locations are Maintenance Bays and Mobile Shops.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoverageRuleResponse } from './CoverageRuleResponse';
import {
    CoverageRuleResponseFromJSON,
    CoverageRuleResponseFromJSONTyped,
    CoverageRuleResponseToJSON,
} from './CoverageRuleResponse';

/**
 * Response payload describing a mobile unit
 * @export
 * @interface MobileUnitResponse
 */
export interface MobileUnitResponse {
    /**
     * Identifier of the base location the mobile unit operates from
     * @type {string}
     * @memberof MobileUnitResponse
     */
    baseLocationId?: string;
    /**
     * The unit's coverage rules ordered by ascending priority. Present only on listMobileUnits with include=coverageRules; absent otherwise (read them with listCoverageRules).
     * @type {Array<CoverageRuleResponse>}
     * @memberof MobileUnitResponse
     */
    coverageRules?: Array<CoverageRuleResponse>;
    /**
     * Timestamp when the mobile unit was created (ISO 8601)
     * @type {Date}
     * @memberof MobileUnitResponse
     */
    createdAt?: Date;
    /**
     * Unique identifier of the mobile unit
     * @type {string}
     * @memberof MobileUnitResponse
     */
    id: string;
    /**
     * Display name of the mobile unit
     * @type {string}
     * @memberof MobileUnitResponse
     */
    name?: string;
    /**
     * Free-text notes about the mobile unit
     * @type {string}
     * @memberof MobileUnitResponse
     */
    notes?: string;
    /**
     * Catalog operation codes this unit can perform off-site (CAP-325 D14), UPPER-DASH per ADR-0059 §3; empty for a unit that has not declared any.
     * @type {Array<string>}
     * @memberof MobileUnitResponse
     */
    serviceCapabilityCodes?: Array<string>;
    /**
     * Operational status of the mobile unit
     * @type {string}
     * @memberof MobileUnitResponse
     */
    status?: MobileUnitResponseStatusEnum;
    /**
     * Identifier of the travel buffer policy applied to the mobile unit
     * @type {string}
     * @memberof MobileUnitResponse
     */
    travelBufferPolicyId?: string;
    /**
     * Timestamp when the mobile unit was last updated (ISO 8601)
     * @type {Date}
     * @memberof MobileUnitResponse
     */
    updatedAt?: Date;
}

/**
* @export
* @enum {string}
*/
export enum MobileUnitResponseStatusEnum {
    Active = 'ACTIVE',
    Inactive = 'INACTIVE'
}


/**
 * Check if a given object implements the MobileUnitResponse interface.
 */
export function instanceOfMobileUnitResponse(value: object): boolean {
    if (!('id' in value)) return false;
    return true;
}

export function MobileUnitResponseFromJSON(json: any): MobileUnitResponse {
    return MobileUnitResponseFromJSONTyped(json, false);
}

export function MobileUnitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MobileUnitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'baseLocationId': json['baseLocationId'] == null ? undefined : json['baseLocationId'],
        'coverageRules': json['coverageRules'] == null ? undefined : ((json['coverageRules'] as Array<any>).map(CoverageRuleResponseFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'serviceCapabilityCodes': json['serviceCapabilityCodes'] == null ? undefined : json['serviceCapabilityCodes'],
        'status': json['status'] == null ? undefined : json['status'],
        'travelBufferPolicyId': json['travelBufferPolicyId'] == null ? undefined : json['travelBufferPolicyId'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function MobileUnitResponseToJSON(value?: MobileUnitResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'baseLocationId': value['baseLocationId'],
        'coverageRules': value['coverageRules'] == null ? undefined : ((value['coverageRules'] as Array<any>).map(CoverageRuleResponseToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'id': value['id'],
        'name': value['name'],
        'notes': value['notes'],
        'serviceCapabilityCodes': value['serviceCapabilityCodes'],
        'status': value['status'],
        'travelBufferPolicyId': value['travelBufferPolicyId'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

