/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Location API
 * API documentation for the Shop Location service, accessible via the API Gateway. Shop locations are Maintenance Bays and Mobile Shops.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A postal code entry within a service area
 * @export
 * @interface PostalCodeEntry
 */
export interface PostalCodeEntry {
    /**
     * ISO 3166-1 alpha-2 country code
     * @type {string}
     * @memberof PostalCodeEntry
     */
    countryCode?: string;
    /**
     * Postal or ZIP code
     * @type {string}
     * @memberof PostalCodeEntry
     */
    postalCode: string;
}

/**
 * Check if a given object implements the PostalCodeEntry interface.
 */
export function instanceOfPostalCodeEntry(value: object): boolean {
    if (!('postalCode' in value)) return false;
    return true;
}

export function PostalCodeEntryFromJSON(json: any): PostalCodeEntry {
    return PostalCodeEntryFromJSONTyped(json, false);
}

export function PostalCodeEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostalCodeEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'postalCode': json['postalCode'],
    };
}

export function PostalCodeEntryToJSON(value?: PostalCodeEntry | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'countryCode': value['countryCode'],
        'postalCode': value['postalCode'],
    };
}

