/**
 * Positivity Location API
 * API documentation for the Shop Location service, accessible via the API Gateway. Shop locations are Maintenance Bays and Mobile Shops.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface StorageLocationResponse
 */
export interface StorageLocationResponse {
    /**
     *
     * @type {string}
     * @memberof StorageLocationResponse
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof StorageLocationResponse
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof StorageLocationResponse
     */
    barcode?: string;
    /**
     *
     * @type {string}
     * @memberof StorageLocationResponse
     */
    type?: StorageLocationResponseTypeEnum;
    /**
     *
     * @type {string}
     * @memberof StorageLocationResponse
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof StorageLocationResponse
     */
    siteId?: string;
    /**
     *
     * @type {string}
     * @memberof StorageLocationResponse
     */
    parentStorageLocationId?: string;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof StorageLocationResponse
     */
    capacity?: {
        [key: string]: any;
    };
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof StorageLocationResponse
     */
    temperature?: {
        [key: string]: any;
    };
    /**
     *
     * @type {number}
     * @memberof StorageLocationResponse
     */
    inventoryCount?: number;
}
/**
* @export
* @enum {string}
*/
export declare enum StorageLocationResponseTypeEnum {
    Floor = "FLOOR",
    Shelf = "SHELF",
    Bin = "BIN",
    Cage = "CAGE",
    Truck = "TRUCK"
}
/**
 * Check if a given object implements the StorageLocationResponse interface.
 */
export declare function instanceOfStorageLocationResponse(value: object): boolean;
export declare function StorageLocationResponseFromJSON(json: any): StorageLocationResponse;
export declare function StorageLocationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageLocationResponse;
export declare function StorageLocationResponseToJSON(value?: StorageLocationResponse | null): any;
