/**
 * POS Human Resources Service API
 * Human Resources service for employee management, payroll, and benefits administration
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { Person, ResolvePersonRequest, ResolvePersonResponse } from '../models/index';
export interface CreatePersonRequest {
    person: Person;
}
export interface DeletePersonRequest {
    personId: string;
}
export interface GetPersonByIdRequest {
    personId: string;
}
export interface ResolvePersonOperationRequest {
    resolvePersonRequest: ResolvePersonRequest;
}
export interface UpdatePersonRequest {
    personId: string;
    person: Person;
}
/**
 *
 */
export declare class PeopleAPIApi extends runtime.BaseAPI {
    /**
     * Add a new person to the system.
     * Create a new person
     */
    createPersonRaw(requestParameters: CreatePersonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Person>>;
    /**
     * Add a new person to the system.
     * Create a new person
     */
    createPerson(requestParameters: CreatePersonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Person>;
    /**
     * Delete a person by their unique ID.
     * Delete a person
     */
    deletePersonRaw(requestParameters: DeletePersonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;
    /**
     * Delete a person by their unique ID.
     * Delete a person
     */
    deletePerson(requestParameters: DeletePersonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;
    /**
     * Retrieve a list of all people.
     * Get all people
     */
    getAllPeopleRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Person>>>;
    /**
     * Retrieve a list of all people.
     * Get all people
     */
    getAllPeople(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Person>>;
    /**
     * Retrieve a person by their unique ID.
     * Get person by ID
     */
    getPersonByIdRaw(requestParameters: GetPersonByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Person>>;
    /**
     * Retrieve a person by their unique ID.
     * Get person by ID
     */
    getPersonById(requestParameters: GetPersonByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Person>;
    /**
     * Find best matching person by score or create a new person
     * Resolve person
     */
    resolvePersonRaw(requestParameters: ResolvePersonOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResolvePersonResponse>>;
    /**
     * Find best matching person by score or create a new person
     * Resolve person
     */
    resolvePerson(requestParameters: ResolvePersonOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResolvePersonResponse>;
    /**
     * Update the details of an existing person.
     * Update an existing person
     */
    updatePersonRaw(requestParameters: UpdatePersonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Person>>;
    /**
     * Update the details of an existing person.
     * Update an existing person
     */
    updatePerson(requestParameters: UpdatePersonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Person>;
}
