/* tslint:disable */
/* eslint-disable */
/**
 * POS Human Resources Service API
 * Human Resources service for employee management, payroll, and benefits administration
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BulkIngestRequestStaffingAssignmentBulkIngestRecord,
  BulkIngestResponse,
} from '../models/index';
import {
    BulkIngestRequestStaffingAssignmentBulkIngestRecordFromJSON,
    BulkIngestRequestStaffingAssignmentBulkIngestRecordToJSON,
    BulkIngestResponseFromJSON,
    BulkIngestResponseToJSON,
} from '../models/index';

export interface BulkIngestStaffingAssignmentsRequest {
    bulkIngestRequestStaffingAssignmentBulkIngestRecord: BulkIngestRequestStaffingAssignmentBulkIngestRecord;
}

/**
 * 
 */
export class StaffingAssignmentBulkIngestAPIApi extends runtime.BaseAPI {

    /**
     * Creates many staffing assignments at once, resolving each row\'s employee number to a person. Use this tool when standing up a location\'s roster or seeding an environment; use createStaffingAssignment instead for a single assignment. Preconditions: each employee number must resolve to a person with an ACTIVE employee record, each location must be active, and no assignment may overlap an existing one for the same person, location and role. Required inputs: jobId (UUID), locationId (UUID) and records, each with an employeeNumber and a role; a record\'s own locationId overrides the batch one, and effectiveFrom defaults to today. Emits a PEOPLE_STAFFING_ASSIGNMENT_BULK_INGEST event and a staffing-assignment fact per row. Note two side effects that make this not simply additive: a new primary demotes and end-dates an overlapping existing primary, and a person\'s first active assignment is forced primary whatever the flag says. Returns 200 with a per-record result; check each result rather than the status alone. 
     * Assign People to Locations in Bulk
     */
    async bulkIngestStaffingAssignmentsRaw(requestParameters: BulkIngestStaffingAssignmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkIngestResponse>> {
        if (requestParameters['bulkIngestRequestStaffingAssignmentBulkIngestRecord'] == null) {
            throw new runtime.RequiredError(
                'bulkIngestRequestStaffingAssignmentBulkIngestRecord',
                'Required parameter "bulkIngestRequestStaffingAssignmentBulkIngestRecord" was null or undefined when calling bulkIngestStaffingAssignments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["people:employee:edit"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/people/staffing/bulk-ingest`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkIngestRequestStaffingAssignmentBulkIngestRecordToJSON(requestParameters['bulkIngestRequestStaffingAssignmentBulkIngestRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkIngestResponseFromJSON(jsonValue));
    }

    /**
     * Creates many staffing assignments at once, resolving each row\'s employee number to a person. Use this tool when standing up a location\'s roster or seeding an environment; use createStaffingAssignment instead for a single assignment. Preconditions: each employee number must resolve to a person with an ACTIVE employee record, each location must be active, and no assignment may overlap an existing one for the same person, location and role. Required inputs: jobId (UUID), locationId (UUID) and records, each with an employeeNumber and a role; a record\'s own locationId overrides the batch one, and effectiveFrom defaults to today. Emits a PEOPLE_STAFFING_ASSIGNMENT_BULK_INGEST event and a staffing-assignment fact per row. Note two side effects that make this not simply additive: a new primary demotes and end-dates an overlapping existing primary, and a person\'s first active assignment is forced primary whatever the flag says. Returns 200 with a per-record result; check each result rather than the status alone. 
     * Assign People to Locations in Bulk
     */
    async bulkIngestStaffingAssignments(requestParameters: BulkIngestStaffingAssignmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkIngestResponse> {
        const response = await this.bulkIngestStaffingAssignmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
