/* tslint:disable */
/* eslint-disable */
/**
 * POS Human Resources Service API
 * Human Resources service for employee management, payroll, and benefits administration
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TimeEntryDecisionBatchRequest,
} from '../models/index';
import {
    TimeEntryDecisionBatchRequestFromJSON,
    TimeEntryDecisionBatchRequestToJSON,
} from '../models/index';

export interface ApproveTimeEntriesBatchRequest {
    timeEntryDecisionBatchRequest: TimeEntryDecisionBatchRequest;
    xCorrelationId?: string;
}

export interface RejectTimeEntriesBatchRequest {
    timeEntryDecisionBatchRequest: TimeEntryDecisionBatchRequest;
    xCorrelationId?: string;
}

/**
 * 
 */
export class TimeEntryApprovalAPIApi extends runtime.BaseAPI {

    /**
     * Approves a batch of time entries, marking each SUBMITTED or PENDING_APPROVAL entry APPROVED and stamping the approver and approval time; pos-people is authoritative for approval execution. Use this tool for supervisor approval of individually selected time entries; do not use rejectTimeEntriesBatch, which rejects them, and do not use approveTimePeriod, which approves a whole pay period per person. Preconditions: each entry must exist and be in SUBMITTED or PENDING_APPROVAL status, and the caller needs the people:timeEntry:approve authority for individual entries to succeed. Required inputs: decisions, a non-empty list of objects each carrying timeEntryId (UUID string); an optional X-Correlation-Id header is recorded in the audit trail. Emits a PEOPLE_TIME_ENTRY_APPROVE event and writes an audit row per decision. Returns 200 with a per-entry result list (failure codes NOT_FOUND, ENTRY_NOT_PENDING, FORBIDDEN) rather than failing the whole batch, and 400 when the decisions list is missing or empty. 
     * Batch Approve Submitted Time Entries
     */
    async approveTimeEntriesBatchRaw(requestParameters: ApproveTimeEntriesBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['timeEntryDecisionBatchRequest'] == null) {
            throw new runtime.RequiredError(
                'timeEntryDecisionBatchRequest',
                'Required parameter "timeEntryDecisionBatchRequest" was null or undefined when calling approveTimeEntriesBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xCorrelationId'] != null) {
            headerParameters['X-Correlation-Id'] = String(requestParameters['xCorrelationId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["people:timeEntry:approve"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/people/timeEntries/approve`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TimeEntryDecisionBatchRequestToJSON(requestParameters['timeEntryDecisionBatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Approves a batch of time entries, marking each SUBMITTED or PENDING_APPROVAL entry APPROVED and stamping the approver and approval time; pos-people is authoritative for approval execution. Use this tool for supervisor approval of individually selected time entries; do not use rejectTimeEntriesBatch, which rejects them, and do not use approveTimePeriod, which approves a whole pay period per person. Preconditions: each entry must exist and be in SUBMITTED or PENDING_APPROVAL status, and the caller needs the people:timeEntry:approve authority for individual entries to succeed. Required inputs: decisions, a non-empty list of objects each carrying timeEntryId (UUID string); an optional X-Correlation-Id header is recorded in the audit trail. Emits a PEOPLE_TIME_ENTRY_APPROVE event and writes an audit row per decision. Returns 200 with a per-entry result list (failure codes NOT_FOUND, ENTRY_NOT_PENDING, FORBIDDEN) rather than failing the whole batch, and 400 when the decisions list is missing or empty. 
     * Batch Approve Submitted Time Entries
     */
    async approveTimeEntriesBatch(requestParameters: ApproveTimeEntriesBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.approveTimeEntriesBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rejects a batch of time entries, marking each SUBMITTED or PENDING_APPROVAL entry REJECTED with the supplied reason stored on the entry. Use this tool to send individually selected entries back with a reason; do not use approveTimeEntriesBatch, which approves them, and do not use rejectTimePeriod, which rejects a whole pay period per person. Preconditions: each entry must exist and be in SUBMITTED or PENDING_APPROVAL status, and the caller needs the people:timeEntry:reject authority for individual entries to succeed. Required inputs: decisions, a non-empty list where every element carries timeEntryId and a non-blank rejectionReason; one missing reason fails the entire request before any entry is touched. Emits a PEOPLE_TIME_ENTRY_REJECT event and writes an audit row per decision. Returns 200 with a per-entry result list (failure codes NOT_FOUND, ENTRY_NOT_PENDING, FORBIDDEN), and 400 when any decision lacks a rejectionReason. 
     * Batch Reject Submitted Time Entries
     */
    async rejectTimeEntriesBatchRaw(requestParameters: RejectTimeEntriesBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['timeEntryDecisionBatchRequest'] == null) {
            throw new runtime.RequiredError(
                'timeEntryDecisionBatchRequest',
                'Required parameter "timeEntryDecisionBatchRequest" was null or undefined when calling rejectTimeEntriesBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xCorrelationId'] != null) {
            headerParameters['X-Correlation-Id'] = String(requestParameters['xCorrelationId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["people:timeEntry:reject"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/people/timeEntries/reject`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TimeEntryDecisionBatchRequestToJSON(requestParameters['timeEntryDecisionBatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Rejects a batch of time entries, marking each SUBMITTED or PENDING_APPROVAL entry REJECTED with the supplied reason stored on the entry. Use this tool to send individually selected entries back with a reason; do not use approveTimeEntriesBatch, which approves them, and do not use rejectTimePeriod, which rejects a whole pay period per person. Preconditions: each entry must exist and be in SUBMITTED or PENDING_APPROVAL status, and the caller needs the people:timeEntry:reject authority for individual entries to succeed. Required inputs: decisions, a non-empty list where every element carries timeEntryId and a non-blank rejectionReason; one missing reason fails the entire request before any entry is touched. Emits a PEOPLE_TIME_ENTRY_REJECT event and writes an audit row per decision. Returns 200 with a per-entry result list (failure codes NOT_FOUND, ENTRY_NOT_PENDING, FORBIDDEN), and 400 when any decision lacks a rejectionReason. 
     * Batch Reject Submitted Time Entries
     */
    async rejectTimeEntriesBatch(requestParameters: RejectTimeEntriesBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.rejectTimeEntriesBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
