/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Customer API
 * API documentation for the Customer service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to complete or dismiss a follow-up task
 * @export
 * @interface CloseFollowUpTaskRequest
 */
export interface CloseFollowUpTaskRequest {
    /**
     * Appointment created from the hand-off, when booking followed
     * @type {string}
     * @memberof CloseFollowUpTaskRequest
     */
    bookedAppointmentId?: string;
    /**
     * Workorder created from the hand-off, when booking followed
     * @type {string}
     * @memberof CloseFollowUpTaskRequest
     */
    bookedWorkorderId?: string;
    /**
     * What happened when the follow-up was worked
     * @type {string}
     * @memberof CloseFollowUpTaskRequest
     */
    outcome: string;
}

/**
 * Check if a given object implements the CloseFollowUpTaskRequest interface.
 */
export function instanceOfCloseFollowUpTaskRequest(value: object): boolean {
    if (!('outcome' in value)) return false;
    return true;
}

export function CloseFollowUpTaskRequestFromJSON(json: any): CloseFollowUpTaskRequest {
    return CloseFollowUpTaskRequestFromJSONTyped(json, false);
}

export function CloseFollowUpTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloseFollowUpTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bookedAppointmentId': json['bookedAppointmentId'] == null ? undefined : json['bookedAppointmentId'],
        'bookedWorkorderId': json['bookedWorkorderId'] == null ? undefined : json['bookedWorkorderId'],
        'outcome': json['outcome'],
    };
}

export function CloseFollowUpTaskRequestToJSON(value?: CloseFollowUpTaskRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bookedAppointmentId': value['bookedAppointmentId'],
        'bookedWorkorderId': value['bookedWorkorderId'],
        'outcome': value['outcome'],
    };
}

