/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Customer API
 * API documentation for the Customer service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountSummary } from './AccountSummary';
import {
    AccountSummaryFromJSON,
    AccountSummaryFromJSONTyped,
    AccountSummaryToJSON,
} from './AccountSummary';
import type { BillingPreferences } from './BillingPreferences';
import {
    BillingPreferencesFromJSON,
    BillingPreferencesFromJSONTyped,
    BillingPreferencesToJSON,
} from './BillingPreferences';
import type { BillingRuleRef } from './BillingRuleRef';
import {
    BillingRuleRefFromJSON,
    BillingRuleRefFromJSONTyped,
    BillingRuleRefToJSON,
} from './BillingRuleRef';
import type { ContactSummary } from './ContactSummary';
import {
    ContactSummaryFromJSON,
    ContactSummaryFromJSONTyped,
    ContactSummaryToJSON,
} from './ContactSummary';
import type { SnapshotMetadata } from './SnapshotMetadata';
import {
    SnapshotMetadataFromJSON,
    SnapshotMetadataFromJSONTyped,
    SnapshotMetadataToJSON,
} from './SnapshotMetadata';
import type { VehicleSummary } from './VehicleSummary';
import {
    VehicleSummaryFromJSON,
    VehicleSummaryFromJSONTyped,
    VehicleSummaryToJSON,
} from './VehicleSummary';

/**
 * 
 * @export
 * @interface CrmSnapshotDTO
 */
export interface CrmSnapshotDTO {
    /**
     * 
     * @type {SnapshotMetadata}
     * @memberof CrmSnapshotDTO
     */
    snapshotMetadata?: SnapshotMetadata;
    /**
     * 
     * @type {AccountSummary}
     * @memberof CrmSnapshotDTO
     */
    account?: AccountSummary;
    /**
     * 
     * @type {Array<ContactSummary>}
     * @memberof CrmSnapshotDTO
     */
    contacts?: Array<ContactSummary>;
    /**
     * 
     * @type {Array<VehicleSummary>}
     * @memberof CrmSnapshotDTO
     */
    vehicles?: Array<VehicleSummary>;
    /**
     * 
     * @type {BillingPreferences}
     * @memberof CrmSnapshotDTO
     */
    preferences?: BillingPreferences;
    /**
     * 
     * @type {BillingRuleRef}
     * @memberof CrmSnapshotDTO
     */
    billingRules?: BillingRuleRef;
}

/**
 * Check if a given object implements the CrmSnapshotDTO interface.
 */
export function instanceOfCrmSnapshotDTO(value: object): boolean {
    return true;
}

export function CrmSnapshotDTOFromJSON(json: any): CrmSnapshotDTO {
    return CrmSnapshotDTOFromJSONTyped(json, false);
}

export function CrmSnapshotDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrmSnapshotDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'snapshotMetadata': json['snapshotMetadata'] == null ? undefined : SnapshotMetadataFromJSON(json['snapshotMetadata']),
        'account': json['account'] == null ? undefined : AccountSummaryFromJSON(json['account']),
        'contacts': json['contacts'] == null ? undefined : ((json['contacts'] as Array<any>).map(ContactSummaryFromJSON)),
        'vehicles': json['vehicles'] == null ? undefined : ((json['vehicles'] as Array<any>).map(VehicleSummaryFromJSON)),
        'preferences': json['preferences'] == null ? undefined : BillingPreferencesFromJSON(json['preferences']),
        'billingRules': json['billingRules'] == null ? undefined : BillingRuleRefFromJSON(json['billingRules']),
    };
}

export function CrmSnapshotDTOToJSON(value?: CrmSnapshotDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'snapshotMetadata': SnapshotMetadataToJSON(value['snapshotMetadata']),
        'account': AccountSummaryToJSON(value['account']),
        'contacts': value['contacts'] == null ? undefined : ((value['contacts'] as Array<any>).map(ContactSummaryToJSON)),
        'vehicles': value['vehicles'] == null ? undefined : ((value['vehicles'] as Array<any>).map(VehicleSummaryToJSON)),
        'preferences': BillingPreferencesToJSON(value['preferences']),
        'billingRules': BillingRuleRefToJSON(value['billingRules']),
    };
}

