/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Customer API
 * API documentation for the Customer service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SnapshotMetadata
 */
export interface SnapshotMetadata {
    /**
     * 
     * @type {string}
     * @memberof SnapshotMetadata
     */
    snapshotId?: string;
    /**
     * 
     * @type {Date}
     * @memberof SnapshotMetadata
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof SnapshotMetadata
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof SnapshotMetadata
     */
    source?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SnapshotMetadata
     */
    stale?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof SnapshotMetadata
     */
    staleSince?: Date;
}

/**
 * Check if a given object implements the SnapshotMetadata interface.
 */
export function instanceOfSnapshotMetadata(value: object): boolean {
    return true;
}

export function SnapshotMetadataFromJSON(json: any): SnapshotMetadata {
    return SnapshotMetadataFromJSONTyped(json, false);
}

export function SnapshotMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnapshotMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'snapshotId': json['snapshotId'] == null ? undefined : json['snapshotId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'version': json['version'] == null ? undefined : json['version'],
        'source': json['source'] == null ? undefined : json['source'],
        'stale': json['stale'] == null ? undefined : json['stale'],
        'staleSince': json['staleSince'] == null ? undefined : (new Date(json['staleSince'])),
    };
}

export function SnapshotMetadataToJSON(value?: SnapshotMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'snapshotId': value['snapshotId'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'version': value['version'],
        'source': value['source'],
        'stale': value['stale'],
        'staleSince': value['staleSince'] == null ? undefined : ((value['staleSince']).toISOString()),
    };
}

