/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Customer API
 * API documentation for the Customer service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VehicleSummary
 */
export interface VehicleSummary {
    /**
     * 
     * @type {string}
     * @memberof VehicleSummary
     */
    vehicleId?: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleSummary
     */
    vin?: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleSummary
     */
    licensePlate?: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleSummary
     */
    make?: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleSummary
     */
    model?: string;
    /**
     * 
     * @type {number}
     * @memberof VehicleSummary
     */
    year?: number;
}

/**
 * Check if a given object implements the VehicleSummary interface.
 */
export function instanceOfVehicleSummary(value: object): boolean {
    if (value === null || Array.isArray(value) || typeof value !== 'object') {
        return false;
    }

    const candidate = value as Record<string, unknown>;
    return (
        (candidate['vehicleId'] === undefined || typeof candidate['vehicleId'] === 'string') &&
        (candidate['vin'] === undefined || typeof candidate['vin'] === 'string') &&
        (candidate['licensePlate'] === undefined || typeof candidate['licensePlate'] === 'string') &&
        (candidate['make'] === undefined || typeof candidate['make'] === 'string') &&
        (candidate['model'] === undefined || typeof candidate['model'] === 'string') &&
        (candidate['year'] === undefined || typeof candidate['year'] === 'number')
    );
}

export function VehicleSummaryFromJSON(json: any): VehicleSummary {
    return VehicleSummaryFromJSONTyped(json, false);
}

export function VehicleSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'vehicleId': json['vehicleId'] == null ? undefined : json['vehicleId'],
        'vin': json['vin'] == null ? undefined : json['vin'],
        'licensePlate': json['licensePlate'] == null ? undefined : json['licensePlate'],
        'make': json['make'] == null ? undefined : json['make'],
        'model': json['model'] == null ? undefined : json['model'],
        'year': json['year'] == null ? undefined : json['year'],
    };
}

export function VehicleSummaryToJSON(value?: VehicleSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'vehicleId': value['vehicleId'],
        'vin': value['vin'],
        'licensePlate': value['licensePlate'],
        'make': value['make'],
        'model': value['model'],
        'year': value['year'],
    };
}
