/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Product API
 * API documentation for the Product service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductSummary } from './ProductSummary';
import {
    ProductSummaryFromJSON,
    ProductSummaryFromJSONTyped,
    ProductSummaryToJSON,
} from './ProductSummary';

/**
 * Cursor-based catalog search result
 * @export
 * @interface CatalogSearchResultDto
 */
export interface CatalogSearchResultDto {
    /**
     * Page of matching product summaries
     * @type {Array<ProductSummary>}
     * @memberof CatalogSearchResultDto
     */
    data?: Array<ProductSummary>;
    /**
     * Opaque cursor for the next page; null if no more results
     * @type {string}
     * @memberof CatalogSearchResultDto
     */
    nextCursor?: string;
    /**
     * Number of items requested (limit)
     * @type {number}
     * @memberof CatalogSearchResultDto
     */
    limit?: number;
}

/**
 * Check if a given object implements the CatalogSearchResultDto interface.
 */
export function instanceOfCatalogSearchResultDto(value: object): boolean {
    return true;
}

export function CatalogSearchResultDtoFromJSON(json: any): CatalogSearchResultDto {
    return CatalogSearchResultDtoFromJSONTyped(json, false);
}

export function CatalogSearchResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogSearchResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ProductSummaryFromJSON)),
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
        'limit': json['limit'] == null ? undefined : json['limit'],
    };
}

export function CatalogSearchResultDtoToJSON(value?: CatalogSearchResultDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ProductSummaryToJSON)),
        'nextCursor': value['nextCursor'],
        'limit': value['limit'],
    };
}

