/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Product API
 * API documentation for the Product service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A named set of operations sold together. With fleetPartyId set it is that account's requirement set rather than a general offering.
 * @export
 * @interface ServicePackageRequestDto
 */
export interface ServicePackageRequestDto {
    /**
     * Whether the package is currently offered; defaults to true
     * @type {boolean}
     * @memberof ServicePackageRequestDto
     */
    active?: boolean;
    /**
     * What the package covers
     * @type {string}
     * @memberof ServicePackageRequestDto
     */
    description?: string;
    /**
     * First day the package is offered
     * @type {Date}
     * @memberof ServicePackageRequestDto
     */
    effectiveFrom?: Date;
    /**
     * Last day the package is offered
     * @type {Date}
     * @memberof ServicePackageRequestDto
     */
    effectiveTo?: Date;
    /**
     * Fleet account this package is the requirement set for; omit for a general offering
     * @type {string}
     * @memberof ServicePackageRequestDto
     */
    fleetPartyId?: string;
    /**
     * Display name
     * @type {string}
     * @memberof ServicePackageRequestDto
     */
    name: string;
    /**
     * Owning location; required when ownerScope is SHOP, rejected otherwise
     * @type {string}
     * @memberof ServicePackageRequestDto
     */
    ownerLocationId?: string;
    /**
     * PLATFORM (every location sells it) or SHOP (one location's own); defaults to PLATFORM
     * @type {string}
     * @memberof ServicePackageRequestDto
     */
    ownerScope?: ServicePackageRequestDtoOwnerScopeEnum;
    /**
     * Stable package identity, unique platform-wide
     * @type {string}
     * @memberof ServicePackageRequestDto
     */
    packageCode: string;
    /**
     * Authored labor hours for the package as sold, decimal hours in tenths. Not derived from the members: a shop prices a package as a number it chose.
     * @type {number}
     * @memberof ServicePackageRequestDto
     */
    packageLaborHours?: number;
}

/**
* @export
* @enum {string}
*/
export enum ServicePackageRequestDtoOwnerScopeEnum {
    Platform = 'PLATFORM',
    Shop = 'SHOP'
}


/**
 * Check if a given object implements the ServicePackageRequestDto interface.
 */
export function instanceOfServicePackageRequestDto(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('packageCode' in value)) return false;
    return true;
}

export function ServicePackageRequestDtoFromJSON(json: any): ServicePackageRequestDto {
    return ServicePackageRequestDtoFromJSONTyped(json, false);
}

export function ServicePackageRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicePackageRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : json['active'],
        'description': json['description'] == null ? undefined : json['description'],
        'effectiveFrom': json['effectiveFrom'] == null ? undefined : (new Date(json['effectiveFrom'])),
        'effectiveTo': json['effectiveTo'] == null ? undefined : (new Date(json['effectiveTo'])),
        'fleetPartyId': json['fleetPartyId'] == null ? undefined : json['fleetPartyId'],
        'name': json['name'],
        'ownerLocationId': json['ownerLocationId'] == null ? undefined : json['ownerLocationId'],
        'ownerScope': json['ownerScope'] == null ? undefined : json['ownerScope'],
        'packageCode': json['packageCode'],
        'packageLaborHours': json['packageLaborHours'] == null ? undefined : json['packageLaborHours'],
    };
}

export function ServicePackageRequestDtoToJSON(value?: ServicePackageRequestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'active': value['active'],
        'description': value['description'],
        'effectiveFrom': value['effectiveFrom'] == null ? undefined : ((value['effectiveFrom']).toISOString().substring(0,10)),
        'effectiveTo': value['effectiveTo'] == null ? undefined : ((value['effectiveTo']).toISOString().substring(0,10)),
        'fleetPartyId': value['fleetPartyId'],
        'name': value['name'],
        'ownerLocationId': value['ownerLocationId'],
        'ownerScope': value['ownerScope'],
        'packageCode': value['packageCode'],
        'packageLaborHours': value['packageLaborHours'],
    };
}

