/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Product API
 * API documentation for the Product service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A hand-authored (DURION-source) labor standard for a service operation. Vehicle-key fields left null are wildcards: the time applies to any vehicle the more specific fields do not narrow.
 * @export
 * @interface ServiceLaborStandardRequestDto
 */
export interface ServiceLaborStandardRequestDto {
    /**
     * Engine code
     * @type {string}
     * @memberof ServiceLaborStandardRequestDto
     */
    engineCode?: string;
    /**
     * Operation codes whose time is already included in this one's hours
     * @type {Array<string>}
     * @memberof ServiceLaborStandardRequestDto
     */
    includedOpCodes?: Array<string>;
    /**
     * Labor hours, decimal hours in tenths (0.1 hr = 6 min)
     * @type {number}
     * @memberof ServiceLaborStandardRequestDto
     */
    laborHours: number;
    /**
     * Vehicle make
     * @type {string}
     * @memberof ServiceLaborStandardRequestDto
     */
    make?: string;
    /**
     * Vehicle model
     * @type {string}
     * @memberof ServiceLaborStandardRequestDto
     */
    model?: string;
    /**
     * Operations sharing this group share setup time and must not be summed naively
     * @type {string}
     * @memberof ServiceLaborStandardRequestDto
     */
    overlapGroup?: string;
    /**
     * Owning location; required when ownerScope is SHOP, rejected otherwise
     * @type {string}
     * @memberof ServiceLaborStandardRequestDto
     */
    ownerLocationId?: string;
    /**
     * Who owns this time: PLATFORM (every location resolves it) or SHOP (one location's own number, which outranks platform rows for that location); defaults to PLATFORM
     * @type {string}
     * @memberof ServiceLaborStandardRequestDto
     */
    ownerScope?: ServiceLaborStandardRequestDtoOwnerScopeEnum;
    /**
     * Date the time was published or decided; omitted means undated
     * @type {Date}
     * @memberof ServiceLaborStandardRequestDto
     */
    publishedAt?: Date;
    /**
     * Vehicle submodel or trim
     * @type {string}
     * @memberof ServiceLaborStandardRequestDto
     */
    submodel?: string;
    /**
     * Kind of published time; defaults to DURION_STANDARD
     * @type {string}
     * @memberof ServiceLaborStandardRequestDto
     */
    timeType?: ServiceLaborStandardRequestDtoTimeTypeEnum;
    /**
     * Model year or year range the time applies to
     * @type {string}
     * @memberof ServiceLaborStandardRequestDto
     */
    vehicleYear?: string;
}

/**
* @export
* @enum {string}
*/
export enum ServiceLaborStandardRequestDtoOwnerScopeEnum {
    Platform = 'PLATFORM',
    Shop = 'SHOP'
}
/**
* @export
* @enum {string}
*/
export enum ServiceLaborStandardRequestDtoTimeTypeEnum {
    RetailFlatRate = 'RETAIL_FLAT_RATE',
    OemWarranty = 'OEM_WARRANTY',
    ManufacturerInstall = 'MANUFACTURER_INSTALL',
    DurionStandard = 'DURION_STANDARD'
}


/**
 * Check if a given object implements the ServiceLaborStandardRequestDto interface.
 */
export function instanceOfServiceLaborStandardRequestDto(value: object): boolean {
    if (!('laborHours' in value)) return false;
    return true;
}

export function ServiceLaborStandardRequestDtoFromJSON(json: any): ServiceLaborStandardRequestDto {
    return ServiceLaborStandardRequestDtoFromJSONTyped(json, false);
}

export function ServiceLaborStandardRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceLaborStandardRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'engineCode': json['engineCode'] == null ? undefined : json['engineCode'],
        'includedOpCodes': json['includedOpCodes'] == null ? undefined : json['includedOpCodes'],
        'laborHours': json['laborHours'],
        'make': json['make'] == null ? undefined : json['make'],
        'model': json['model'] == null ? undefined : json['model'],
        'overlapGroup': json['overlapGroup'] == null ? undefined : json['overlapGroup'],
        'ownerLocationId': json['ownerLocationId'] == null ? undefined : json['ownerLocationId'],
        'ownerScope': json['ownerScope'] == null ? undefined : json['ownerScope'],
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'submodel': json['submodel'] == null ? undefined : json['submodel'],
        'timeType': json['timeType'] == null ? undefined : json['timeType'],
        'vehicleYear': json['vehicleYear'] == null ? undefined : json['vehicleYear'],
    };
}

export function ServiceLaborStandardRequestDtoToJSON(value?: ServiceLaborStandardRequestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'engineCode': value['engineCode'],
        'includedOpCodes': value['includedOpCodes'],
        'laborHours': value['laborHours'],
        'make': value['make'],
        'model': value['model'],
        'overlapGroup': value['overlapGroup'],
        'ownerLocationId': value['ownerLocationId'],
        'ownerScope': value['ownerScope'],
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString().substring(0,10)),
        'submodel': value['submodel'],
        'timeType': value['timeType'],
        'vehicleYear': value['vehicleYear'],
    };
}

