/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Product API
 * API documentation for the Product service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Live vendor stock with a status indicator. A null quantity means the vendor stated nothing; zero means the vendor stated it has none, and only that justifies showing a customer that the vendor is out of stock.
 * @export
 * @interface SupplierAvailabilityInfo
 */
export interface SupplierAvailabilityInfo {
    /**
     * When the supplier fact was obtained. Present only when the vendor answered — a degraded component carries no timestamp, because there is no vendor statement to date. A cached answer carries the age of the fact, not of the cache hit.
     * @type {Date}
     * @memberof SupplierAvailabilityInfo
     */
    asOf?: Date;
    /**
     * Quantity the vendor can supply. Null whenever the status is not OK, and null even under OK when the vendor answered without stating a quantity.
     * @type {number}
     * @memberof SupplierAvailabilityInfo
     */
    availableQuantity?: number;
    /**
     * Confidence in the supplier data
     * @type {string}
     * @memberof SupplierAvailabilityInfo
     */
    confidence: SupplierAvailabilityInfoConfidenceEnum;
    /**
     * Earliest date the vendor promised any quantity, when it stated one.
     * @type {Date}
     * @memberof SupplierAvailabilityInfo
     */
    earliestDeliveryDate?: Date;
    /**
     * Supplier data status
     * @type {string}
     * @memberof SupplierAvailabilityInfo
     */
    status: SupplierAvailabilityInfoStatusEnum;
    /**
     * Whether the vendor carries this product at all. NOT_LISTED is a definite answer; UNAVAILABLE means the vendor holds none right now.
     * @type {string}
     * @memberof SupplierAvailabilityInfo
     */
    vendorStatus?: SupplierAvailabilityInfoVendorStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum SupplierAvailabilityInfoConfidenceEnum {
    Low = 'LOW',
    Medium = 'MEDIUM',
    High = 'HIGH'
}
/**
* @export
* @enum {string}
*/
export enum SupplierAvailabilityInfoStatusEnum {
    Ok = 'OK',
    Unavailable = 'UNAVAILABLE',
    Stale = 'STALE',
    Error = 'ERROR'
}
/**
* @export
* @enum {string}
*/
export enum SupplierAvailabilityInfoVendorStatusEnum {
    Available = 'AVAILABLE',
    Unavailable = 'UNAVAILABLE',
    NotListed = 'NOT_LISTED',
    NotAnswered = 'NOT_ANSWERED'
}


/**
 * Check if a given object implements the SupplierAvailabilityInfo interface.
 */
export function instanceOfSupplierAvailabilityInfo(value: object): boolean {
    if (!('confidence' in value)) return false;
    if (!('status' in value)) return false;
    return true;
}

export function SupplierAvailabilityInfoFromJSON(json: any): SupplierAvailabilityInfo {
    return SupplierAvailabilityInfoFromJSONTyped(json, false);
}

export function SupplierAvailabilityInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplierAvailabilityInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'asOf': json['asOf'] == null ? undefined : (new Date(json['asOf'])),
        'availableQuantity': json['availableQuantity'] == null ? undefined : json['availableQuantity'],
        'confidence': json['confidence'],
        'earliestDeliveryDate': json['earliestDeliveryDate'] == null ? undefined : (new Date(json['earliestDeliveryDate'])),
        'status': json['status'],
        'vendorStatus': json['vendorStatus'] == null ? undefined : json['vendorStatus'],
    };
}

export function SupplierAvailabilityInfoToJSON(value?: SupplierAvailabilityInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'asOf': value['asOf'] == null ? undefined : ((value['asOf']).toISOString()),
        'availableQuantity': value['availableQuantity'],
        'confidence': value['confidence'],
        'earliestDeliveryDate': value['earliestDeliveryDate'] == null ? undefined : ((value['earliestDeliveryDate']).toISOString().substring(0,10)),
        'status': value['status'],
        'vendorStatus': value['vendorStatus'],
    };
}

