/**
 * Positivity Product API
 * API documentation for the Product service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UomConversionCreateRequestDto
 */
export interface UomConversionCreateRequestDto {
    /**
     *
     * @type {string}
     * @memberof UomConversionCreateRequestDto
     */
    fromUomCode: string;
    /**
     *
     * @type {string}
     * @memberof UomConversionCreateRequestDto
     */
    toUomCode: string;
    /**
     *
     * @type {number}
     * @memberof UomConversionCreateRequestDto
     */
    conversionFactor: number;
    /**
     *
     * @type {string}
     * @memberof UomConversionCreateRequestDto
     */
    createdBy?: string;
}
/**
 * Check if a given object implements the UomConversionCreateRequestDto interface.
 */
export declare function instanceOfUomConversionCreateRequestDto(value: object): boolean;
export declare function UomConversionCreateRequestDtoFromJSON(json: any): UomConversionCreateRequestDto;
export declare function UomConversionCreateRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UomConversionCreateRequestDto;
export declare function UomConversionCreateRequestDtoToJSON(value?: UomConversionCreateRequestDto | null): any;
