/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { PurchaseOrderLineRequest } from './PurchaseOrderLineRequest';
/**
 *
 * @export
 * @interface CreatePurchaseOrderRequest
 */
export interface CreatePurchaseOrderRequest {
    /**
     *
     * @type {string}
     * @memberof CreatePurchaseOrderRequest
     */
    vendorId: string;
    /**
     *
     * @type {Date}
     * @memberof CreatePurchaseOrderRequest
     */
    poDate: Date;
    /**
     *
     * @type {string}
     * @memberof CreatePurchaseOrderRequest
     */
    currency: string;
    /**
     *
     * @type {string}
     * @memberof CreatePurchaseOrderRequest
     */
    paymentTermsId?: string;
    /**
     *
     * @type {Date}
     * @memberof CreatePurchaseOrderRequest
     */
    expectedDeliveryDate?: Date;
    /**
     *
     * @type {string}
     * @memberof CreatePurchaseOrderRequest
     */
    shipToLocationId?: string;
    /**
     *
     * @type {string}
     * @memberof CreatePurchaseOrderRequest
     */
    requestedBy?: string;
    /**
     *
     * @type {string}
     * @memberof CreatePurchaseOrderRequest
     */
    comment?: string;
    /**
     *
     * @type {Array<PurchaseOrderLineRequest>}
     * @memberof CreatePurchaseOrderRequest
     */
    lines: Array<PurchaseOrderLineRequest>;
}
/**
 * Check if a given object implements the CreatePurchaseOrderRequest interface.
 */
export declare function instanceOfCreatePurchaseOrderRequest(value: object): boolean;
export declare function CreatePurchaseOrderRequestFromJSON(json: any): CreatePurchaseOrderRequest;
export declare function CreatePurchaseOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePurchaseOrderRequest;
export declare function CreatePurchaseOrderRequestToJSON(value?: CreatePurchaseOrderRequest | null): any;
