"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfLeadTimeView = instanceOfLeadTimeView;
exports.LeadTimeViewFromJSON = LeadTimeViewFromJSON;
exports.LeadTimeViewFromJSONTyped = LeadTimeViewFromJSONTyped;
exports.LeadTimeViewToJSON = LeadTimeViewToJSON;
/**
 * Check if a given object implements the LeadTimeView interface.
 */
function instanceOfLeadTimeView(value) {
    return true;
}
function LeadTimeViewFromJSON(json) {
    return LeadTimeViewFromJSONTyped(json, false);
}
function LeadTimeViewFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'productId': json['productId'] == null ? undefined : json['productId'],
        'locationId': json['locationId'] == null ? undefined : json['locationId'],
        'source': json['source'] == null ? undefined : json['source'],
        'minDays': json['minDays'] == null ? undefined : json['minDays'],
        'maxDays': json['maxDays'] == null ? undefined : json['maxDays'],
        'displayText': json['displayText'] == null ? undefined : json['displayText'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'asOf': json['asOf'] == null ? undefined : (new Date(json['asOf'])),
    };
}
function LeadTimeViewToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'productId': value['productId'],
        'locationId': value['locationId'],
        'source': value['source'],
        'minDays': value['minDays'],
        'maxDays': value['maxDays'],
        'displayText': value['displayText'],
        'confidence': value['confidence'],
        'asOf': value['asOf'] == null ? undefined : ((value['asOf']).toISOString()),
    };
}
