/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PurchaseOrderLineResponse } from './PurchaseOrderLineResponse';
import {
    PurchaseOrderLineResponseFromJSON,
    PurchaseOrderLineResponseFromJSONTyped,
    PurchaseOrderLineResponseToJSON,
} from './PurchaseOrderLineResponse';

/**
 * 
 * @export
 * @interface PurchaseOrderResponse
 */
export interface PurchaseOrderResponse {
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderResponse
     */
    purchaseOrderId?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderResponse
     */
    vendorId?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderResponse
     */
    poNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderResponse
     */
    status?: PurchaseOrderResponseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof PurchaseOrderResponse
     */
    versionNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderResponse
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof PurchaseOrderResponse
     */
    subtotalMinor?: number;
    /**
     * 
     * @type {number}
     * @memberof PurchaseOrderResponse
     */
    taxMinor?: number;
    /**
     * 
     * @type {number}
     * @memberof PurchaseOrderResponse
     */
    grandTotalMinor?: number;
    /**
     * 
     * @type {number}
     * @memberof PurchaseOrderResponse
     */
    openBalanceMinor?: number;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderResponse
     */
    shipToLocationId?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderResponse
     */
    paymentTermsId?: string;
    /**
     * 
     * @type {Date}
     * @memberof PurchaseOrderResponse
     */
    poDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PurchaseOrderResponse
     */
    expectedDeliveryDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderResponse
     */
    requestedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderResponse
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderResponse
     */
    approverId?: string;
    /**
     * 
     * @type {Date}
     * @memberof PurchaseOrderResponse
     */
    approvalTimestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderResponse
     */
    approvalNotes?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderResponse
     */
    encumbranceRef?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderResponse
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderResponse
     */
    updatedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PurchaseOrderResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PurchaseOrderResponse
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Array<PurchaseOrderLineResponse>}
     * @memberof PurchaseOrderResponse
     */
    lines?: Array<PurchaseOrderLineResponse>;
}

/**
* @export
* @enum {string}
*/
export enum PurchaseOrderResponseStatusEnum {
    Draft = 'DRAFT',
    Approved = 'APPROVED',
    PartiallyReceived = 'PARTIALLY_RECEIVED',
    FullyReceived = 'FULLY_RECEIVED',
    Closed = 'CLOSED',
    Cancelled = 'CANCELLED'
}


/**
 * Check if a given object implements the PurchaseOrderResponse interface.
 */
export function instanceOfPurchaseOrderResponse(value: object): boolean {
    return true;
}

export function PurchaseOrderResponseFromJSON(json: any): PurchaseOrderResponse {
    return PurchaseOrderResponseFromJSONTyped(json, false);
}

export function PurchaseOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'purchaseOrderId': json['purchaseOrderId'] == null ? undefined : json['purchaseOrderId'],
        'vendorId': json['vendorId'] == null ? undefined : json['vendorId'],
        'poNumber': json['poNumber'] == null ? undefined : json['poNumber'],
        'status': json['status'] == null ? undefined : json['status'],
        'versionNumber': json['versionNumber'] == null ? undefined : json['versionNumber'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'subtotalMinor': json['subtotalMinor'] == null ? undefined : json['subtotalMinor'],
        'taxMinor': json['taxMinor'] == null ? undefined : json['taxMinor'],
        'grandTotalMinor': json['grandTotalMinor'] == null ? undefined : json['grandTotalMinor'],
        'openBalanceMinor': json['openBalanceMinor'] == null ? undefined : json['openBalanceMinor'],
        'shipToLocationId': json['shipToLocationId'] == null ? undefined : json['shipToLocationId'],
        'paymentTermsId': json['paymentTermsId'] == null ? undefined : json['paymentTermsId'],
        'poDate': json['poDate'] == null ? undefined : (new Date(json['poDate'])),
        'expectedDeliveryDate': json['expectedDeliveryDate'] == null ? undefined : (new Date(json['expectedDeliveryDate'])),
        'requestedBy': json['requestedBy'] == null ? undefined : json['requestedBy'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'approverId': json['approverId'] == null ? undefined : json['approverId'],
        'approvalTimestamp': json['approvalTimestamp'] == null ? undefined : (new Date(json['approvalTimestamp'])),
        'approvalNotes': json['approvalNotes'] == null ? undefined : json['approvalNotes'],
        'encumbranceRef': json['encumbranceRef'] == null ? undefined : json['encumbranceRef'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'lines': json['lines'] == null ? undefined : ((json['lines'] as Array<any>).map(PurchaseOrderLineResponseFromJSON)),
    };
}

export function PurchaseOrderResponseToJSON(value?: PurchaseOrderResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'purchaseOrderId': value['purchaseOrderId'],
        'vendorId': value['vendorId'],
        'poNumber': value['poNumber'],
        'status': value['status'],
        'versionNumber': value['versionNumber'],
        'currency': value['currency'],
        'subtotalMinor': value['subtotalMinor'],
        'taxMinor': value['taxMinor'],
        'grandTotalMinor': value['grandTotalMinor'],
        'openBalanceMinor': value['openBalanceMinor'],
        'shipToLocationId': value['shipToLocationId'],
        'paymentTermsId': value['paymentTermsId'],
        'poDate': value['poDate'] == null ? undefined : ((value['poDate']).toISOString().substring(0,10)),
        'expectedDeliveryDate': value['expectedDeliveryDate'] == null ? undefined : ((value['expectedDeliveryDate']).toISOString().substring(0,10)),
        'requestedBy': value['requestedBy'],
        'comment': value['comment'],
        'approverId': value['approverId'],
        'approvalTimestamp': value['approvalTimestamp'] == null ? undefined : ((value['approvalTimestamp']).toISOString()),
        'approvalNotes': value['approvalNotes'],
        'encumbranceRef': value['encumbranceRef'],
        'createdBy': value['createdBy'],
        'updatedBy': value['updatedBy'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'lines': value['lines'] == null ? undefined : ((value['lines'] as Array<any>).map(PurchaseOrderLineResponseToJSON)),
    };
}

