/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to execute a putaway move from staging to storage, with optional business-rule overrides
 * @export
 * @interface PutawayExecutionRequest
 */
export interface PutawayExecutionRequest {
    /**
     * Identifier of the supervisor who approved the override
     * @type {string}
     * @memberof PutawayExecutionRequest
     */
    approvedBy?: string;
    /**
     * Identifier of the storage location the goods are moved to
     * @type {string}
     * @memberof PutawayExecutionRequest
     */
    destinationLocationId: string;
    /**
     * When true, bypasses the destination capacity check for this move
     * @type {boolean}
     * @memberof PutawayExecutionRequest
     */
    overrideCapacity?: boolean;
    /**
     * Free-text justification supporting the override
     * @type {string}
     * @memberof PutawayExecutionRequest
     */
    overrideJustification?: string;
    /**
     * When true, bypasses the location compatibility check for this move
     * @type {boolean}
     * @memberof PutawayExecutionRequest
     */
    overrideLocationCompatibility?: boolean;
    /**
     * Audit reason code justifying any applied override
     * @type {string}
     * @memberof PutawayExecutionRequest
     */
    overrideReasonCode?: PutawayExecutionRequestOverrideReasonCodeEnum;
    /**
     * Quantity of units to move
     * @type {number}
     * @memberof PutawayExecutionRequest
     */
    quantity: number;
    /**
     * Identifier of the SKU being moved
     * @type {string}
     * @memberof PutawayExecutionRequest
     */
    skuId: string;
    /**
     * Identifier of the staging location the goods are moved from
     * @type {string}
     * @memberof PutawayExecutionRequest
     */
    sourceLocationId: string;
}

/**
* @export
* @enum {string}
*/
export enum PutawayExecutionRequestOverrideReasonCodeEnum {
    CapacityOverride = 'CAPACITY_OVERRIDE',
    LocationCompatibilityOverride = 'LOCATION_COMPATIBILITY_OVERRIDE',
    UrgentFulfillment = 'URGENT_FULFILLMENT',
    AlternateLocation = 'ALTERNATE_LOCATION',
    Other = 'OTHER'
}


/**
 * Check if a given object implements the PutawayExecutionRequest interface.
 */
export function instanceOfPutawayExecutionRequest(value: object): boolean {
    if (!('destinationLocationId' in value)) return false;
    if (!('quantity' in value)) return false;
    if (!('skuId' in value)) return false;
    if (!('sourceLocationId' in value)) return false;
    return true;
}

export function PutawayExecutionRequestFromJSON(json: any): PutawayExecutionRequest {
    return PutawayExecutionRequestFromJSONTyped(json, false);
}

export function PutawayExecutionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutawayExecutionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'approvedBy': json['approvedBy'] == null ? undefined : json['approvedBy'],
        'destinationLocationId': json['destinationLocationId'],
        'overrideCapacity': json['overrideCapacity'] == null ? undefined : json['overrideCapacity'],
        'overrideJustification': json['overrideJustification'] == null ? undefined : json['overrideJustification'],
        'overrideLocationCompatibility': json['overrideLocationCompatibility'] == null ? undefined : json['overrideLocationCompatibility'],
        'overrideReasonCode': json['overrideReasonCode'] == null ? undefined : json['overrideReasonCode'],
        'quantity': json['quantity'],
        'skuId': json['skuId'],
        'sourceLocationId': json['sourceLocationId'],
    };
}

export function PutawayExecutionRequestToJSON(value?: PutawayExecutionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'approvedBy': value['approvedBy'],
        'destinationLocationId': value['destinationLocationId'],
        'overrideCapacity': value['overrideCapacity'],
        'overrideJustification': value['overrideJustification'],
        'overrideLocationCompatibility': value['overrideLocationCompatibility'],
        'overrideReasonCode': value['overrideReasonCode'],
        'quantity': value['quantity'],
        'skuId': value['skuId'],
        'sourceLocationId': value['sourceLocationId'],
    };
}

