/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutawayLineItemRequest
 */
export interface PutawayLineItemRequest {
    /**
     * 
     * @type {string}
     * @memberof PutawayLineItemRequest
     */
    productId: string;
    /**
     * 
     * @type {number}
     * @memberof PutawayLineItemRequest
     */
    quantity: number;
}

/**
 * Check if a given object implements the PutawayLineItemRequest interface.
 */
export function instanceOfPutawayLineItemRequest(value: object): boolean {
    if (!('productId' in value)) return false;
    if (!('quantity' in value)) return false;
    return true;
}

export function PutawayLineItemRequestFromJSON(json: any): PutawayLineItemRequest {
    return PutawayLineItemRequestFromJSONTyped(json, false);
}

export function PutawayLineItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutawayLineItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'],
        'quantity': json['quantity'],
    };
}

export function PutawayLineItemRequestToJSON(value?: PutawayLineItemRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'productId': value['productId'],
        'quantity': value['quantity'],
    };
}

