"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfReallocateResponse = instanceOfReallocateResponse;
exports.ReallocateResponseFromJSON = ReallocateResponseFromJSON;
exports.ReallocateResponseFromJSONTyped = ReallocateResponseFromJSONTyped;
exports.ReallocateResponseToJSON = ReallocateResponseToJSON;
/**
 * Check if a given object implements the ReallocateResponse interface.
 */
function instanceOfReallocateResponse(value) {
    return true;
}
function ReallocateResponseFromJSON(json) {
    return ReallocateResponseFromJSONTyped(json, false);
}
function ReallocateResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'stockItemId': json['stockItemId'] == null ? undefined : json['stockItemId'],
        'totalReallocated': json['totalReallocated'] == null ? undefined : json['totalReallocated'],
        'auditRecordsCreated': json['auditRecordsCreated'] == null ? undefined : json['auditRecordsCreated'],
        'atpAfterReallocation': json['atpAfterReallocation'] == null ? undefined : json['atpAfterReallocation'],
    };
}
function ReallocateResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'stockItemId': value['stockItemId'],
        'totalReallocated': value['totalReallocated'],
        'auditRecordsCreated': value['auditRecordsCreated'],
        'atpAfterReallocation': value['atpAfterReallocation'],
    };
}
