/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferQuantityLineRequest } from './TransferQuantityLineRequest';
import {
    TransferQuantityLineRequestFromJSON,
    TransferQuantityLineRequestFromJSONTyped,
    TransferQuantityLineRequestToJSON,
} from './TransferQuantityLineRequest';

/**
 * Request to receive a transfer order; omitted lines receive their full remainder
 * @export
 * @interface ReceiveTransferOrderRequest
 */
export interface ReceiveTransferOrderRequest {
    /**
     * Explicit per-line received quantities; omitted lines receive their full remainder
     * @type {Array<TransferQuantityLineRequest>}
     * @memberof ReceiveTransferOrderRequest
     */
    lines?: Array<TransferQuantityLineRequest>;
}

/**
 * Check if a given object implements the ReceiveTransferOrderRequest interface.
 */
export function instanceOfReceiveTransferOrderRequest(value: object): boolean {
    return true;
}

export function ReceiveTransferOrderRequestFromJSON(json: any): ReceiveTransferOrderRequest {
    return ReceiveTransferOrderRequestFromJSONTyped(json, false);
}

export function ReceiveTransferOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiveTransferOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'lines': json['lines'] == null ? undefined : ((json['lines'] as Array<any>).map(TransferQuantityLineRequestFromJSON)),
    };
}

export function ReceiveTransferOrderRequestToJSON(value?: ReceiveTransferOrderRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'lines': value['lines'] == null ? undefined : ((value['lines'] as Array<any>).map(TransferQuantityLineRequestToJSON)),
    };
}

