/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Summary of a batch replenishment scan run over all replenishment policies
 * @export
 * @interface ReplenishmentScanResultResponse
 */
export interface ReplenishmentScanResultResponse {
    /**
     * Number of policies whose on-hand quantity was below the configured minimum
     * @type {number}
     * @memberof ReplenishmentScanResultResponse
     */
    policiesBelowMinimum: number;
    /**
     * Number of replenishment policies evaluated by the scan
     * @type {number}
     * @memberof ReplenishmentScanResultResponse
     */
    policiesEvaluated: number;
    /**
     * Number of policies skipped without evaluation because they are inactive or snoozed
     * @type {number}
     * @memberof ReplenishmentScanResultResponse
     */
    policiesSkipped: number;
    /**
     * Timestamp at which the scan ran
     * @type {string}
     * @memberof ReplenishmentScanResultResponse
     */
    scanAt: string;
    /**
     * Number of new purchase suggestions created for PURCHASE-preferring policies (odoo-parity F4)
     * @type {number}
     * @memberof ReplenishmentScanResultResponse
     */
    suggestionsCreated: number;
    /**
     * Number of already-open purchase suggestions whose quantity was refreshed to the current need (odoo-parity F4)
     * @type {number}
     * @memberof ReplenishmentScanResultResponse
     */
    suggestionsRefreshed: number;
    /**
     * Number of new replenishment tasks created by the scan
     * @type {number}
     * @memberof ReplenishmentScanResultResponse
     */
    tasksCreated: number;
    /**
     * Number of already-open replenishment tasks whose quantity was refreshed to the current need
     * @type {number}
     * @memberof ReplenishmentScanResultResponse
     */
    tasksRefreshed: number;
}

/**
 * Check if a given object implements the ReplenishmentScanResultResponse interface.
 */
export function instanceOfReplenishmentScanResultResponse(value: object): boolean {
    if (!('policiesBelowMinimum' in value)) return false;
    if (!('policiesEvaluated' in value)) return false;
    if (!('policiesSkipped' in value)) return false;
    if (!('scanAt' in value)) return false;
    if (!('suggestionsCreated' in value)) return false;
    if (!('suggestionsRefreshed' in value)) return false;
    if (!('tasksCreated' in value)) return false;
    if (!('tasksRefreshed' in value)) return false;
    return true;
}

export function ReplenishmentScanResultResponseFromJSON(json: any): ReplenishmentScanResultResponse {
    return ReplenishmentScanResultResponseFromJSONTyped(json, false);
}

export function ReplenishmentScanResultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplenishmentScanResultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'policiesBelowMinimum': json['policiesBelowMinimum'],
        'policiesEvaluated': json['policiesEvaluated'],
        'policiesSkipped': json['policiesSkipped'],
        'scanAt': json['scanAt'],
        'suggestionsCreated': json['suggestionsCreated'],
        'suggestionsRefreshed': json['suggestionsRefreshed'],
        'tasksCreated': json['tasksCreated'],
        'tasksRefreshed': json['tasksRefreshed'],
    };
}

export function ReplenishmentScanResultResponseToJSON(value?: ReplenishmentScanResultResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'policiesBelowMinimum': value['policiesBelowMinimum'],
        'policiesEvaluated': value['policiesEvaluated'],
        'policiesSkipped': value['policiesSkipped'],
        'scanAt': value['scanAt'],
        'suggestionsCreated': value['suggestionsCreated'],
        'suggestionsRefreshed': value['suggestionsRefreshed'],
        'tasksCreated': value['tasksCreated'],
        'tasksRefreshed': value['tasksRefreshed'],
    };
}

