/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ReservationResponse
 */
export interface ReservationResponse {
    /**
     *
     * @type {string}
     * @memberof ReservationResponse
     */
    reservationId?: string;
    /**
     *
     * @type {string}
     * @memberof ReservationResponse
     */
    workorderLineId?: string;
    /**
     *
     * @type {string}
     * @memberof ReservationResponse
     */
    stockItemId?: string;
    /**
     *
     * @type {number}
     * @memberof ReservationResponse
     */
    requiredQuantity?: number;
    /**
     *
     * @type {number}
     * @memberof ReservationResponse
     */
    allocatedQuantity?: number;
    /**
     *
     * @type {string}
     * @memberof ReservationResponse
     */
    status?: string;
}
/**
 * Check if a given object implements the ReservationResponse interface.
 */
export declare function instanceOfReservationResponse(value: object): boolean;
export declare function ReservationResponseFromJSON(json: any): ReservationResponse;
export declare function ReservationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationResponse;
export declare function ReservationResponseToJSON(value?: ReservationResponse | null): any;
