/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Outcome of a return submission, summarizing how many lines were processed
 * @export
 * @interface ReturnSubmissionResultDto
 */
export interface ReturnSubmissionResultDto {
    /**
     * Timestamp when the return was processed
     * @type {Date}
     * @memberof ReturnSubmissionResultDto
     */
    processedAt: Date;
    /**
     * Number of return lines that were processed
     * @type {number}
     * @memberof ReturnSubmissionResultDto
     */
    processedLines: number;
    /**
     * Identifier of the created return record
     * @type {string}
     * @memberof ReturnSubmissionResultDto
     */
    returnId: string;
    /**
     * Status of the return submission
     * @type {string}
     * @memberof ReturnSubmissionResultDto
     */
    status: string;
    /**
     * Identifier of the workorder the return was submitted against
     * @type {string}
     * @memberof ReturnSubmissionResultDto
     */
    workorderId: string;
}

/**
 * Check if a given object implements the ReturnSubmissionResultDto interface.
 */
export function instanceOfReturnSubmissionResultDto(value: object): boolean {
    if (!('processedAt' in value)) return false;
    if (!('processedLines' in value)) return false;
    if (!('returnId' in value)) return false;
    if (!('status' in value)) return false;
    if (!('workorderId' in value)) return false;
    return true;
}

export function ReturnSubmissionResultDtoFromJSON(json: any): ReturnSubmissionResultDto {
    return ReturnSubmissionResultDtoFromJSONTyped(json, false);
}

export function ReturnSubmissionResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturnSubmissionResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'processedAt': (new Date(json['processedAt'])),
        'processedLines': json['processedLines'],
        'returnId': json['returnId'],
        'status': json['status'],
        'workorderId': json['workorderId'],
    };
}

export function ReturnSubmissionResultDtoToJSON(value?: ReturnSubmissionResultDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'processedAt': ((value['processedAt']).toISOString()),
        'processedLines': value['processedLines'],
        'returnId': value['returnId'],
        'status': value['status'],
        'workorderId': value['workorderId'],
    };
}

