/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RollupQuantities } from './RollupQuantities';
import {
    RollupQuantitiesFromJSON,
    RollupQuantitiesFromJSONTyped,
    RollupQuantitiesToJSON,
} from './RollupQuantities';
import type { StorageLocationRollupNode } from './StorageLocationRollupNode';
import {
    StorageLocationRollupNodeFromJSON,
    StorageLocationRollupNodeFromJSONTyped,
    StorageLocationRollupNodeToJSON,
} from './StorageLocationRollupNode';

/**
 * Site inventory rollup with quantities subtotaled along the storage-location hierarchy
 * @export
 * @interface SiteInventoryRollupResponse
 */
export interface SiteInventoryRollupResponse {
    /**
     * Root storage locations of the site topology
     * @type {Array<StorageLocationRollupNode>}
     * @memberof SiteInventoryRollupResponse
     */
    nodes: Array<StorageLocationRollupNode>;
    /**
     * Site (Location) identifier
     * @type {string}
     * @memberof SiteInventoryRollupResponse
     */
    siteId: string;
    /**
     * 
     * @type {RollupQuantities}
     * @memberof SiteInventoryRollupResponse
     */
    totals: RollupQuantities;
}

/**
 * Check if a given object implements the SiteInventoryRollupResponse interface.
 */
export function instanceOfSiteInventoryRollupResponse(value: object): boolean {
    if (!('nodes' in value)) return false;
    if (!('siteId' in value)) return false;
    if (!('totals' in value)) return false;
    return true;
}

export function SiteInventoryRollupResponseFromJSON(json: any): SiteInventoryRollupResponse {
    return SiteInventoryRollupResponseFromJSONTyped(json, false);
}

export function SiteInventoryRollupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteInventoryRollupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'nodes': ((json['nodes'] as Array<any>).map(StorageLocationRollupNodeFromJSON)),
        'siteId': json['siteId'],
        'totals': RollupQuantitiesFromJSON(json['totals']),
    };
}

export function SiteInventoryRollupResponseToJSON(value?: SiteInventoryRollupResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nodes': ((value['nodes'] as Array<any>).map(StorageLocationRollupNodeToJSON)),
        'siteId': value['siteId'],
        'totals': RollupQuantitiesToJSON(value['totals']),
    };
}

