/* tslint:disable */
/* eslint-disable */
/**
 * POS Human Resources Service API
 * Human Resources service for employee management, payroll, and benefits administration
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PersonBulkIngestRecord } from './PersonBulkIngestRecord';
import {
    PersonBulkIngestRecordFromJSON,
    PersonBulkIngestRecordFromJSONTyped,
    PersonBulkIngestRecordToJSON,
} from './PersonBulkIngestRecord';

/**
 * 
 * @export
 * @interface BulkIngestRequestPersonBulkIngestRecord
 */
export interface BulkIngestRequestPersonBulkIngestRecord {
    /**
     * 
     * @type {string}
     * @memberof BulkIngestRequestPersonBulkIngestRecord
     */
    jobId: string;
    /**
     * 
     * @type {string}
     * @memberof BulkIngestRequestPersonBulkIngestRecord
     */
    locationId: string;
    /**
     * 
     * @type {Array<PersonBulkIngestRecord>}
     * @memberof BulkIngestRequestPersonBulkIngestRecord
     */
    records: Array<PersonBulkIngestRecord>;
    /**
     * 
     * @type {string}
     * @memberof BulkIngestRequestPersonBulkIngestRecord
     */
    operatorId?: string;
}

/**
 * Check if a given object implements the BulkIngestRequestPersonBulkIngestRecord interface.
 */
export function instanceOfBulkIngestRequestPersonBulkIngestRecord(value: object): boolean {
    if (!('jobId' in value)) return false;
    if (!('locationId' in value)) return false;
    if (!('records' in value)) return false;
    return true;
}

export function BulkIngestRequestPersonBulkIngestRecordFromJSON(json: any): BulkIngestRequestPersonBulkIngestRecord {
    return BulkIngestRequestPersonBulkIngestRecordFromJSONTyped(json, false);
}

export function BulkIngestRequestPersonBulkIngestRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkIngestRequestPersonBulkIngestRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'],
        'locationId': json['locationId'],
        'records': ((json['records'] as Array<any>).map(PersonBulkIngestRecordFromJSON)),
        'operatorId': json['operatorId'] == null ? undefined : json['operatorId'],
    };
}

export function BulkIngestRequestPersonBulkIngestRecordToJSON(value?: BulkIngestRequestPersonBulkIngestRecord | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jobId': value['jobId'],
        'locationId': value['locationId'],
        'records': ((value['records'] as Array<any>).map(PersonBulkIngestRecordToJSON)),
        'operatorId': value['operatorId'],
    };
}

