/**
 * POS Human Resources Service API
 * Human Resources service for employee management, payroll, and benefits administration
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PersonRoleAssignmentRequest
 */
export interface PersonRoleAssignmentRequest {
    /**
     *
     * @type {string}
     * @memberof PersonRoleAssignmentRequest
     */
    roleCode: string;
    /**
     *
     * @type {string}
     * @memberof PersonRoleAssignmentRequest
     */
    locationId?: string;
    /**
     *
     * @type {Date}
     * @memberof PersonRoleAssignmentRequest
     */
    startDate?: Date;
    /**
     *
     * @type {Date}
     * @memberof PersonRoleAssignmentRequest
     */
    endDate?: Date;
}
/**
 * Check if a given object implements the PersonRoleAssignmentRequest interface.
 */
export declare function instanceOfPersonRoleAssignmentRequest(value: object): boolean;
export declare function PersonRoleAssignmentRequestFromJSON(json: any): PersonRoleAssignmentRequest;
export declare function PersonRoleAssignmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonRoleAssignmentRequest;
export declare function PersonRoleAssignmentRequestToJSON(value?: PersonRoleAssignmentRequest | null): any;
