/* tslint:disable */
/* eslint-disable */
/**
 * POS Human Resources Service API
 * Human Resources service for employee management, payroll, and benefits administration
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One person's assignment to a location for a role
 * @export
 * @interface StaffingAssignmentBulkIngestRecord
 */
export interface StaffingAssignmentBulkIngestRecord {
    /**
     * First day of the assignment; defaults to today when omitted, since a seeded roster is current as of the load rather than backdated.
     * @type {Date}
     * @memberof StaffingAssignmentBulkIngestRecord
     */
    effectiveFrom?: Date;
    /**
     * Last day of the assignment; open-ended when omitted
     * @type {Date}
     * @memberof StaffingAssignmentBulkIngestRecord
     */
    effectiveTo?: Date;
    /**
     * Employee number of the person being assigned. Resolved to a person id here, so a file can be written without knowing ids the pipeline generates.
     * @type {string}
     * @memberof StaffingAssignmentBulkIngestRecord
     */
    employeeNumber: string;
    /**
     * Location the person is assigned to. Defaults to the request's locationId when omitted.
     * @type {string}
     * @memberof StaffingAssignmentBulkIngestRecord
     */
    locationId?: string;
    /**
     * Whether this is the person's primary assignment
     * @type {boolean}
     * @memberof StaffingAssignmentBulkIngestRecord
     */
    primary?: boolean;
    /**
     * Role at that location
     * @type {string}
     * @memberof StaffingAssignmentBulkIngestRecord
     */
    role: string;
}

/**
 * Check if a given object implements the StaffingAssignmentBulkIngestRecord interface.
 */
export function instanceOfStaffingAssignmentBulkIngestRecord(value: object): boolean {
    if (!('employeeNumber' in value)) return false;
    if (!('role' in value)) return false;
    return true;
}

export function StaffingAssignmentBulkIngestRecordFromJSON(json: any): StaffingAssignmentBulkIngestRecord {
    return StaffingAssignmentBulkIngestRecordFromJSONTyped(json, false);
}

export function StaffingAssignmentBulkIngestRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffingAssignmentBulkIngestRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'effectiveFrom': json['effectiveFrom'] == null ? undefined : (new Date(json['effectiveFrom'])),
        'effectiveTo': json['effectiveTo'] == null ? undefined : (new Date(json['effectiveTo'])),
        'employeeNumber': json['employeeNumber'],
        'locationId': json['locationId'] == null ? undefined : json['locationId'],
        'primary': json['primary'] == null ? undefined : json['primary'],
        'role': json['role'],
    };
}

export function StaffingAssignmentBulkIngestRecordToJSON(value?: StaffingAssignmentBulkIngestRecord | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'effectiveFrom': value['effectiveFrom'] == null ? undefined : ((value['effectiveFrom']).toISOString().substring(0,10)),
        'effectiveTo': value['effectiveTo'] == null ? undefined : ((value['effectiveTo']).toISOString().substring(0,10)),
        'employeeNumber': value['employeeNumber'],
        'locationId': value['locationId'],
        'primary': value['primary'],
        'role': value['role'],
    };
}

