"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * POS Human Resources Service API
 * Human Resources service for employee management, payroll, and benefits administration
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfWorkSessionDto = instanceOfWorkSessionDto;
exports.WorkSessionDtoFromJSON = WorkSessionDtoFromJSON;
exports.WorkSessionDtoFromJSONTyped = WorkSessionDtoFromJSONTyped;
exports.WorkSessionDtoToJSON = WorkSessionDtoToJSON;
/**
 * Check if a given object implements the WorkSessionDto interface.
 */
function instanceOfWorkSessionDto(value) {
    return true;
}
function WorkSessionDtoFromJSON(json) {
    return WorkSessionDtoFromJSONTyped(json, false);
}
function WorkSessionDtoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'personId': json['personId'] == null ? undefined : json['personId'],
        'status': json['status'] == null ? undefined : json['status'],
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'endedAt': json['endedAt'] == null ? undefined : (new Date(json['endedAt'])),
    };
}
function WorkSessionDtoToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'sessionId': value['sessionId'],
        'personId': value['personId'],
        'status': value['status'],
        'startedAt': value['startedAt'] == null ? undefined : ((value['startedAt']).toISOString()),
        'endedAt': value['endedAt'] == null ? undefined : ((value['endedAt']).toISOString()),
    };
}
