/* tslint:disable */
/* eslint-disable */
/**
 * POS Human Resources Service API
 * Human Resources service for employee management, payroll, and benefits administration
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Work session representing a tracked period of work for a person
 * @export
 * @interface WorkSessionDto
 */
export interface WorkSessionDto {
    /**
     * Total billable minutes for the session
     * @type {number}
     * @memberof WorkSessionDto
     */
    billableMinutes?: number;
    /**
     * Total break minutes for the session
     * @type {number}
     * @memberof WorkSessionDto
     */
    breakMinutes?: number;
    /**
     * Timestamp the session ended
     * @type {Date}
     * @memberof WorkSessionDto
     */
    endedAt?: Date;
    /**
     * Person the session belongs to
     * @type {string}
     * @memberof WorkSessionDto
     */
    personId: string;
    /**
     * Work session identifier
     * @type {string}
     * @memberof WorkSessionDto
     */
    sessionId: string;
    /**
     * Timestamp the session started
     * @type {Date}
     * @memberof WorkSessionDto
     */
    startedAt?: Date;
    /**
     * Lifecycle status of the session
     * @type {string}
     * @memberof WorkSessionDto
     */
    status: string;
    /**
     * Timestamp the session was submitted
     * @type {Date}
     * @memberof WorkSessionDto
     */
    submittedAt?: Date;
}

/**
 * Check if a given object implements the WorkSessionDto interface.
 */
export function instanceOfWorkSessionDto(value: object): boolean {
    if (!('personId' in value)) return false;
    if (!('sessionId' in value)) return false;
    if (!('status' in value)) return false;
    return true;
}

export function WorkSessionDtoFromJSON(json: any): WorkSessionDto {
    return WorkSessionDtoFromJSONTyped(json, false);
}

export function WorkSessionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkSessionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'billableMinutes': json['billableMinutes'] == null ? undefined : json['billableMinutes'],
        'breakMinutes': json['breakMinutes'] == null ? undefined : json['breakMinutes'],
        'endedAt': json['endedAt'] == null ? undefined : (new Date(json['endedAt'])),
        'personId': json['personId'],
        'sessionId': json['sessionId'],
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'status': json['status'],
        'submittedAt': json['submittedAt'] == null ? undefined : (new Date(json['submittedAt'])),
    };
}

export function WorkSessionDtoToJSON(value?: WorkSessionDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'billableMinutes': value['billableMinutes'],
        'breakMinutes': value['breakMinutes'],
        'endedAt': value['endedAt'] == null ? undefined : ((value['endedAt']).toISOString()),
        'personId': value['personId'],
        'sessionId': value['sessionId'],
        'startedAt': value['startedAt'] == null ? undefined : ((value['startedAt']).toISOString()),
        'status': value['status'],
        'submittedAt': value['submittedAt'] == null ? undefined : ((value['submittedAt']).toISOString()),
    };
}

