/* tslint:disable */
/* eslint-disable */
/**
 * POS Security Service API
 * API documentation for POS Security Service
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Lifecycle and lock state of a user account
 * @export
 * @interface AccountStateResponse
 */
export interface AccountStateResponse {
    /**
     * Timestamp at which the account expires
     * @type {Date}
     * @memberof AccountStateResponse
     */
    accountExpiresAt?: Date;
    /**
     * True when the account has not expired
     * @type {boolean}
     * @memberof AccountStateResponse
     */
    accountNonExpired: boolean;
    /**
     * True when the account is not locked
     * @type {boolean}
     * @memberof AccountStateResponse
     */
    accountNonLocked: boolean;
    /**
     * Timestamp at which the credentials expire
     * @type {Date}
     * @memberof AccountStateResponse
     */
    credentialsExpireAt?: Date;
    /**
     * True when the credentials have not expired
     * @type {boolean}
     * @memberof AccountStateResponse
     */
    credentialsNonExpired: boolean;
    /**
     * Timestamp at which the account was disabled
     * @type {Date}
     * @memberof AccountStateResponse
     */
    disabledAt?: Date;
    /**
     * Actor that disabled the account
     * @type {string}
     * @memberof AccountStateResponse
     */
    disabledBy?: string;
    /**
     * True when the account is enabled
     * @type {boolean}
     * @memberof AccountStateResponse
     */
    enabled: boolean;
    /**
     * Number of consecutive failed login attempts
     * @type {number}
     * @memberof AccountStateResponse
     */
    failedLoginAttempts: number;
    /**
     * Timestamp at which the account was locked
     * @type {Date}
     * @memberof AccountStateResponse
     */
    lockedAt?: Date;
    /**
     * Timestamp until which the account remains locked
     * @type {Date}
     * @memberof AccountStateResponse
     */
    lockedUntil?: Date;
    /**
     * User identifier
     * @type {string}
     * @memberof AccountStateResponse
     */
    userId: string;
}

/**
 * Check if a given object implements the AccountStateResponse interface.
 */
export function instanceOfAccountStateResponse(value: object): boolean {
    if (!('accountNonExpired' in value)) return false;
    if (!('accountNonLocked' in value)) return false;
    if (!('credentialsNonExpired' in value)) return false;
    if (!('enabled' in value)) return false;
    if (!('failedLoginAttempts' in value)) return false;
    if (!('userId' in value)) return false;
    return true;
}

export function AccountStateResponseFromJSON(json: any): AccountStateResponse {
    return AccountStateResponseFromJSONTyped(json, false);
}

export function AccountStateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountStateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accountExpiresAt': json['accountExpiresAt'] == null ? undefined : (new Date(json['accountExpiresAt'])),
        'accountNonExpired': json['accountNonExpired'],
        'accountNonLocked': json['accountNonLocked'],
        'credentialsExpireAt': json['credentialsExpireAt'] == null ? undefined : (new Date(json['credentialsExpireAt'])),
        'credentialsNonExpired': json['credentialsNonExpired'],
        'disabledAt': json['disabledAt'] == null ? undefined : (new Date(json['disabledAt'])),
        'disabledBy': json['disabledBy'] == null ? undefined : json['disabledBy'],
        'enabled': json['enabled'],
        'failedLoginAttempts': json['failedLoginAttempts'],
        'lockedAt': json['lockedAt'] == null ? undefined : (new Date(json['lockedAt'])),
        'lockedUntil': json['lockedUntil'] == null ? undefined : (new Date(json['lockedUntil'])),
        'userId': json['userId'],
    };
}

export function AccountStateResponseToJSON(value?: AccountStateResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accountExpiresAt': value['accountExpiresAt'] == null ? undefined : ((value['accountExpiresAt']).toISOString()),
        'accountNonExpired': value['accountNonExpired'],
        'accountNonLocked': value['accountNonLocked'],
        'credentialsExpireAt': value['credentialsExpireAt'] == null ? undefined : ((value['credentialsExpireAt']).toISOString()),
        'credentialsNonExpired': value['credentialsNonExpired'],
        'disabledAt': value['disabledAt'] == null ? undefined : ((value['disabledAt']).toISOString()),
        'disabledBy': value['disabledBy'],
        'enabled': value['enabled'],
        'failedLoginAttempts': value['failedLoginAttempts'],
        'lockedAt': value['lockedAt'] == null ? undefined : ((value['lockedAt']).toISOString()),
        'lockedUntil': value['lockedUntil'] == null ? undefined : ((value['lockedUntil']).toISOString()),
        'userId': value['userId'],
    };
}

