/**
 * POS Security Service API
 * API documentation for POS Security Service
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PermissionDefinition
 */
export interface PermissionDefinition {
    /**
     *
     * @type {string}
     * @memberof PermissionDefinition
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof PermissionDefinition
     */
    description?: string;
}
/**
 * Check if a given object implements the PermissionDefinition interface.
 */
export declare function instanceOfPermissionDefinition(value: object): boolean;
export declare function PermissionDefinitionFromJSON(json: any): PermissionDefinition;
export declare function PermissionDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionDefinition;
export declare function PermissionDefinitionToJSON(value?: PermissionDefinition | null): any;
