/* tslint:disable */
/* eslint-disable */
/**
 * POS Security Service API
 * API documentation for POS Security Service
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionDecodeRequest
 */
export interface PermissionDecodeRequest {
    /**
     * 
     * @type {string}
     * @memberof PermissionDecodeRequest
     */
    permBits: string;
    /**
     * 
     * @type {number}
     * @memberof PermissionDecodeRequest
     */
    permVer?: number;
}

/**
 * Check if a given object implements the PermissionDecodeRequest interface.
 */
export function instanceOfPermissionDecodeRequest(value: object): boolean {
    if (!('permBits' in value)) return false;
    return true;
}

export function PermissionDecodeRequestFromJSON(json: any): PermissionDecodeRequest {
    return PermissionDecodeRequestFromJSONTyped(json, false);
}

export function PermissionDecodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionDecodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'permBits': json['perm_bits'],
        'permVer': json['perm_ver'] == null ? undefined : json['perm_ver'],
    };
}

export function PermissionDecodeRequestToJSON(value?: PermissionDecodeRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'perm_bits': value['permBits'],
        'perm_ver': value['permVer'],
    };
}

