/* tslint:disable */
/* eslint-disable */
/**
 * POS Security Service API
 * API documentation for POS Security Service
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionRegistrationResponse
 */
export interface PermissionRegistrationResponse {
    /**
     * 
     * @type {boolean}
     * @memberof PermissionRegistrationResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PermissionRegistrationResponse
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof PermissionRegistrationResponse
     */
    totalPermissions?: number;
    /**
     * 
     * @type {number}
     * @memberof PermissionRegistrationResponse
     */
    registeredPermissions?: number;
    /**
     * 
     * @type {number}
     * @memberof PermissionRegistrationResponse
     */
    updatedPermissions?: number;
    /**
     * 
     * @type {number}
     * @memberof PermissionRegistrationResponse
     */
    skippedPermissions?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof PermissionRegistrationResponse
     */
    errors?: Array<string>;
}

/**
 * Check if a given object implements the PermissionRegistrationResponse interface.
 */
export function instanceOfPermissionRegistrationResponse(value: object): boolean {
    return true;
}

export function PermissionRegistrationResponseFromJSON(json: any): PermissionRegistrationResponse {
    return PermissionRegistrationResponseFromJSONTyped(json, false);
}

export function PermissionRegistrationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionRegistrationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'totalPermissions': json['totalPermissions'] == null ? undefined : json['totalPermissions'],
        'registeredPermissions': json['registeredPermissions'] == null ? undefined : json['registeredPermissions'],
        'updatedPermissions': json['updatedPermissions'] == null ? undefined : json['updatedPermissions'],
        'skippedPermissions': json['skippedPermissions'] == null ? undefined : json['skippedPermissions'],
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function PermissionRegistrationResponseToJSON(value?: PermissionRegistrationResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'message': value['message'],
        'totalPermissions': value['totalPermissions'],
        'registeredPermissions': value['registeredPermissions'],
        'updatedPermissions': value['updatedPermissions'],
        'skippedPermissions': value['skippedPermissions'],
        'errors': value['errors'],
    };
}

