/* tslint:disable */
/* eslint-disable */
/**
 * POS Security Service API
 * API documentation for POS Security Service
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PricingRuleTraceEntryDto } from './PricingRuleTraceEntryDto';
import {
    PricingRuleTraceEntryDtoFromJSON,
    PricingRuleTraceEntryDtoFromJSONTyped,
    PricingRuleTraceEntryDtoToJSON,
} from './PricingRuleTraceEntryDto';

/**
 * Pricing snapshot including its rule-evaluation trace
 * @export
 * @interface PricingSnapshotDto
 */
export interface PricingSnapshotDto {
    /**
     * Ordered rule-evaluation steps that produced the price
     * @type {Array<PricingRuleTraceEntryDto>}
     * @memberof PricingSnapshotDto
     */
    evaluationSteps?: Array<PricingRuleTraceEntryDto>;
    /**
     * Final computed price
     * @type {number}
     * @memberof PricingSnapshotDto
     */
    finalPrice: number;
    /**
     * Serialized quote context evaluated
     * @type {string}
     * @memberof PricingSnapshotDto
     */
    quoteContext?: string;
    /**
     * Snapshot identifier
     * @type {string}
     * @memberof PricingSnapshotDto
     */
    snapshotId: string;
    /**
     * Timestamp the snapshot was captured
     * @type {Date}
     * @memberof PricingSnapshotDto
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the PricingSnapshotDto interface.
 */
export function instanceOfPricingSnapshotDto(value: object): boolean {
    if (!('finalPrice' in value)) return false;
    if (!('snapshotId' in value)) return false;
    if (!('timestamp' in value)) return false;
    return true;
}

export function PricingSnapshotDtoFromJSON(json: any): PricingSnapshotDto {
    return PricingSnapshotDtoFromJSONTyped(json, false);
}

export function PricingSnapshotDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricingSnapshotDto {
    if (json == null) {
        return json;
    }
    return {
        
        'evaluationSteps': json['evaluationSteps'] == null ? undefined : ((json['evaluationSteps'] as Array<any>).map(PricingRuleTraceEntryDtoFromJSON)),
        'finalPrice': json['finalPrice'],
        'quoteContext': json['quoteContext'] == null ? undefined : json['quoteContext'],
        'snapshotId': json['snapshotId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function PricingSnapshotDtoToJSON(value?: PricingSnapshotDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'evaluationSteps': value['evaluationSteps'] == null ? undefined : ((value['evaluationSteps'] as Array<any>).map(PricingRuleTraceEntryDtoToJSON)),
        'finalPrice': value['finalPrice'],
        'quoteContext': value['quoteContext'],
        'snapshotId': value['snapshotId'],
        'timestamp': ((value['timestamp']).toISOString()),
    };
}

