"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Price API
 * Price service for managing product pricing and discounts
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPriceQuoteRequest = instanceOfPriceQuoteRequest;
exports.PriceQuoteRequestFromJSON = PriceQuoteRequestFromJSON;
exports.PriceQuoteRequestFromJSONTyped = PriceQuoteRequestFromJSONTyped;
exports.PriceQuoteRequestToJSON = PriceQuoteRequestToJSON;
/**
 * Check if a given object implements the PriceQuoteRequest interface.
 */
function instanceOfPriceQuoteRequest(value) {
    if (!('productId' in value))
        return false;
    if (!('quantity' in value))
        return false;
    if (!('locationId' in value))
        return false;
    if (!('customerTierId' in value))
        return false;
    return true;
}
function PriceQuoteRequestFromJSON(json) {
    return PriceQuoteRequestFromJSONTyped(json, false);
}
function PriceQuoteRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'productId': json['productId'],
        'quantity': json['quantity'],
        'locationId': json['locationId'],
        'customerTierId': json['customerTierId'],
        'effectiveTimestamp': json['effectiveTimestamp'] == null ? undefined : (new Date(json['effectiveTimestamp'])),
    };
}
function PriceQuoteRequestToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'productId': value['productId'],
        'quantity': value['quantity'],
        'locationId': value['locationId'],
        'customerTierId': value['customerTierId'],
        'effectiveTimestamp': value['effectiveTimestamp'] == null ? undefined : ((value['effectiveTimestamp']).toISOString()),
    };
}
