"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * POS Shop Manager Service API
 * Shop Manager service for managing shop operations and staff
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.AppointmentsAPIApi = void 0;
const runtime = __importStar(require("../runtime"));
const index_1 = require("../models/index");
/**
 *
 */
class AppointmentsAPIApi extends runtime.BaseAPI {
    /**
     * Cancel a scheduled appointment
     * Cancel appointment
     */
    cancelAppointmentRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            if (requestParameters['appointmentId'] == null) {
                throw new runtime.RequiredError('appointmentId', 'Required parameter "appointmentId" was null or undefined when calling cancelAppointment().');
            }
            if (requestParameters['cancelAppointmentRequest'] == null) {
                throw new runtime.RequiredError('cancelAppointmentRequest', 'Required parameter "cancelAppointmentRequest" was null or undefined when calling cancelAppointment().');
            }
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            const response = yield this.request({
                path: `/v1/appointments/{appointmentId}/cancel`.replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters['appointmentId']))),
                method: 'DELETE',
                headers: headerParameters,
                query: queryParameters,
                body: (0, index_1.CancelAppointmentRequestToJSON)(requestParameters['cancelAppointmentRequest']),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.AppointmentResponseFromJSON)(jsonValue));
        });
    }
    /**
     * Cancel a scheduled appointment
     * Cancel appointment
     */
    cancelAppointment(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.cancelAppointmentRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     * Create a new appointment
     * Create appointment
     */
    createAppointmentRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            if (requestParameters['appointmentCreateRequest'] == null) {
                throw new runtime.RequiredError('appointmentCreateRequest', 'Required parameter "appointmentCreateRequest" was null or undefined when calling createAppointment().');
            }
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            if (requestParameters['idempotencyKey'] != null) {
                headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
            }
            if (requestParameters['xCorrelationId'] != null) {
                headerParameters['X-Correlation-Id'] = String(requestParameters['xCorrelationId']);
            }
            const response = yield this.request({
                path: `/v1/appointments`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: (0, index_1.AppointmentCreateRequestToJSON)(requestParameters['appointmentCreateRequest']),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.AppointmentResponseFromJSON)(jsonValue));
        });
    }
    /**
     * Create a new appointment
     * Create appointment
     */
    createAppointment(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.createAppointmentRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     * Retrieve an appointment by ID
     * Load appointment
     */
    getAppointmentRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            if (requestParameters['appointmentId'] == null) {
                throw new runtime.RequiredError('appointmentId', 'Required parameter "appointmentId" was null or undefined when calling getAppointment().');
            }
            const queryParameters = {};
            const headerParameters = {};
            if (requestParameters['xCorrelationId'] != null) {
                headerParameters['X-Correlation-Id'] = String(requestParameters['xCorrelationId']);
            }
            const response = yield this.request({
                path: `/v1/appointments/{appointmentId}`.replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters['appointmentId']))),
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.AppointmentResponseFromJSON)(jsonValue));
        });
    }
    /**
     * Retrieve an appointment by ID
     * Load appointment
     */
    getAppointment(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.getAppointmentRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     * Reschedule an existing appointment
     * Reschedule appointment
     */
    rescheduleAppointmentRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            if (requestParameters['appointmentId'] == null) {
                throw new runtime.RequiredError('appointmentId', 'Required parameter "appointmentId" was null or undefined when calling rescheduleAppointment().');
            }
            if (requestParameters['rescheduleAppointmentRequest'] == null) {
                throw new runtime.RequiredError('rescheduleAppointmentRequest', 'Required parameter "rescheduleAppointmentRequest" was null or undefined when calling rescheduleAppointment().');
            }
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            const response = yield this.request({
                path: `/v1/appointments/{appointmentId}/reschedule`.replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters['appointmentId']))),
                method: 'PUT',
                headers: headerParameters,
                query: queryParameters,
                body: (0, index_1.RescheduleAppointmentRequestToJSON)(requestParameters['rescheduleAppointmentRequest']),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.AppointmentResponseFromJSON)(jsonValue));
        });
    }
    /**
     * Reschedule an existing appointment
     * Reschedule appointment
     */
    rescheduleAppointment(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.rescheduleAppointmentRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
}
exports.AppointmentsAPIApi = AppointmentsAPIApi;
