/* tslint:disable */
/* eslint-disable */
/**
 * POS Shop Manager Service API
 * Shop Manager service for managing shop operations and staff
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AssignmentResponse,
  CreateAssignmentRequest,
} from '../models/index';
import {
    AssignmentResponseFromJSON,
    AssignmentResponseToJSON,
    CreateAssignmentRequestFromJSON,
    CreateAssignmentRequestToJSON,
} from '../models/index';

export interface CreateAssignmentOperationRequest {
    appointmentId: string;
    createAssignmentRequest: CreateAssignmentRequest;
}

export interface ListAssignmentsRequest {
    appointmentId: string;
}

/**
 * 
 */
export class AssignmentControllerApi extends runtime.BaseAPI {

    /**
     */
    async createAssignmentRaw(requestParameters: CreateAssignmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AssignmentResponse>> {
        if (requestParameters['appointmentId'] == null) {
            throw new runtime.RequiredError(
                'appointmentId',
                'Required parameter "appointmentId" was null or undefined when calling createAssignment().'
            );
        }

        if (requestParameters['createAssignmentRequest'] == null) {
            throw new runtime.RequiredError(
                'createAssignmentRequest',
                'Required parameter "createAssignmentRequest" was null or undefined when calling createAssignment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/appointments/{appointmentId}/assignments`.replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters['appointmentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAssignmentRequestToJSON(requestParameters['createAssignmentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssignmentResponseFromJSON(jsonValue));
    }

    /**
     */
    async createAssignment(requestParameters: CreateAssignmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AssignmentResponse> {
        const response = await this.createAssignmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listAssignmentsRaw(requestParameters: ListAssignmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AssignmentResponse>>> {
        if (requestParameters['appointmentId'] == null) {
            throw new runtime.RequiredError(
                'appointmentId',
                'Required parameter "appointmentId" was null or undefined when calling listAssignments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/appointments/{appointmentId}/assignments`.replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters['appointmentId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AssignmentResponseFromJSON));
    }

    /**
     */
    async listAssignments(requestParameters: ListAssignmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AssignmentResponse>> {
        const response = await this.listAssignmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
