/* tslint:disable */
/* eslint-disable */
/**
 * Positivity Product API
 * API documentation for the Product service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  Page,
  TreadDesignDto,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    PageFromJSON,
    PageToJSON,
    TreadDesignDtoFromJSON,
    TreadDesignDtoToJSON,
} from '../models/index';

export interface GetTreadDesignForProductRequest {
    productId: string;
}

export interface ListUnmatchedTreadDesignsRequest {
    page?: number;
    size?: number;
}

/**
 * 
 */
export class TreadDesignEnrichmentApi extends runtime.BaseAPI {

    /**
     * Returns the manufacturer marketing content matched to a product — names, copy per language, artwork — distinguishable from catalog-owned product data because it lives here rather than on the product itself. Use this tool to show manufacturer marketing copy alongside a product; do not use it as a source for any structural or identity field, since a supplier fact never changes what a product is. Preconditions: the product must exist and must have matched a tread design; fuzzy matching on vendor brand and design names means many products, especially newly priced ones, match nothing yet. Required inputs: productId path parameter; there is no request body. Emits a CATALOG_TREAD_DESIGN_FOR_PRODUCT event; no state changes. Returns 404 when the product does not exist or matches no tread design — an ordinary outcome, not an error condition. 
     * Get Vendor Tread-Design Enrichment for a Product
     */
    async getTreadDesignForProductRaw(requestParameters: GetTreadDesignForProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TreadDesignDto>> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling getTreadDesignForProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["ROLE_ADMIN", "ROLE_CATALOG_VIEW"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/catalog/tread-designs/for-product/{productId}`.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreadDesignDtoFromJSON(jsonValue));
    }

    /**
     * Returns the manufacturer marketing content matched to a product — names, copy per language, artwork — distinguishable from catalog-owned product data because it lives here rather than on the product itself. Use this tool to show manufacturer marketing copy alongside a product; do not use it as a source for any structural or identity field, since a supplier fact never changes what a product is. Preconditions: the product must exist and must have matched a tread design; fuzzy matching on vendor brand and design names means many products, especially newly priced ones, match nothing yet. Required inputs: productId path parameter; there is no request body. Emits a CATALOG_TREAD_DESIGN_FOR_PRODUCT event; no state changes. Returns 404 when the product does not exist or matches no tread design — an ordinary outcome, not an error condition. 
     * Get Vendor Tread-Design Enrichment for a Product
     */
    async getTreadDesignForProduct(requestParameters: GetTreadDesignForProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TreadDesignDto> {
        const response = await this.getTreadDesignForProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns tread designs that fuzzy matching, scoped to each design\'s own vendor\'s priced products, could not resolve to any catalog product, newest applied first. Use this tool to review enrichment a person needs to connect manually; do not use it to look up one product\'s enrichment, which is getTreadDesignForProduct. A design matching nothing is an ordinary outcome here, not a failure of ingestion. Preconditions: none; an empty result means every applied design has matched at least one product. Required inputs: none; page and size are optional, with size defaulting to 50 and capped at 200. Emits a CATALOG_TREAD_DESIGN_UNMATCHED_LIST event; no state changes. Returns 200 with an empty items array when nothing is unmatched. 
     * List Vendor Tread Designs Matched to No Product
     */
    async listUnmatchedTreadDesignsRaw(requestParameters: ListUnmatchedTreadDesignsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Page>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", ["ROLE_ADMIN", "ROLE_CATALOG_VIEW"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/catalog/tread-designs/unmatched`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageFromJSON(jsonValue));
    }

    /**
     * Returns tread designs that fuzzy matching, scoped to each design\'s own vendor\'s priced products, could not resolve to any catalog product, newest applied first. Use this tool to review enrichment a person needs to connect manually; do not use it to look up one product\'s enrichment, which is getTreadDesignForProduct. A design matching nothing is an ordinary outcome here, not a failure of ingestion. Preconditions: none; an empty result means every applied design has matched at least one product. Required inputs: none; page and size are optional, with size defaulting to 50 and capped at 200. Emits a CATALOG_TREAD_DESIGN_UNMATCHED_LIST event; no state changes. Returns 200 with an empty items array when nothing is unmatched. 
     * List Vendor Tread Designs Matched to No Product
     */
    async listUnmatchedTreadDesigns(requestParameters: ListUnmatchedTreadDesignsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Page> {
        const response = await this.listUnmatchedTreadDesignsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
